// Material de Estudo Auto-Gerado para a disciplina: Estudo Contemporâneo e Transversal_ Autonomia Intelectual, Relação de Consumo e Sustentabilidade
window.FisioMaterials = window.FisioMaterials || {};
window.FisioMaterials["s7_estudo_contemp"] = {
  "title": "Estudo Contemporâneo e Transversal_ Autonomia Intelectual, Relação de Consumo e Sustentabilidade",
  "toc": [
    {
      "title": "_GoBack",
      "page": 26
    }
  ],
  "pages": [
    {
      "number": 1,
      "text": "ALFREDO PIERITZ NETTO\nGUILHERME AUGUSTO HILÁRIO LOPES\nESTUDO \nCONTEMPORÂNEO \nE TRANSVERSAL:\nAUTONOMIA \nINTELECTUAL, \nRELAÇÃO DE \nCONSUMO E \nSUSTENTABILIDADE"
    },
    {
      "number": 2,
      "text": "Coordenador(a) de Conteúdo \nVera Lucia Hoffmann Pieritz\nProjeto Gráfico e Capa\nArthur Cantareli Silva\nEditoração\nAlan Diego Hordina; Ellen Jeane Versari; \nLaura Janke\nDesign Educacional\nAmanda Peçanha dos Santos\nRevisão Textual\nSalen Nascimento\nIlustração\nAndre Luis Azevedo da Silva\nEduardo Aparecido Alves\nFotos\nShutterstock e Envato\nImpresso por: \nBibliotecária: Leila Regina do Nascimento - CRB- 9/1722.\nFicha catalográfica elaborada de acordo com os dados fornecidos pelo(a) autor(a).\nNúcleo de Educação a Distância. NETTO, Alfredo Pieritz; LOPES, \nGuilherme Augusto Hilário.\nEstudo Contemporâneo e Transversal: Autonomia Intelectual, \nRelação de Consumo e Sustentabilidade / Alfredo Pieritz Netto, \nGuilherme Augusto Hilário Lopes. - Florianópolis, SC: Arqué, 2024.\n56 p.\n1. Autonomia 2. Consumo 3. Sustentabilidade 4. EaD. I. Título.\nCDD - 339.47\nEXPEDIENTE\nFICHA CATALOGRÁFICA\nN964\nISBN digital 978-65-279-0938-5"
    },
    {
      "number": 3,
      "text": ""
    },
    {
      "number": 4,
      "text": "RECURSOS DE IMERSÃO\nUtilizado para temas, assuntos ou conceitos avançados, levando ao aprofundamento do que está sendo trabalhado \nnaquele momento do texto. \nAPROFUNDANDO\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você \nterá indicações de filmes \nque se conectam com o \ntema do conteúdo.\nINDICAÇÃO DE FILME\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você terá \nindicações de livros que \nagregarão muito na sua \nvida profissional.\nINDICAÇÃO DE LIVRO\nUtilizado para desmistificar pontos \nque possam gerar confusão sobre o \ntema. Após o texto trazer a explicação, \nessa interlocução pode trazer pontos \nadicionais que contribuam para que \no estudante não fique com dúvidas \nsobre o tema. \nZOOM NO CONHECIMENTO\nEste item corresponde a uma proposta \nde reflexão que pode ser apresentada por \nmeio de uma frase, um trecho breve ou \numa pergunta. \nPENSANDO JUNTOS\nUtilizado para aprofundar o \nconhecimento em conteúdos \nrelevantes utilizando uma linguagem audiovisual.\nEM FOCO\nUtilizado para agregar um conteúdo \nexterno.\nEU INDICO\nProfessores especialistas e convidados, ampliando as discussões sobre os temas por meio de \nfantásticos podcasts.\nPLAY NO CONHECIMENTO\nPRODUTOS AUDIOVISUAIS\nOs elementos abaixo possuem recursos \naudiovisuais. Recursos de mídia disponíveis no conteúdo digital do ambiente \nvirtual de aprendizagem.\n4"
    },
    {
      "number": 5,
      "text": "6TEMA 1\nUNIVERSO: A PARTE É MAIOR QUE O TODO, OU O TODO É MAIOR QUE A PARTE? 6\nENTENDENDO O TODO E AS PARTES: UM RELACIONAMENTO DELICADO. . . . . . . . . 9\nA FORÇA DA DEMOCRACIA PARA A MANUTENÇÃO DO TODO . . . . . . . . . . . . . . . . . 9\nA FORÇA COERCITIVA DO TODO E AS LIMITAÇÕES E FINITUDES EXISTENCIAIS \nDAS PARTES . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .13\nCONHECENDO EM ESPECÍFICO AS PARTES . . . . . . . . . . . . . . . . . . . . . . . . . . . . .13\nA HISTORICIDADE E A QUESTÃO RACIAL . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19 \n29TEMA 2\nCONTRA FATOS E ATOS, NÃO HÁ BOATOS; A VIDA É PARA VIVER, MAS COMO VIVER \nE CONVIVER? 29\nSOCIEDADE MODERNA: CLASSES, CONSUMO E RELAÇÕES SOCIAIS . . . . . . . . . . . 32\nEQUIDADE, JUSTIÇA E CONTROLE SOCIAL. . . . . . . . . . . . . . . . . . . . . . . . . . . . . 39\nHUMANIZAÇÃO, SUSTENTABILIDADE E INTEGRAÇÃO SOCIAL . . . . . . . . . . . . . . . 46\n5\nSUMÁRIO"
    },
    {
      "number": 6,
      "text": "MINHAS METAS\nUNIVERSO: A PARTE É MAIOR QUE \nO TODO, OU O TODO É MAIOR QUE A \nPARTE?\nAnalisar o sujeito-cidadão, a partir de suas definições e sua dinamicidade.\nEstudar a amplitude e a dimensão da cidadania.\nPrecisar o impacto da cultura no processo de construção do todo.\nCompreender a importância da individualização como processo de humanização.\nRelacionar a democracia ao processo de cidadania, a partir da alteridade.\nAnalisar a importância da singularização dos grupos e a sua necessidade de acolhimento \npelo Estado, a partir dos discursos da vulnerabilidade e igualdade.\nCompreender a necessidade de equilíbrio entre a coercitividade estatal e a autonomia.\nTEMA DE APRENDIZAGEM 1\n6"
    },
    {
      "number": 7,
      "text": "INICIE SUA JORNADA\nDurante um debate que participei, deparei-me com a hipótese de um idoso, com \nidade superior a 90 anos, que tinha um diagnóstico de doença terminal, cuja \nexpectativa de vida era remota, mas que precisava de um medicamento oneroso, \nnão fornecido voluntariamente pelo Sistema Único de Saúde (SUS), para experimentar alguma sobrevida. A partir desse caso, determinado agente público \ndefendeu que seria um absurdo a concessão do medicamento pelo Estado, na \nmedida em que a expectativa de vida é baixa e os recursos públicos são limitados. \nPor isso, com os valores gastos com esse paciente, o Estado poderia investir em \noutras tantas esferas.\nEm razão dessa angústia, existe limite de idade para a defesa do direito à vida e \nà saúde? Devemos tratar uma vida através de um discurso tão numérico? O que \nvale mais: uma vida, ainda que idosa, ou os recursos da coletividade? Como har monizar os interesses entre o todo e as partes?\nO fato é que a defesa da vida, compreendida como direito fundamental, é a razão \nexistencial da sociedade.\nAlém disso, pergunto-lhe: quem nunca se sentiu isolado, apesar de viver em \numa sociedade? Quem jamais se sentiu oprimido pelas pressões de um grupo \nmicro ou macro?\nQuando falamos da tomada de decisões, entendemos que a própria Lei é um \nconjunto de decisões do seu criador. Por exemplo, quando o legislador defendeu \na monogamia, isso significa que o autor da Lei está repudiando a bigamia. Essa \ndecisão do todo impacta diretamente a vida das pessoas, pois, por mais que \nalguém queira viver uma relação poliamorista, por conta de suas convicções \npessoais, ninguém poderá manter dois casamentos ao mesmo tempo.\nA cidadania, casada com a democracia, significa participar, ter as suas deficiências \nprotegidas, desde que a sua decisão não comprometa terceiros ou a sociedade \ncomo um todo.\n7"
    },
    {
      "number": 8,
      "text": "TEMA DE APRENDIZAGEM 1\nPor tudo isso, vamos juntos pensar na harmonização do todo e das partes, \nisto é, precisamos tentar equilibrar os interesses da sociedade, conhecendo \ndiversos grupos.\nPense bem: qual é o ambiente em que devemos estudar esse assunto? De \ninício, deve ser construída a ideia de que a cidadania significa pertencimento \ne participação em um contexto de sociedade. Assim, de que maneira você \nexerce a cidadania?\nA cidadania exige unidade e relacionamentos humanos mais sólidos, além da \ntomada de decisões constantes. Em outras palavras, a liquidez dos relacionamentos humanos pode ser um entrave para a unidade em sociedade e, reflexamente, \npode impactar no exercício da cidadania, que em seu “coração” conceitual valoriza \na necessidade de esforços para a manutenção da coletividade e unidade.\nA compreensão da cidadania é decisiva para a conjugalidade entre o todo e \nas partes.\nVAMOS RECORDAR?\nÉ importante relembrar que a cidadania é um processo que está em constante \nreleitura. O ponto de partida desse estímulo passa pela formação cultural sólida, \natravés da democracia, cuja marca é a genuína participação nas esferas macro, \natravés da iniciativa popular ou através de condutas que prestigiem a coletividade; \nassim, o que precisamos é de solidez. Sobre esse discurso de solidez micro \nou macro, sugiro a leitura de: Amor Líquido: sobre a fragilidade dos laços humanos, de Zygmunt Bauman.\n8"
    },
    {
      "number": 9,
      "text": "DESENVOLVA SEU POTENCIAL\nENTENDENDO O TODO E AS PARTES: UM RELACIONAMENTO \nDELICADO\nSempre que você pensar no relacionamento entre o todo e as partes, pense na \ncidadania e na democracia; precisamos identificar que cidadania é um direito, a \npartir de um olhar normativista, de participação popular, com larga convergência \naos parâmetros da democracia. Além disso, é um sentimento de pertencimento, \ncom inevitáveis renúncias, não comprometedoras da individualidade, tendo em \nvista a salubridade do todo.\nA FORÇA DA DEMOCRACIA PARA A MANUTENÇÃO DO TODO\nNa realidade constitucionalista brasileira, são características importantes para \nentender a cidadania e a participação dos cidadãos perante o todo: consenso e \nparticipação, que nos remetem ao regime democrático, a partir do voto secreto, \nperiódico e universal, previsto no Art. 60, parágrafos 4º e 14 da atual Constituição \nda República Federativa do Brasil.\n9"
    },
    {
      "number": 10,
      "text": "TEMA DE APRENDIZAGEM 1\nO senso de bem comum, coletividade dentro das suas \nrelações privadas\nA ideia de função social passa pelo exercício do direito ao voto, coletivamente e \nempresarialmente. Nesse exercício, a Lei nº 6.404, de 15 de dezembro de 1976, \nLei das Sociedades Anônimas, prevê que, no exercício do direito ao voto, que é \numa cidadania empresarial, se acontecer a colisão entre os direitos individuais \ndo acionista e os interesses coletivos, estes devem preferir aqueles. No mesmo \nsentido, o eleitor, ao exercer a sua cidadania, deverá primar pelos interesses coletivos sobre os particulares. Entretanto, não é assim que, comumente, acontece.\nIdeia de participação do povo em órgãos e esferas da \nsociedade\nA composição do Conselho Nacional de Justiça, conforme o Art. 103-B da atual \nConstituição da República Federativa do Brasil, conta com a presença de dois \ncidadãos, entre os 15 conselheiros.\n1\n1"
    },
    {
      "number": 11,
      "text": "Independentemente de seu prévio conhecimento científico ou biológico sobre a \nLei de Biossegurança, Lei nº 11.105, de 24 de março de 2005, chama a atenção que \nesse julgamento é de grande sensibilidade e envolve o direito à vida. Por isso, o \nSupremo Tribunal Federal convocou audiência pública, o que autorizou o pronunciamento de autoridades da Medicina, sobre o início do direito à vida, assim como \nautoridades eclesiásticas, as quais foram também convocadas.\nIniciativa popular e seus perigos quantitativos\nChama a atenção a iniciativa de lei popular, inclusive prevista no Art. 61 do \ntexto constitucional, que permitirá ao povo propor determinadas leis para que \no Congresso Nacional aprove. Nesse tom, chama a atenção o rigorismo para a \nsubmissão da proposta de lei de iniciativa popular, isto é, criar extremada dificuldade para concretizar o direito, é como afastar o direito. Pensamos, assim, por \nconta do fato de que os requisitos são:\na) Ao menos 1 (um) % do eleitorado nacional; b) representados em 5 (cinco) Estados, no mínimo; c) em cada um dos Estados, ao menos 0,3% de seu eleitorado; a \nnossa compreensão de cidadania passa por dimensionar o exato nível da participação, o que, quanto à Lei de Iniciativa Popular, parece ser um exercício distante.\nDe quantos plebiscitos você participou? De quantos \nreferendos?\nA nossa cidadania e democracia, embora provida de instrumentos abstratamente interessantes, muitos deles são pouco utilizados, implicando uma cidadania, \nem certa medida, manca. Portanto, uma interatividade branda entre o todo e as \npartes, o que significa que a cidadania é muito mais impositiva do que dialética. \nEm outros termos, as leis, compostas pelo método coercitivo, são criadas pelos \nrepresentantes políticos, sem diagnosticar os exatos desígnios do povo, a partir \nde uma percepção superficial das aspirações populares.\n1\n1"
    },
    {
      "number": 12,
      "text": "TEMA DE APRENDIZAGEM 1\nEm contrapartida, a função do Direito, como essência, epistemologia e método, não significa a curvatura à sociedade, por mais viciada que seja. Por exemplo:\nImaginemos que a sociedade, em sua maioria, pretenda aprovar a suposta lei de \ncasamento entre crianças. Por conta dessa hipotética atmosfera social, o Congresso Nacional necessariamente deverá aprovar, significando um Poder Legislativo de mera chancela das paixões sociais? Cremos que não é esse o caminho, na \nmedida em que a racionalidade exige compreender a complexidade do casamento \ncomo comunhão plena de vida, patrimonial, física e emocional.\nEm termos técnicos, cidadania, como pertencimento ao povo, segundo Gamba \n(2022), pode estar ligada, por exemplo, ao fato de ter cadastramento eleitoral ou \nter a nacionalidade brasileira. A partir disso, encontramos um critério formal \nde cidadania.\nOs valores necessários para a proteção do todo\nA cidadania exige ponderar os parâmetros da boa-fé, eticidade e função social, \ntendo em vista a necessidade de lealdade, coerência e senso coletivo, em busca \ndo bem comum. Aliás, comumente nos deparamos com uma colisão entre os \nnossos interesses individuais e os coletivos. \nVOCÊ SABE RESPONDER?\nQuais são os critérios que você se ampara para a escolha dos candidatos? \nO que melhor representa a sua classe e o que torce para a mesma equipe \nfutebolística que a sua? Ou o candidato que melhor contribuirá para o bem \nda coletividade?\nA partir disso, começamos a perceber que o sentimento de pertencimento ao \ntodo nos exige pensar de modo coletivo, o que é delicado, tendo em vista o \nestado de natureza.\n1\n1"
    },
    {
      "number": 13,
      "text": "A FORÇA COERCITIVA DO TODO E AS LIMITAÇÕES E \nFINITUDES EXISTENCIAIS DAS PARTES\nDevemos pensar em uma cidadania forçosa ou voluntária? Igualmente complexa \na questão, o que nos exige também pensar na cultura normativista e imperativa \nda ciência do Direito e dos aparatos estatais.\nDiante dessa finitude, limitação e nocividade, como trabalhar o senso altruísta e coletivo? É delicado. No entanto, as reflexões giram em torno das ideologias, \ncrenças, formação cultural e ética. Nesse discurso, viver de modo funcionalizado, \nsolidarista e humanista, é compreender sensivelmente que todos se submetem \nao irrefreável processo de envelhecimento:\n “\nO envelhecimento – esse processo biológico e vital, inerente ao ser \nhumano (conforme ocorre na Natureza) – é considerado, nos ter mos legais, um direito personalíssimo, afeto aos direitos da personalidade, isto é, que se revestem da qualidade de intransmissibilidade \n(GARCIA; LEITE; SERAPHIM, 2016, p. 26).\nT ambém, nas palavras de Kübler-Ross (1981, p. 19 apud SÁ; LIMA, 2022, p. 69):\n “\nMorrer se torna um ato solitário e impessoal porque o paciente \nnão raro é removido de seu ambiente familiar e levado às pressas \npara uma sala de emergência. Qualquer um que tenha estado muito doente e necessitado de repouso e conforto se lembrará de ter \nsido posto numa maca sob o som estridente da sirene, e da corrida \ndesenfreada até se abrirem os portões do hospital \nCONHECENDO EM ESPECÍFICO AS PARTES\nO propósito existencial de um ordenamento jurídico é a construção de uma \nsociedade livre, justa e solidária, nos termos do Art. 3º da Constituição Federal. \nEssa análise nos permite retomar a discussão sobre a tomada de decisões no \nambiente político e a democracia indireta.\n1\n1"
    },
    {
      "number": 14,
      "text": "TEMA DE APRENDIZAGEM 1\nO povo, compreendido como o todo, e suas especificidades\nA expressão povo, por si só, é abrangente e acolhe toda a coletividade, em níveis \nde pertencimento. Por isso, não tem como fugir dos debates organicistas e naturalistas. O certo é que ser povo é ser agente de relacionamentos, horizontalmente, \ncom os seus pares e, verticalmente, com o Estado.\nNa teoria organicista, conforme Gamba (2022), admite-se uma analogia com o \ncorpo humano, na medida em que tanto a sociedade quanto o corpo humano têm \numa série de órgãos. No mesmo sentido, a sociedade é um organismo, que se \ndesdobra em diversos órgãos, sendo certo que os cidadãos são os órgãos, isto é, \nos órgãos terão o propósito de proteger e salvaguardar o organismo.\nPor outro lado, na teoria mecanicista, o protagonista é o indivíduo, inclusive \nnuma percepção de felicidade individual. Nessa visão, instaura-se, inclusive, mais \nliberdade para os indivíduos, quando comparamos com a teoria organicista. O \nentendimento de unidade auxilia a compreensão do todo, que é composto pelas \npartes, refletidas no todo. Sendo certo que a parte só é “enquanto postas pelo \ntodo” (HEGEL, 1989, p. 25). Assim, a ideia de alteridade revela a impossibilidade \nde exteriormente se ignorar o outro, numa universalidade.\nComo defendido por Bretas (2022):\n “\nCada membro do universal deve ser levado em conta, sob pena de \nnão ser universal. Assim, na eticidade do singular não há nenhum \nser que possa ser excluído, em razão da individualidade, universalidade e absolutismo. Nesse horizonte de particularidades, é possível \nidentificar carências, necessidades etc. (BRETAS, 2022, p. 133).\nDessa forma, compreende-se a humanidade, a completude, a coletividade e \na cidadania.\nEsse pertencimento atrai o princípio da igualdade, que só faz sentido se for \nmediante o reconhecimento das diferenças, em especial com base no estudo sensível da vulnerabilidade, que significa a necessidade de tratamento vulnerável; \nassim, a vulnerabilidade, composta por várias espécies, segundo Bretas (2020), \n1\n4"
    },
    {
      "number": 15,
      "text": "significa a percepção de diversas fragilidades, como as de ordem física, emocional, processual, jurídica, econômica, técnica, informacional, entre outras. Nesse \ndiscurso, cabe a análise de T avares (2013), ao pensar sobre a não discriminação \ne o reconhecimento das diferenças:\n “\nOs elementos, ou situações, constitucionalmente arrolados (sexo, \ncor etc.), na realidade, relacionam-se a ocorrências discriminatórias \natentatórias de direitos fundamentais, muito comuns em determinadas épocas históricas, utilizadas indiscriminadamente e gratuitamente como forma de distinção e, o mais das vezes, punição. Foram \nsituações de injustiça, que marcaram profundamente o espírito dos \nHomens, e que, por isso, o constituinte brasileiro pretendeu pôr a \nsalvo os indivíduos para o futuro. Assim, a título exemplificativo, foi \no caso da escravidão dos negros (distinção em função da raça), da \nsubmissão das mulheres (por força do sexo) e outros tantos casos \n(TAV ARES, 2013, p. 291).\nA partir da sensibilidade do reconhecimento da vulnerabilidade, a percepção da \nequidade se torna mais palpável, além de gerar acolhimento e representatividade, o que nos faz migrar de uma ideia de igualdade abstrata para a isonomia, \ncomo acolhimento real e reconhecimento ativo das vulnerabilidades, tornando \no todo mais equilibrado, mais equânime, por conta da redução dos abismos. De \nmaneira que, se as partes, isto é, os grupos forem mais sólidos, os membros, de \nantemão, o todo será mais solidamente estruturado. A princípio, entre o todo e \nas partes há uma relação de complementariedade, interdependência, além do \ncaráter estruturante, pelo fato de que a solidez do todo se reflete nas partes e \nreciprocamente também.\nTrata-se de um universo intrigante, pois estamos inseridos num todo, por conta \nda paridade da finitude e das limitações existenciais, o que uniformiza os seres \nhumanos. Além disso, pertencemos ao todo, dentro de fragmentos, em deter minados grupos de pertencimentos patrimoniais e existenciais.\nZOOM NO CONHECIMENTO\n1\n5"
    },
    {
      "number": 16,
      "text": "TEMA DE APRENDIZAGEM 1\nO fortalecimento da paz, harmonia e restauração\nA cidadania e a mantença do todo depende de preservar a sociedade. Por isso, \ndos métodos, é o fortalecimento do discurso constitucional da paz, além do \ncaráter restaurativo das relações adoecidas, a solução pacífica dos conflitos e \no espírito mediador.\n “\nA escuta ativa engloba uma série de ações comunicacionais verbais e \nnão verbais, tais como: perguntas com final aberto, rotulagem emocional (tom de voz passivo, gestos de abertura, olhar direcionado à \npessoa, leve inclinação do corpo para frente), ato de parafrasear o \noponente, adoção de atitudes pequenas de encorajamento (aceno \ncom a cabeça, utilização de sons indicativos de concordância e compreensão “mmm” ou “uh-huh”) e emprego do silêncio (expressões \nfaciais agradáveis que permitem ao oponente continuar falando de \nforma confortável) (FARIAS, 2022, p. 813).\nA cidadania, como participação, também decorre da liberdade de expressão, por \nmais que seja limitada e que possa significar a tensão entre grupos. Entretanto, \no amadurecimento do discurso, passa pelo reconhecimento de outras variáveis \ne da própria confrontação.\nVocê conhece a vulnerabilidade, de modo específico?\nPor exemplo, o melhor interesse da criança é defensor do reconhecimento da \nvulnerabilidade emocional, física e biológica do menor. Por isso, as políticas públicas, as decisões normativas e jurisprudenciais devem primar pelo tratamento \ndiferenciado e protetivo dos vulneráveis. Assim:\n “\n[...] o princípio do interesse superior (também denominado princípio do melhor interesse) não se encontra expresso nessa formulação, nem no ECA nem na CF . Porém, pode-se afirmar que decorre \nda interpretação harmônica de todo o sistema jurídico referente aos \ndireitos de crianças e adolescentes (ZAPATER, 2023, p. 29).\n1\n6"
    },
    {
      "number": 17,
      "text": "Segundo Bretas (2020), qual seria a vulnerabilidade aplicável diretamente ao \nidoso? A física, sobre a qual importa a percepção de limitações orgânicas: “Há \numa alteração do sistema nervoso, à medida que se envelhece, há perda de células, \ndiminuindo o volume do cérebro. Desse modo, “o corrente do idoso fica mais \nlento, todavia, permanece ativo” (VERAS, 1999, p. 76).\nDentro desse discurso, temos o choque geracional, dentro de uma visão tecnológica. Já pensou nisso? Somos uma sociedade de diversidades, isto é, o todo \ntraz imposições e exclusões, de maneira que as imposições tecnológicas sociais, \ncomo a necessidade premente de interação nas redes sociais, exercem violenta \nforça de repulsão em face daqueles que não se adaptam. Apesar de a sociedade \nser tecnológica, como estabelecer a saudável convivência entre gerações mais \nnovas, estritamente tecnológicas, versus os idosos, os quais, comumente, não \nsabem lidar com a tecnologia, implicando, até mesmo, a tecnofobia? Assim, \no todo exerce poder sobre as partes, mas as partes merecem tutela, tendo em \nvista o humanismo.\nO letramento digital é primordial, a partir do reconhecimento dos benefícios \nque a internet é capaz de promover e que o acesso a diversos aparatos estatais \ndependem de recursos tecnológicos.\nAmor.com\nAno: 2017\nSinopse: A cidadania não pode ser artificial e tampouco ser exercida no universo paralelo; sobre esse paralelismo perigoso de \nuniversos e a premência da educação digital responsável, sugiro o filme Amor.com, estrelado por Isis Valverde, que representa \na influencer digital Katrina, engajada em dicas de moda, em seu \ncanal no YouTube, responsável pela ostensiva divulgação de \nvídeos. Nesse engajamento, Katrina passa a viver um confronto \nentre a sua dignidade no mundo real e a sua imagem artificial, \nconstruída conforme o que os seus seguidores pretendiam.\nINDICAÇÃO DE FILME\n1\n7"
    },
    {
      "number": 18,
      "text": "TEMA DE APRENDIZAGEM 1\nA vulnerabilidade do idoso e seus desafios de cidadania\nO idoso, quando desprovido de conhecimentos tecnológicos, é hipervulnerável, \nem razão de sua condição de vulnerável físico, associado ao fato de ser consumidor e idoso. Por esse motivo, nos termos do Art 229 da Constituição Federal \nde 1988, deve haver amparo ao idoso.\n “\nÉ obrigação da família, da comunidade, da sociedade e do Poder \nPúblico assegurar ao idoso, com absoluta prioridade, a efetivação \ndo direito à vida, à saúde, à alimentação, à educação, à cultura, ao \nesporte, ao lazer, ao trabalho, à cidadania, à liberdade, à dignidade, \nao respeito e à convivência familiar e comunitária (BRASIL, 1988).\nO todo se constrói a partir do conhecimento das partes, conforme as suas individualidades. Por isso, a coletividade, além das vulnerabilidades de grupos etários, \nencontra outros incontáveis grupos de vulneráveis, como o Código de Proteção \nao Consumidor.\nNo mesmo âmbito físico, a Lei nº 13.146, de 6 de julho de 2015, instituiu o \nEstatuto da Pessoa com Deficiência, em busca do acolhimento aos portadores \nde deficiência física ou psíquica. Essa previsão é primordial, pois, independen temente da deficiência, é necessário acolher e reconhecer. Apartir desse olhar, \num dos impactos desse Estatuto é solidificar a premissa de que o portador da \nsíndrome de Down, por exemplo, pode se casar. Afinal, afastar desse grupo de \nmodo absoluto o instituto central do casamento, é espancar a cidadania.\nSobre essa temática, sugiro a entrevista de Hugo Rios Bretas, \nconcedida à PUC TV Minas, em 2017.\nEU INDICO\n1\n8"
    },
    {
      "number": 19,
      "text": "A HISTORICIDADE E A QUESTÃO RACIAL\nOutra discussão importante, no universo das vulnerabilidades e do fortaleci mento da igualdade e cidadania, diz respeito ao estatuto da igualdade racial, \nque preceitua a característica da historicidade dos direitos fundamentais, isto é, \nos direitos fundamentais significam conquistas obtidas ao longo da História, as \nquais devem ser protegidas, sob pena de retrocesso. A questão é muito complexa, porque a cidadania e o altruísmo são alcançados através do reconhecimento \ndas singularidades e através de fatores históricos, ou seja, há uma base forte de \nequidade. Convido-lhe a pensar sobre esta reflexão:\n “\nO caminho adequado é evitar generalizações (a culpa é da colonização) e analisar o caso concreto, identificando as dimensões do \nproblema. Provas de concurso escritas e anonimizadas dão menos \nespaço para discriminações do que uma entrevista livre na qual a cor \nda pele, o sexo ou a deficiência física aumentam a probabilidade de \ndecisões preconceituosas. Além disso, deve ser examinada a queixa \nconcreta. Nada impede que a queixa relacione a cor da pele com a \nsituação econômica, sendo essa combinação o alegado motivo da \ndiscriminação. Pode ser também que mulheres brancas e negras que \nse encontrem na mesma situação de pobreza tenham experiências \ndiferentes, pois o tratamento das mulheres negras pobres pode incluir \nagressões adicionais em razão da raça. Bastaria discutir e provar isso, \nsem se preocupar em desvendar a exata relação e dosagem de causas \ne efeitos (DIMOULIS, 2021, p. 112).\nA inteligência emocional, o mínimo existencial e as relações \nde consumo\nAs relações de consumo são irrefreáveis e dizem respeito a todos, inevitavelmente. O todo se baseia em relacionamentos, comumente marcados por interesses \neconômicos ou existenciais e por isso, o fator consumo é fundamental para compreender a relação entre o organismo e seus fragmentos.\n1\n9"
    },
    {
      "number": 20,
      "text": "TEMA DE APRENDIZAGEM 1\nÉ nebuloso pensar em cidadania, se não houver acessibilidade ao mínimo \nexistencial. Enfim, a acessibilidade, como núcleo da cidadania, gravita em torno \nda acessibilidade informacional, comunicativa, locomotiva, social, entre outras.\nVOCÊ SABE RESPONDER?\nO que é mínimo existencial? Quais são os bens e os valores a serem acessados, \nsob pena de ofensa à dignidade humana? .\nPara início: o direito à vida, à saúde, à alimentação, à moradia, à informação, entre \noutros. Conforme Bretas (2022), a teoria do patrimônio mínimo defende que a \npropriedade e a posse não são os seus principais componentes, e sim a dignidade. \nEsse discurso depende, para fins de universalização, da compreensão solidarista:\n “\nA exacerbação do individualismo acentuou na propriedade o caráter \nde inviolabilidade e de absolutismo. Hoje, já se imprime à propriedade privada um conjunto de limitações formais, sendo composto \nde restrições e induzimentos que formam o conteúdo da função \nsocial da propriedade que não se confunde como função social da \nposse. O absolutismo no exercício da propriedade sofreu a inter venção de ideias que progressivamente construíram a doutrina da \ndenominada função social da propriedade (FACHIN, 1988, p. 17).\nAs relações de consumo são estruturadas na visão de que a defesa deste grupo \né um direito fundamentalmente constitucional. Nessa perspectiva, o Direito do \nConsumidor, a partir das lições de Rizzatto Nunes (2019), que nos norteará, possui, como principal objetivo, a proteção do consumidor. Para a compreensão do \ntodo e de suas partes, acredita-se na contribuição da função social, que coloca os \ninteresses sociais versus individuais.\n1\n1"
    },
    {
      "number": 21,
      "text": "Por exemplo, por mais que o proprietário não queira pagar tributos sobre o imóvel \nno qual reside, em nome da universalidade e coletividade, é necessário que o \ntributo seja pago, caso haja o fato gerador, de forma a viabilizar economicamente \na continuidade estatal. Portanto, existem limites estatais que atingem o exercício \ndo uso e fruição da propriedade: “A reformulação operada com base nos princípios \nda socialidade, eticidade e operabilidade deu nova feição aos princípios fundamentais dos contratos” (GONÇALVES, 2020, p. 58).\nO Estado e os cidadãos\nNa confrontação, aqui, trabalhada, é básico, na Administração Pública, a valo rização do princípio da supremacia dos interesses públicos sobre os interesses \nprivados, o que tem caráter imperativo, como acontece no âmbito das desapropriações. A título de exemplo: por mais que você tenha adquirido um imóvel, \nque serve de morada para a sua família, se o Estado entender que o seu imóvel é \nnecessário para a utilidade pública, para a construção de uma escola, que beneficiará a educação no âmbito daquele município, certamente, haverá prevalência \ndos interesses coletivos.\nVOCÊ SABE RESPONDER?\nIsso é justo? O é inevitável dentro da relação entre o todo e as partes?\nApatia jurídica diante dos problemas emocionais\nDentro de uma sociedade tão complexa, marcada pelo colapso das relações humanas, efêmeras e agravadas pela pandemia, o perfil, dentro de uma sociedade, \nalém de tecnológico, exige o domínio de habilidades emocionais e do exercício \nda empatia: “perceber as necessidades e sentimentos dos outros, ouvir o que os \nliderados têm a dizer (e o que não dizem) e compreender suas reações” (ROBBINS; \nJUDGE; SOBRAL, 2010, p. 361).\n1\n1"
    },
    {
      "number": 22,
      "text": "TEMA DE APRENDIZAGEM 1\nConforme desenvolvido no Grupo de Pesquisas GEPAM: “ A gestão de pessoas \ne o assédio moral: contribuições da Psicologia Organizacional e do Trabalho e \ndo Direito para um ambiente empresarial saudável”, a inteligência emocional \nprecisa ser desenvolvida, como forma de pertencimento ao todo, de maneira \nque os traumas psíquicos constituem um vivido que ultrapassa a competência \npsíquica de apropriação e de recalcamento. Ainda que deixe marcas indeléveis na \nmemória, a experiência traumática é aquela que não se representa. Ao psiquismo \né sobreposto a capacidade de elaboração (MALDONADO; CARDOSO, 2009).\nA cidadania, como acolhimento, revela que o Direito nem sempre consegue \ncontribuir eficazmente, por exemplo, a saúde mental da pessoa humana é um dos \nnúcleos da ciência do Direito. Assim, o desenvolvimento do sólido diálogo entre \no Direito e outras ciências transcendentes, é emergente. Ora, o ordenamento \npátrio privatista não responde, adequadamente, às hipóteses de violação à per sonalidade, pois, quando alguém sofre danos morais, a resposta de acolhimento \ne cidadania não pode ser apenas a indenização, como o texto jurídico prevê.\nO ponto basilar é que a cidadania, o altruísmo, e o acolhimento estão sempre \nem construção. Trata-se de um constante estado de cidadania incipiente, que, por \nexemplo, a ciência do Direito não conseguirá resolver, ou seja, as angústias humanas.\nNOVOS DESAFIOS\nDesenvolvemos as fortes tensões entre o todo e as partes, a coletividade e os \ninteresses individuais; o certo é que a relação entre eles é de interdependência e \ncomplementariedade. Entretanto, não é possível que a sociedade acolha todas as \naspirações humanas, pois a coletividade depende de uma filtragem dos interesses \nindividuais, a valorização da dignidade, e do senso de pertencimento, expressado \npelo fortalecimento da cidadania e da percepção das fragilidades humanas.\nInfelizmente, na sociedade de hoje, percebe-se que o todo está adoecido, pois \nos fragmentos não estão devidamente acolhidos, tendo em vista as angústias e \na complexidade humana, dando vazão a uma existência possível, jamais ideal. \nAfinal, o plano racional humano, dotado de nocividades, não admite que os \nfragmentos sejam plenamente saudáveis.\n1\n1"
    },
    {
      "number": 23,
      "text": "Se as relações humanas estão em colapso, como as aquecer novamente, dentro \nde uma sociedade virtual, que nos convida cotidianamente para fugirmos do \nmundo real e vivermos no mundo paralelo?\nProjetando o futuro: você é agente de transformação da realidade e tem o \ndever de participar do humanismo e da solidez das relações humanas.\n1\n1"
    },
    {
      "number": 24,
      "text": "VAMOS PRATICAR\n1. A cidadania não se contenta com discursos meramente poéticos, simbólicos, abs tratos, vazios ou frios, na medida em que ela precisa ser concretizada todos os dias, \ninclusive através de batalhas sociais. Por isso, viver em sociedade exige o sentimento \nde pertencimento, de unidade e de coletividade, o que nos aproxima da importantís sima função social. De início, deve ser construída a ideia de que a cidadania significa \npertencimento e participação em um contexto de sociedade.\nA cidadania consiste num direito, a partir de um olhar normativista, de participação popular, com larga convergência aos parâmetros da democracia. Além disso, é um sentimento \nde pertencimento, com inevitáveis renúncias, não comprometedoras da individualidade, \ntendo em vista a salubridade do todo. A cidadania é tema de todas as esferas do saber, em \nespecial da ciência política, sociologia, antropologia e Direito, que se dedica fortemente \na compreender os limites da participação popular (GAMBA, 2022).\nFonte: GAMBA, J. R. G. Teoria geral do Estado e ciência política. 2. ed. Barueri: Atlas, \n2022.\nEm atenção a esse discurso, quais os itens abaixo significam o exercício da “democracia \ndireta”:\nI - Plebiscito.\nII - Aprovação de lei complementar.\nIII - Projeto de lei apresentado por determinado deputado federal.\nÉ correto o que se afirma em:\na) I, apenas.\nb) III, apenas.\nc) I e II, apenas.\nd) II e III, apenas.\ne) I, II e III.\n1\n4"
    },
    {
      "number": 25,
      "text": "VAMOS PRATICAR\n2. Na teoria organicista, segundo as lições de Gamba (2022), admite-se uma analogia com \no corpo humano, na medida em que tanto a sociedade quanto o corpo humano têm \numa série de órgãos. No mesmo sentido, a sociedade é um organismo, que se desdobra \nem diversos órgãos, sendo certo que os cidadãos são os órgãos. Isto é, os órgãos terão \no propósito de proteger e salvaguardar o organismo. Segundo Gamba: “[...] na teoria, \n[...] a sociedade é fim, isto é, é para a manutenção dela (e não de seus membros) que o \ntodo social existe. A sociedade é um fim em si mesma e, portanto, os membros desse \ncorpo social tendem a dar a sua vida para que o todo permaneça vivo”.\nFonte: GAMBA, J. R. G. Teoria geral do Estado e ciência política. 2. ed. Barueri: Atlas, \n2022. p. 22.\nEssa visão se refere, em caráter extremo, à seguinte teoria:\na) Mecanicista.\nb) Organicista.\nc) Naturalista.\nd) Força.\ne) Axiológica.\n3. Na teoria mecanicista, o protagonista é o indivíduo, inclusive numa percepção de felicidade individual, num caráter eudemonista. Nessa visão, instaura-se inclusive mais \nliberdade para os indivíduos, quando comparamos com a teoria organicista.\nSegundo Fábio Konder Comparato: “É a partir do período axial que o ser humano passa a \nser considerado, pela primeira vez na História, em sua igualdade essencial, como ser dotado de liberdade e razão, não obstante as múltiplas diferenças [...]. Lançavam-se, assim, \nos fundamentos intelectuais para a compreensão da pessoa humana e para a afirmação \nda existência de direitos universais, porque a ela inerentes”.\nFonte: COMPARATO, F. K. A afirmação histórica dos direitos humanos. 4. ed. rev. e \natual. São Paulo: Saraiva, 2005. p. 11.\nIsso posto, o presente texto é defensor da seguinte vertente:\na) Mecanicista.\nb) Organicista.\nc) Naturalista.\nd) Força.\ne) Contratualista.\n1\n5"
    },
    {
      "number": 26,
      "text": "REFERÊNCIAS\nBRASIL. [Constituição (1988)]. Constituição da República Federativa do Brasil de 1988. \nBrasília, DF: Presidência da República, 1988. Disponível em: http:/ /www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm. Acesso em: 28 ago. 2023.\nBRASIL. Lei nº 6.404, de 15 de dezembro de 1976. Dispõe sobre as Sociedades por Ações. \nBrasília, DF: Presidência da República, 1976. Disponível em: https:/ /www.planalto.gov.br/ccivil_03/leis/l6404consol.htm. Acesso em: 28 ago. 2023.\nBRASIL. Lei nº 9.868, de 10 de novembro de 1999. Dispõe sobre o processo e julgamento \nda ação direta de inconstitucionalidade e da ação declaratória de constitucionalidade perante o Supremo Tribunal Federal. Brasília, DF: Presidência da República, 1999. Disponível em: \nhttps:/ /www.planalto.gov.br/ccivil_03/leis/l9868.htm. Acesso em: 28 ago. 2023.\nBRASIL. Lei nº 10.741, de 1º de outubro de 2003. Dispõe sobre o Estatuto da Pessoa Idosa \ne dá outras providências. Brasília, DF: Presidência da República, 2003. Disponível em: http:/ /\nwww.planalto.gov.br/ccivil_03/leis/2003/l10.741.htm. Acesso em: 28 ago. 2023.\nBRASIL. Lei nº 11.105, de 24 de março de 2005. Regulamenta os incisos II, IV e V do § 1º do \nart. 225 da Constituição Federal, estabelece normas de segurança e mecanismos de fiscalização de atividades que envolvam organismos geneticamente modificados – OGM e seus \nderivados, cria o Conselho Nacional de Biossegurança – CNBS, reestrutura a Comissão Técnica Nacional de Biossegurança – CTNBio, dispõe sobre a Política Nacional de Biossegurança \n– PNB, revoga a Lei nº 8.974, de 5 de janeiro de 1995, e a Medida Provisória nº 2.191-9, de 23 \nde agosto de 2001, e os arts. 5º , 6º , 7º , 8º , 9º , 10 e 16 da Lei nº 10.814, de 15 de dezembro de \n2003, e dá outras providências. Brasília, DF: Presidência da República, 2005. Disponível em: \nhttps:/ /www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11105.htm. Acesso em: 28 \nago. 2023.\nBRASIL. Lei nº 13.146, de 6 de julho de 2015. Institui a Lei Brasileira de Inclusão da Pessoa \ncom Deficiência (Estatuto da Pessoa com Deficiência). Brasília, DF: Presidência da República, 2015. Disponível em: https:/ /www.planalto.gov.br/ccivil_03/_ato2015-2018/2015/lei/\nl13146.htm. Acesso em: 28 ago. 2023.\nBRETAS, H. R. A releitura do discurso de tutela da propriedade privada no âmbito da \npolítica urbana a partir da função social da propriedade. 2022. Tese (Doutorado em \nDireito) – Programa de Pós-Graduação em Direito, Pontifícia Universidade Católica de Minas \nGerais, Belo Horizonte, 2022.\nBRETAS, H. R. O idoso no sistema jurídico. São Paulo: Dialética, 2020. v. 1.\nDIMOULIS, D. Direito de igualdade: antidiscriminação, minorias sociais, remédios constitucionais. São Paulo: Almedina, 2021.\nFACHIN, L. E. A função social da posse e a propriedade contemporânea: uma perspectiva da usucapião imobiliária rural. Porto Alegre: S. A. Fabris, 1988.\n1\n6"
    },
    {
      "number": 27,
      "text": "REFERÊNCIAS\nFARIAS, B. O. de. Negociação eletrônica e comunicação não verbal como instrumentos relevantes de promoção da cultura de paz em tempos de pandemia. In: SILVA, M. C.; LAFATA, \nC. T. P. C; MELO, S. T. L. P.; OLIVEIRA, V. E. C. (org.). Impactos do coronavírus no direito: \ndiálogos, reflexões e perspectivas contemporâneas. Belo Horizonte: Newton Paiva, 2022. v. \nI. p. 805-815.\nGAMBA, J. R. G. Teoria geral do Estado e ciência política. 2. ed. Barueri: Atlas, 2022.\nGARCIA, M.; LEITE, F. P. A.; SERAPHIM, C. M. B. Comentários ao Estatuto do Idoso. São \nPaulo: Saraiva, 2016.\nGONÇALVES, C. R. Contratos e atos unilaterais. 17. ed. São Paulo: Saraiva Educação, 2020.\nHEGEL, G. W. F. Propedêutica filosófica. Lisboa: Edições 70, 1989.\nMALDONADO, G.; CARDOSO, M. R. O trauma psíquico e o paradoxo das narrativas impossíveis, mas necessárias. Psicologia Clínica, Rio de Janeiro, v. 21, n. 1, p. \n45-57. Disponível em: http:/ /pepsic.bvsalud.org/scielo.php?script=sci_arttext&pid=S0103-56652009000100004&lng=pt&nrm=iso&tlng=pt. Acesso em: 28 ago. 2023.\nNUNES, R. Curso de Direito do Consumidor. 13. ed. São Paulo: Saraiva Educação, 2019.\nROBBINS, S.; JUDGE, T. A.; SOBRAL, F. Comportamento organizacional. Tradução Rita de \nCássia Gomes. 14. ed. São Paulo: Pearson Prentice Hall, 2010.\nSÁ, M. de F. F. de.; LIMA, T. M. M. de. O direito de dizer adeus: faticidade e juridicidade. In: \nSILVA, M. C.; LAFATA, C. T. P. C.; MELO, S. T. L. P.; OLIVEIRA, V. E. C. (org.). Impactos do coronavírus no direito: diálogos, reflexões e perspectivas contemporâneas. Belo Horizonte: \nNewton Paiva, 2022. v. II. p. 67-79.\nTAVARES, A. R. Curso de direito constitucional. 11. ed. rev. e atual. São Paulo: Saraiva, \n2013.\nVERAS, R. P. (org.). Terceira Idade: alternativas para uma sociedade em transição. Rio de \nJaneiro: Relume-Dumará: UnATI–UERJ – Universidade Aberta da Terceira Idade da Universidade Estadual do Rio de Janeiro, 1999.\nZAPATER, M. C. Direito da criança e do adolescente. 2. ed. São Paulo: Saraiva-Jur, 2023.\n1\n7"
    },
    {
      "number": 28,
      "text": "1. Opção A. O plebiscito é instrumento de democracia direta, tendo em vista a ausência de \nintermediadores, isto é, sem a presença de mandatários políticos. Em sentido oposto, os \noutros itens significam o exercício da democracia indireta, por conta da presença dos \nintermediadores.\n2. Opção B. A teoria organicista é relevante para a compreensão da relação todo versus \npartes, por conta de se basear justamente no fato de que as partes pertencem ao todo \ne precisam se posicionar de tal modo que o todo seja protegido. Por outro lado, todas as \ndemais não são capazes de reproduzir a relação sacrificial dos cidadãos.\n3. Opção A. A teoria mecanicista é a que reproduz melhor o sentido do texto, na medida em \nque essa visão valoriza, sobretudo, o protagonismo das pessoas humanas, dentro de um \ncontexto de sociedade. As demais não têm explicitamente a mesma visão.\nGABARITO\n1\n8"
    },
    {
      "number": 29,
      "text": "MINHAS METAS\nCONTRA FATOS E ATOS, NÃO HÁ \nBOATOS; A VIDA É PARA VIVER, \nMAS COMO VIVER E CONVIVER?\nCompreender e analisar os conceitos de classes sociais, relações de consumo e suas \nimplicações na sustentabilidade\nConhecer e compreender os modos de vida na sociedade moderna, aspectos emocionais e \na realidade\nConhecer e compreender os modos de vida na sociedade moderna, aspectos emocionais \ne a realidade\nEntender e analisar os conceitos de sustentabilidade, humanização e consumo consciente\nAnalisar e compreender os aspectos presentes na discussão sobre a interação social e a \nbusca de justiça e equidade\nAbsorver os conceitos que permeiam a discussão sobre espacialidade urbana e a questão \nda desigualdade social\nConhecer, compreender e criticar as principais correntes envolvidas na discussão sobre a \nconstituição de classes na sociedade\nTEMA DE APRENDIZAGEM 2\n1\n9"
    },
    {
      "number": 30,
      "text": "INICIE SUA JORNADA\nÉ possível vivermos e convivermos de maneira harmoniosa, tanto com nossos \nsemelhantes quanto com a natureza a nossa volta? A sociedade moderna, com \ntoda a sua diversidade, pode ser um lugar de justiça, equidade e, ainda, respei to ao meio ambiente? Nossos atos, os fatos que ocorrem a partir das relações \nsociais, podem expressar uma humanização necessária para o bom convívio \nem sociedade?\nCertamente, você já se voltou para esses questionamentos em vários momentos de sua vida pessoal e profissional, seja por conta de suas experiências ou pela \nbusca de conhecimento sobre os assuntos abordados.\nOs nossos grandes centros urbanos estão cheios de exemplos das relações \nsociais que estamos destacando neste tema de aprendizagem. T alvez, um dos \ncenários mais conhecidos é a flagrante desigualdade social expressa pela di visa de dois bairros extremamente diferentes. Na grande cidade de São Paulo, \ntemos o bairro de Paraisópolis fazendo divisa com o bairro do Morumbi. O \nprimeiro expressa o quadro de extrema pobreza de inúmeras das comunidades \nbrasileiras de periferia, o segundo é o quadro da extrema riqueza de alguns \nindivíduos da população.\nNesse cenário, tomemos a realidade de um jovem que desenvolve um ati vismo social assíduo. Ele faz parte de uma central de moradores do bairro, Paraisópolis, que luta para melhorar a vida da comunidade. Além das dificuldades \nfinanceiras enfrentadas pelos moradores, há, ainda, a falta de saneamento básico, \no que gera alta incidência de doenças, a poluição, que vem das mansões do bairro \nvizinho, Morumbi, bem como a forte repressão por parte do poder público e das \npolíticas de segurança. O jovem desse caso visa elaborar um projeto social que \najude a mudar essa realidade, compreendendo os aspectos envolvidos e as possibilidades existentes, tanto em relação à desigualdade social e à injustiça, quanto \nao consumo consciente e à sustentabilidade. A questão é: como?\nA resolução das questões suscitadas pela nossa situação-problema não passa \npor uma única via, muito menos abarca uma visão engessada ou preconceituosa \nde sociedade. É preciso avaliar todos os aspectos envolvidos nessa situação, como \na desigualdade social, a injustiça e o uso indevido de recursos naturais por conta \n1\n1"
    },
    {
      "number": 31,
      "text": "TEMA DE APRENDIZAGEM 2\nde um consumismo sem consciência. A falta de cuidado com o meio ambiente e \nos recursos disponíveis torna as grandes cidades lugares insalubres e propensos \nao surgimento de doenças. Os fatos, os atos dos indivíduos, compõem um cenário \nno qual o convívio social se desenrola, assim, é imprescindível a busca por uma \nigualdade justa, uma interação entre desenvolvimento e sustentabilidade.\nVocê, estudante, encontrará desafios em sua carreira profissional que, certamente, estarão permeados pelos problemas sociais, aqui, levantados. Seja como \narquiteto, engenheiro florestal, assistente social, agente de segurança pública, \nprofessor, engenheiro ambiental ou mesmo na área da informação, certamente, \nterá desafios que perpassam as relações sociais e seus desdobramentos. Uma \nengenheira ambiental pode traçar um plano de metas para adequação dos tratamentos de água e esgoto, evitando a poluição de córregos e rios. Um assistente \nsocial pode desenvolver ações que levem os indivíduos a ter acesso aos direitos \nsociais, viabilizando o atendimento das pessoas que estão em situação de vulnerabilidade social. Poderíamos fazer uma longa lista de ações a serem providas em \npraticamente todas as profissões.\nEnfim, em todas as atividades profissionais, os temas da justiça social, da igualdade, da sustentabilidade e do consumo consciente podem ser vislumbrados \ne abordados de maneira teórica e prática. Dessa forma, a reflexão sobre os assuntos propostos para este tema deve partir de uma crítica, que é tanto teórica \nquanto prática, na qual você, valendo-se de suas experiências e conhecimentos \nprévios, poderá construir sua opinião de maneira autônoma e consciente.\n1\n1"
    },
    {
      "number": 32,
      "text": "VAMOS RECORDAR?\nEstudante, o cenário proposto para nossa situação-problema é o retrato de um Brasil que apresenta uma das mais \ncruéis realidades de desigualdade social do mundo. Para entendermos melhor esse cenário, é preciso conhecer todos \nos aspectos nele envolvidos. A desigualdade territorial nos \ngrandes centros urbanos, a falta de acesso ao saneamento e \nplanejamento urbano, a violência e a falta de oportunidade. \nEm vista disso, para recordarmos a relação desses aspectos \ncom o quadro proposto, indicamos a leitura do artigo jor nalístico Para moradores de Paraisópolis, vida média é 10 \nanos mais curta que no vizinho Morumbi”.\nDESENVOLVA SEU POTENCIAL\nSOCIEDADE MODERNA: CLASSES, CONSUMO E RELAÇÕES \nSOCIAIS\nQuando entramos em uma discussão sobre classes sociais, consumo, responsabilidade social e relações sociais, é indelével uma ferrenha dicotomia entre duas visões hegemônicas. De um lado, uma perspectiva mais \nliberal, que aponta para uma meritocracia que define \nos lugares sociais dos indivíduos, tanto econômica \nquanto politicamente. Em outra ponta, uma perspectiva tida como mais progressista, principalmente de \nvertente socialista, que apresenta a sociedade dividida \nem duas classes sociais.\nComecemos, então, com a perspectiva liberal, para em seguida nos debruçarmos sobre a visão socialista, ou mesmo uma visão progressista menos radical, \nmas que esteja em consonância com tal visão. Após esse primeiro movimento, \nnos deteremos na compreensão das relações de consumo dentro da sociedade \nClasses sociais, \nconsumo, \nresponsabilidade \nsocial e relações \nsociais\n1\n1"
    },
    {
      "number": 33,
      "text": "TEMA DE APRENDIZAGEM 2\nmoderna capitalista. T ais relações de consumo são determinantes para com preender as relações sociais existentes nessa sociedade, que é politicamente constituída em torno da noção de Estado, bem como economicamente estabelecida \nsobre as bases do modo de produção capitalista.\nMuito se tem tratado do liberalismo clássico, bem como do chamado neoliberalismo. Pode-se afirmar, com ressalvas em alguns pontos econômicos, que \nas duas vertentes fazem parte da mesma corrente de pensamento. Entretanto, o \nneoliberalismo ganhou força e destaque, principalmente, após o final do período \nda Guerra Fria e a abertura de mercado nos países subdesenvolvidos nas décadas \nde 1980 e 1990. Sobre tal tema, temos a opinião de Viana e Silva (2018, p. 2109):\n “\nNessa grande produção mundial sobre o tema, o neoliberalismo \nfoi visto como ideologia, como política econômica, como coalizão \npolítica hegemônica, como política das elites, como conservadorismo, como nova forma de imperialismo e como razão do mundo, \npara ilustrar algumas perspectivas de análise mais importantes dos \núltimos anos\nPor esse prisma pode-se compreender que a vertente neoliberal abarca uma discussão sobre uma enorme gama de setores da sociedade, principalmente, entre \nos países tidos como mais desenvolvidos. Essa informação é muito importante \npara se valorar a importância da perspectiva liberal dentro de uma discussão \nsobre a constituição da sociedade e suas classes sociais. Seja a partir de uma \nperspectiva liberal clássica, seja por meio de uma lente neoliberal mais atual, a \nquestão é que o cerne dessa corrente está na noção de meritocracia e livre ação \neconômica dos indivíduos.\n1\n1"
    },
    {
      "number": 34,
      "text": "O Fim da História e o Último Homem\nEditora: Rocco\nAutor: Francis Fukuyama\nSinopse: Nesta obra, Francis Fukuyama defende a visão \nliberal de mercado, alavancado pelo fim da Guerra Fria e \na vitória dos países do Bloco Capitalista, Fukuyama indica que o modelo liberal, político e econômico, é o ápice \nda História humana. Sua projeção é a de que o modelo \nliberal capitalista conquistou uma hegemonia tal que não \npode ser superado por nenhum outro modelo. Este livro embasa bem a temática liberal que temos indicado em nossa discussão, apontando, segundo o autor, os motivos pelos quais o \nliberalismo seria o melhor modelo.\nINDICAÇÃO DE LIVRO\n \nEm outros termos, o liberalismo tem como premissa a noção de que cada indivíduo deve ser livre e autônomo para desenvolver suas potencialidades, suas \nhabilidades e estabelecer suas atividades produtivas e econômicas.\nA partir dessa perspectiva, os indivíduos que conseguem mais êxito terão melhores condições econômicas e sociais, não podendo ser limitados ou prejudicados \npelas instituições públicas. As classes sociais seriam, então, o arranjo justo dessas \ndisputas, que devem ser livres e favorecer o esforço pessoal de cada indivíduo. \nComo apontam W ayne e Cabral (2021, p. 3):\n “\nO etos da meritocracia de (i) liberdade individual, de (ii) frutos justos do trabalho árduo e dos (iii) talentos e a ideia de mobilidade social alheia às origens de classe triunfando sobre as barreiras sociais \nfoi fundamental para a marca de Conservadorismo de Margaret \nThatcher, nos anos 1980, e para a marca do Liberalismo Social de \nT ony Blair, durante o período dos governos do Novo Trabalhismo \nentre 1997 e 2010 (W AYNE; CABRAL, 2021, p. 3).\n1\n4"
    },
    {
      "number": 35,
      "text": "TEMA DE APRENDIZAGEM 2\nPara o liberalismo, o fator determinante para definir a situação econômica de um \nindivíduo é seu mérito, seu esforço, o qual não se prende a definições de classes \nsociais. A solução, então, seria proporcionar cada vez mais liberdade para que as \npessoas pudessem desempenhar suas potencialidades, seus esforços, alcançando, \nassim, uma ascensão social justa. Nesse cenário, segundo a perspectiva liberal, \no Estado não precisa intervir com políticas de distribuição de renda ou arrefecimento das diferenças sociais, sua única função é garantir a liberdade de cada \nindivíduo e o livre comércio.\nO modo de produção capitalista veio corroborar a visão liberal, dando subsídios \npara se acreditar que é apenas o mérito, a livre iniciativa e o esforço, o caminho \npara se alcançar uma boa situação econômica e social. Vários países da América \nLatina aderiram a essa perspectiva, principalmente, após o fim das ditaduras militares \nimplantadas durante a chamada Guerra Fria.\nComo indicamos no início, na outra ponta dessa discussão, temos uma pers pectiva tida como mais progressista. Seja de cunho plenamente socialista, seja \nem uma vertente menos radical, a noção de luta de classes é o oposto teórico da \nchamada meritocracia defendida pelo liberalismo clássico e o neoliberalismo.\nO chamado socialismo científico, teorizado por Karl Marx e Friedrich Engels, \naponta a luta de classes e a posse privada dos meios de produção como principais causas da desigualdade social e da pobreza. Nessa perspectiva socialista, os \nindivíduo,s que pertencem às classes dominadas, as quais não possuem os meios \nde produção e precisam vender sua força de trabalho, nunca conseguirão mudar \nsua condição social. Dessa forma, há uma luta de classes que se desenrola durante \ntoda a História humana, a qual determina também as condições de vida e todas \nas construções políticas, sociais e culturais.\n1\n5"
    },
    {
      "number": 36,
      "text": "Esses fundamentos teóricos estabelecem o chamado materialismo históri co-dialético, em outros termos, todas as condições de vida, as instituições so ciais, políticas e culturais, são determinadas pela organização da vida produtiva \nem vista das necessidades dos indivíduos. Nos dizeres do próprio Marx (1985, \np. 173): “Uma classe oprimida é a condição vital de toda sociedade baseada \nno antagonismo de classe. A emancipação da classe oprimida implica, assim, \nforçosamente, a criação de uma nova sociedade” .\nEles Não Usam Black Tie\nSinopse: longa-metragem que visa expor a realidade de um \ngrupo de trabalhadores de uma fábrica. Em meio às dificuldades da vida e da escassez de recursos, as pessoas lutam \ncontra uma condição social desfavorável. O longa-metragem \napresenta uma visão de luta de classes, a qual ilustra bem o \nque indicamos, aqui, como sendo o cerne da teoria socialista \nsobre este tema. A disputa entre aqueles que precisam vender sua força de trabalho e aqueles que possuem os meios de \nprodução. Como vimos até o momento sobre este tema, esta \né uma visão socialista. Além disso, o longa-metragem também \nmostra a questão da precariedade das moradias, assunto \nque também discutimos.\nINDICAÇÃO DE FILME\n1\n6"
    },
    {
      "number": 37,
      "text": "TEMA DE APRENDIZAGEM 2\nSob essa ótica teórica, a corrente socialista inspirada por Marx e Engels defende a \nrevolução da classe trabalhadora como única forma efetiva para se acabar com a \nhistórica luta de classes. T al revolução implicaria diretamente na extinção da propriedade privada e no completo controle do Estado, sob poder do proletariado, \naté a própria extinção do Estado em uma sociedade comunista real. Entretanto, \nvárias vertentes teóricas se apropriaram do pensamento marxista, criando uma \ngama enorme de interpretações. A principal experiência socialista na História \nfoi a Revolução Bolchevique de 1917 na Rússia.\nAlgumas das vertentes menos radicais instauraram uma teoria progressista \nque visava à luta pelos direitos dos trabalhadores, a ação do Estado para a diminuição das diferenças sociais e a constituição de uma justiça social que permita \naos indivíduos o acesso a trabalhos dignos. Essa perspectiva progressista ganha \nforça após a queda do chamado “bloco socialista” , o qual era representado, principalmente, pela União Soviética e a Alemanha Oriental.\nCom a queda desses dois governos no final das décadas de 1980 e 1990, as \ninterpretações progressistas, de influência socialista, começaram a ganhar ter reno. Esse fenômeno levou ao surgimento de partidos políticos e organizações \nsociais tidas como de centro-esquerda, as quais não defendiam a revolução \nproletária, mas defendiam políticas e ações em defesa da classe trabalhadora e \ndos menos favorecidos.\nComo você, estudante, pode inferir, são visões bem antagônicas: de um lado a \nperspectiva neoliberal de que se deve incentivar a iniciativa privada e a meri tocracia; do outro, a perspectiva socialista de que se deve haver uma revolução \nsocial, pondo fim à propriedade privada e, consequentemente, à luta de classes. \nCertamente, você é capaz de analisar todos os aspectos e constituir sua opinião \ncrítica e reflexiva sobre o tema. Além disso, pode também concluir que cada visão \nimplicará em uma abordagem distinta sobre o consumo e as relações sociais.\nPENSANDO JUNTOS\nQuando tratamos de consumo dentro da sociedade capitalista, estamos falando \nde uma ampla gama de relações econômicas, sociais e culturais. Não se trata \napenas de relações de compra e venda, mas também de organização produtiva, \nstatus social e criação de padrões. T odo esse amplo espectro socioeconômico \nque constitui a sociedade capitalista moderna direciona os indivíduos para rela1\n7"
    },
    {
      "number": 38,
      "text": "ções estabelecidas em diversos níveis. Podemos ser de classes sociais diversas e \nconvivermos em áreas comuns, tais como shoppings, academias, áreas de lazer \ne diversão, locais de trabalho, faculdades, colégios etc.\nT odavia, quando olhamos para a divisão social a partir do poder aquisitivo \nde cada classe, podemos perceber que há um tipo de separação em vista daquilo \nque é a realidade econômica de cada grupo. Sendo assim, há uma projeção de \nsonhos, expectativas e objetivos que podem ser compartilhados por indivíduos \nde diferentes classes sociais, mas que estão acessíveis a poucos indivíduos de \nalgumas classes sociais.\nEsses fatores, como posto, influenciam as relações de consumo e as relações \nsociais. Os indivíduos que pertencem a classes sociais de baixo poder aquisitivo, \nem geral, consomem os bens, produtos e serviços que estão acessíveis. Na maioria das vezes, são produtos de marcas mais baratas, majoritariamente itens de \nprimeira necessidade, ou seja, não são bens supérfluos. Deve-se ressaltar que tal \nconsumo não se restringe a bens e produtos, mas a serviços, viagens, educação, \nsaúde etc.\nO mercado financeiro se organiza em vista dos costumes e dos hábitos de consumo de cada camada da população. Um dos principais referenciais para essa \norganização é a classificação econômica dos grupos sociais. T al classificação se dá \npor meio da faixa de ganho real das famílias, variando de menos de um salário \nmínimo até 20 salários. Dessa forma, uma família pode ser classificada como \nsendo da classe A, B, C, D ou E.\nEsse fator é mais válido para se medir o poder aquisitivo dos indivíduos e \ngrupos sociais, todavia, não traduz de forma completa a realidade da população \nbrasileira. Quando se diz que um grupo social ficou “mais pobre” , não quer dizer \napenas que ele está com uma renda menor. O que realmente conta é o poder aquisitivo dos indivíduos, ou seja, se o que ele consegue comprar hoje com sua renda \né menos do que poderia comprar há dois anos atrás, então, ele ficou “mais pobre” .\nDessa maneira, quando pensamos em classes sociais e consumo, devemos ter \nem mente que não se trata apenas da relação “salário x consumo” , mas também \ndas condições sociais e políticas da sociedade como um todo. A convivência dos \nindivíduos em suas diversas relações sociais é marcada por uma desigualdade \nque, em muitos casos, passa despercebida. \n1\n8"
    },
    {
      "number": 39,
      "text": "TEMA DE APRENDIZAGEM 2\nQuando se olha por esse prisma, é possível perceber que viver e conviver em \nsociedade é um processo dinâmico, mutável e plural . Os sentimentos de per tencimento e inclusão são dependentes dessas relações, cada indivíduo se sente \ninserido em sua realidade social e pertencente a um grupo ou classe.\nEQUIDADE, JUSTIÇA E CONTROLE SOCIAL\nPara começarmos a abordagem dos assuntos desta seção, precisamos antes delinear brevemente o que se configura como justiça e equidade. A justiça recebe \numa conotação universal, normativa e deontológica, como nos instrui Rawls \n(1997, p. 7): “o conceito de justiça se define pela atuação de seus princípios na \natribuição de direitos e deveres e na definição da divisão apropriada de vantagens \nsociais. Uma concepção de justiça é uma interpretação dessa atuação” .\nDesde as Revoluções Burguesas dos séculos XVII e XVIII, a ideia de que \ndeve haver uma igualdade de direitos para todos os indivíduos tem sido o mote \nprincipal do chamado Estado Moderno de linhagem liberal clássica. “T odos são \niguais perante a lei” . Uma divisa que tem sido usada como fundamento de uma \nsociedade, na qual dos direitos e deveres não conhecem divisão de classe, religião, \netnia ou gênero. T odavia, é preciso compreender que tal concepção traz uma \n“universalização” da justiça enquanto algo que “iguala” os sujeitos. V ários autores, \ncríticos a essa construção, têm argumentado que há um encobrimento da real \ndesigualdade social, uma vez que tal noção de justiça não leva em consideração \nas diferenças econômicas e sociais.\nO liberalismo clássico, principalmente aquele de John Locke, Alexis de Tocqueville \ne Benjamin Constant, promulgava exatamente o caráter “igualitário” que a noção \nde direitos e justiça trazia. Entretanto, para esses autores, se há igualdade em \ndemasia não se tem liberdade, uma vez que cada indivíduo deve ser livre para desenvolver suas potencialidades. Vejamos a opinião de Constant ([201-?], p. 10): “A \nindependência individual é a primeira das necessidades modernas. Consequentemente, não se deve nunca pedir seu sacrifício para estabelecer a liberdade política”. Nesses termos, a liberdade individual é a garantia primeira de toda e qualquer \njustiça que possa haver de maneira institucionalizada no Estado.\n1\n9"
    },
    {
      "number": 40,
      "text": "Seu caráter de universalização é imprescindível para se pensar uma liberdade entre \nos sujeitos, todavia, sem limitações que possam advir de uma excessiva “igualdade” , \na qual poderia tolher a livre iniciativa dos sujeitos. No Estado Moderno, a justiça \nestá institucionalizada através dos dispositivos jurídico-políticos que compõem a \nprópria disposição desse Estado enquanto “ente” . O que significa isso?\nSignifica que o Estado, enquanto “ente jurídico-político” imparcial, deve garantir a todos os indivíduos o mesmo tratamento, os mesmos direitos e os mesmos deveres. Não pode agir de forma arbitrária com nenhum sujeito, por qualquer motivo que seja, independentemente da classe social ou poder aquisitivo.\nNo entanto, e a normatividade? A justiça é normativa, pois estabelece os \nmodos de ação aceitos dentro do convívio social, além disso, estabelece as diretrizes para as relações sociais e as disputas. Dentro do tecido social, as interações \nocorrem de maneira a relacionar indivíduos de diferentes classes e grupos sociais. \nÉ importante compreender que esse processo é normatizado exatamente pelas \nleis, pelos direitos, pelos deveres comuns a todos os indivíduos.\nÉ interessante perceber que tal normatividade é alicerçada em diretrizes sociais \nestabelecidas de maneira cultural, através de princípios e valores compartilhados. \nEm outros termos, a normatividade das leis é lastreada por uma compreensão \ncoletiva do que é correto, aceito e permitido. O indivíduo não precisa conhecer \ntodo o Código Civil Brasileiro para saber o que ele pode ou não fazer, o que é \ncrime ou não, de maneira geral.\nA justiça exerce seu caráter normativo, estabelecendo os direitos de cada \num e os deveres de todos, porém, como já indicado, desenvolve tal expediente a \npartir da compreensão de que “são todos iguais” . Novamente, é preciso pontuar \nque existem críticas a tal visão. Como estabelecer “igualdade jurídica” entre “desigualdade econômica e social”? Fazendo um contraponto à perspectiva de Rawls, \nautor citado anteriormente, temos a visão de Macintyre(2001):\n “\nRawls torna fundamental o que é, com efeito, um princípio da igualdade com relação às necessidades. Sua concepção do setor mais pobre \nda comunidade é uma concepção daqueles, cujas necessidades são as \nmais graves com relação à renda, riqueza e outros bens [...]. Para Rawls, \né irrelevante como foi que os que estão agora passando por necessidades graves chegaram a tal situação (MACINTYRE, 2001, p. 415).\n4\n1"
    },
    {
      "number": 41,
      "text": "TEMA DE APRENDIZAGEM 2\nOs pontos indicados, aqui, por Macintyre (2001), reverberam na crítica de vários autores.\nVOCÊ SABE RESPONDER?\nComo a tão aclamada “igualdade”, proporcionada pela justiça, pode, de fato, \ntornar justa a vida em sociedade?\nA normatividade da justiça seria então um “guarda-chuvas” para resguardar os \nprivilégios daqueles que pertencem às classes mais abastadas e melhor posicionadas socialmente. Essa discussão nos leva ao próximo delineamento necessário.\nE se tratando de equidade, o que se pode argumentar? Bem, a noção de \nequidade tem gravitado entre vários polos distintos. Para algumas vertentes, trata-se apenas do resultado prático da justiça; para outras, é um tipo de igualdade \nsocial que vai além do universalismo e da normatividade da justiça presente no \nEstado Moderno. Em termos gerais, pode-se asseverar que a noção de “equidade” se relaciona com a noção de “igualdade” , uma vez que esta última não está \ntotalmente realizada no âmbito da “justiça normativa” . Bem, tendemos clarificar \num pouco essa relação.\nComo já posto, a justiça pensada de maneira universal e normativa engloba \ntodos os indivíduos em um mesmo nível de igualdade. Entretanto, no tecido social, o que se vê é uma gritante desigualdade que permeia praticamente todos os \nníveis de interação social. Nesse sentido, a equidade é a disposição de se “corrigir” \naqueles pontos que se mostram insuficientes para garantir a real aplicação da \njustiça em termos sociais, jurídicos e políticos. T omemos a instrução de Cunha \n(2013, p. 19):\n “\nPor isso, a equidade impõe-se como uma exigência derivada da \nnecessidade de temperamento das consequências pessoais, familiares ou sociais desfavoráveis, surgidas pela inevitável generalidade \ne abstração das leis. Se tomarmos essa peculiar carência normativa \ncomo um erro, a tarefa do equitativo seria a de corrigi-lo. Porém, \n4\n1"
    },
    {
      "number": 42,
      "text": "como vimos, não se trata propriamente de uma falha na instituição \nda regra de Direito, mas de uma sua característica intrínseca. As \nregras jurídicas têm um modo de ser que não lhes permite alcançar, \nna sua abstração e generalidade, a riqueza das circunstâncias da \nsituação que pretendem regular.\nT orna-se bastante esclarecedora a opinião do autor, uma vez que já se indicou que \na justiça, enquanto universal e normativa, enxerga a todos como iguais, porém, \nno substrato social, o que ocorre é exatamente o oposto. Por esse viés, pode-se \ncompreender que a equidade é correlato necessário da justiça, visando a “equilibrar” um processo que não é em si mesmo perfeito ou isento de falhas.\nNo entanto, como pensar essa equidade em termos práticos na sociedade? \nComo podemos articular essa relação entre justiça e equidade com a questão das \nclasses sociais?\nPENSANDO JUNTOS\nBem, certamente se levantarão várias propostas, mas o cerne da questão é como \nmanter a liberdade de todos e os direitos de cada um. Em termos políticos, a \nequidade social, enquanto “justiça social equitativa”, visa a arrefecer as de sigualdades sociais, a partir de dispositivos legais, políticos e econômicos, que \npossam garantir melhores condições para os indivíduos em desvantagens.\n4\n1"
    },
    {
      "number": 43,
      "text": "TEMA DE APRENDIZAGEM 2\nEntre essas ações, podemos salientar as chamadas “políticas afirmativas” , programas, ações e projetos do poder público, que visam estabelecer uma igualdade e uma justiça social para grupos menos favorecidos ou marginalizados. \nPodemos citar as cotas raciais, os auxílios sociais que visam prover uma melhor distribuição de renda, bolsas de estudos e financiamento estudantil, entre \nvários outros. O viver e o conviver em sociedade não estão margeados apenas \npelos aspectos políticos e jurídicos, mas também por processos de empatia, \nreconhecimento e cuidado.\nA equidade deve ser entendida como uma condição necessária para se arrefecer \nos desdobramentos da “questão social”, inibindo, assim, o desarranjo social que \npoderia advir de uma desigualdade extrema. Para tentarmos ilustrar, de maneira \ninterpretativa, a diferença entre justiça e equidade, podemos pensar na seguinte \nsituação: imagine um grupo com cinco pessoas, o qual recebe um bolo para ser \ndividido entre essas pessoas. Se dividirmos o bolo em dez pedaços iguais e der mos dois para cada pessoa, estaremos sendo justos, dentro de uma visão normativa e universal de justiça igualitária.\nEntretanto, ao sabermos que, entre essas cinco pessoas, duas estão sem comer há \ndois dias e três tomaram café da manhã, almoçaram e jantaram, decidimos dar \ndois pedaços maiores para as pessoas que estão sem comer há dias. Dentro de \numa visão de equidade, estaríamos tentando adequar a situação à necessidade \ndiferenciada, ou mais urgente, daquelas pessoas.\nSe analisarmos dentro de uma perspectiva de classes sociais, fica claro que \nhá classes menos favorecidas, as quais apresentam necessidades mais urgentes \ne carências tão profundas que não podem ser sanadas pela simples justiça nor mativa ou universal. Por esse prisma, dentro de uma sociedade na qual há uma \nclara desigualdade social, a equidade se coloca como fator preponderante para \nse alcançar uma “justiça social” mais efetiva. Como consequência, o viver e o \nconviver entre os indivíduos poderá ser mais justo, seguro e proveitoso.\nEm complemento a essas disposições sociais estabelecidas pela justiça e pela \nequidade, pode-se, ainda, ressaltar a importância do controle social. De maneira \ngeral, como prerrogativa do Estado, o uso da força e da coerção só pode ser utilizada pelas forças legislativas, judiciais e policiais estabelecidas pelo poder público. \nEm outros termos, cabe ao Estado, a partir de suas instâncias e instituições, prover \n4\n1"
    },
    {
      "number": 44,
      "text": "a segurança, a liberdade e a efetivação das leis, a partir de um controle social que \npossa garantir a todos os indivíduos uma boa relação com o grupo.\nEntretanto, em vista da desigualdade social, esse processo de manutenção \nda ordem e da segurança é prejudicado. Quando se fala em controle social, para \nmuitas pessoas, o termo pode “soar” como “repressão” ou “limitação”. Todavia, a \nconotação que assumimos, aqui, é a de garantia de relações seguras e iguais para \ntodos os indivíduos a partir de dispositivos de ordenamento social. Por essa conotação, pode-se entender que a participação popular, da sociedade civil, também \ncontribui para o controle social. Sendo as instituições públicas legitimadas pela \nvontade popular, por consequência, as diretrizes tomadas por essas instituições \ndevem se coadunar aos objetivos da população.\nPor esse prisma, o controle social deve ser um processo mútuo, o qual é legitimado pela vontade e participação popular, a sociedade civil em suas diversas ex pressões, bem como exercida de maneira prática pelas forças públicas instituídas \nem todos os níveis de governo. Se o poder público, com a intenção de manter o \ncontrole social, fere a vontade popular ou sua legitimação, o que se instaura é um \nestado de violência institucional. Em outros termos, o poder público age por interesse \npróprio ou por interesse de determinado grupo social.\nCasos assim são vistos em sociedades extremamente desiguais, nas quais o poder público age em favor das classes dominantes, utilizando o controle social, \nde maneira truculenta, contra as classes menos favorecidas. V ê-se, também, em \ngovernos ditatoriais, nos quais as forças públicas são utilizadas para manter um \nregime de exceção e coerção.\n4\n4"
    },
    {
      "number": 45,
      "text": "TEMA DE APRENDIZAGEM 2\nO Brasil, infelizmente, sofre historicamente com essa discrepância entre controle social e legitimação social. Como pontua Florestan Fernandes (2008), a população negra no Brasil, desde o fim da escravidão, sofreu um controle truculento \npor parte do Estado, devido a um resquício cultural e ideológico advindo das \nclasses brancas dominantes. V ejamos um trecho de uma reportagem jornalística \nque trata dessa questão:\n “\nNo estado de São Paulo, as polícias mataram mais de uma pessoa \npor dia ao longo de 2022, totalizando 414 casos, segundo balanço \nda Secretaria de Segurança Pública. Dessas, 62,5% foram identificadas como pessoas negras. Em janeiro deste ano, foram 37 mortes \nclassificadas como “intervenção policial” (MELLO, 2023, on-line).\nComo consequência desse quadro social trágico, no qual uma determinada população sofre maior repressão das forças públicas, a conotação que se tem do \ncontrole social é exatamente aquele de repressão e injustiça. Quando olhamos o \ncenário a partir de um ponto de vista de classes, o resultado não é mais animador. Esses desvios, do que deve ser um controle social baseado na cidadania, na \nparticipação popular e na ação democrática das instituições públicas, precisam \nser abordados a partir das temáticas da justiça social, da equidade e igualdade.\nO controle social não precisa ser um processo de repressão que aprofunde \nmais ainda o enorme abismo de classes no Brasil. É necessário que a sociedade \ncivil e o poder público instituído caminhem juntos para a construção de uma \nsociedade aberta, participativa e que busque o equilíbrio para o conviver de todos \nos grupos sociais.\n4\n5"
    },
    {
      "number": 46,
      "text": "O termo “controle social” tomou conotações diversas no decorrer do século XX, \ndesde os apontamentos da chamada Teoria Crítica, de autores como Adorno \ne Horkheimer, que viam na sociedade moderna um processo de massificação \nda cultura e dos indivíduos, o termo ganhou um emprego crítico. Controle social passou a ser sinônimo de repressão, violência institucional e discriminação. \nTodavia, em uma perspectiva participativa, a partir de políticas populares de inclusão social, o termo passou a ter um sentido de ação coletiva da organização \ncivil e suas representações. Sendo assim, é possível encontrar artigos, livros \ne diversos outros materiais, principalmente dentro da discussão política, que \ntrarão essa dicotomia.\nAPROFUNDANDO\nHUMANIZAÇÃO, SUSTENTABILIDADE E INTEGRAÇÃO SOCIAL\nO viver e o conviver em sociedade, com todos os desafios, desigualdades e injustiças, só é possível a partir de um “compartilhamento”. Ao se relacionarem entre \nsi, os indivíduos estabelecem um compartilhamento complexo no tecido social. \nCompartilhamos espaços, ideias, concepções, objetivos, esperanças, crenças e \nvalores. Claro que as diferenças estão presentes, mas, em geral, a sociedade se \narticula dentro de uma “esfera de compartilhamentos” . Essas características são \npróprias de nossas relações humanas. Ao longo de milhares de anos de evolução, \naprendemos a nos relacionar e a depender uns dos outros. Mesmo com todas as \nimperfeições e desigualdades, conseguimos construir uma sociedade minima mente capaz de nos oferecer o que precisamos.\nAo longo do tempo, muito se questionou sobre o nível de envolvimento dos \nindivíduos nesse processo de compartilhamento. As relações sociais desiguais e \nas diversas disputas políticas e econômicas minaram os avanços éticos que a humanidade alcançou ao longo dos séculos. Em meio a essa aparente descrença, nas \núltimas décadas, os temas da ética, do cuidado à vida, do meio ambiente, bem como \ndas relações sociais compartilhadas no tecido social ganharam força e importância. \n4\n6"
    },
    {
      "number": 47,
      "text": "TEMA DE APRENDIZAGEM 2\n “\nNo contraponto, do meio do século XX para cá, começam a se desenhar respostas para a sociedade assim estabelecida. Direitos humanos, bioética, proteção ambiental, cidadania, mais que conceitos \nemergentes, são práticas que vão ganhando espaço no dia a dia das \npessoas, chamando-nos para o trabalho de construção de outra realidade (RIOS, 2009, p. 254).\nEsse processo de valorização e fortalecimento dos temas éticos e sociais tem constituído um movimento de “humanização” das relações sociais e das instituições. A \nrecompensa dessa humanização das relações sociais é a melhora da convivência \ne a busca de soluções para as profundas e graves desigualdades sociais. Como \nse pode perceber na opinião de Rios (2009), trata-se de uma visão mais ampla \nde sociedade, na qual se abarca também a preocupação com o meio ambiente, a \nbioética e conceitos basilares como cidadania e direitos humanos.\nLevanta-se um tema muito importante e a questão da sustentabilidade dentro \nde um projeto social humanizado, mais amplo e preocupado com as desigualdades sociais. Quando se fala em sustentabilidade, não se restringe a discussão a \ntemas relacionados ao clima, a proteção de florestas e povos originários. O planejamento sanitário dos grandes centros urbanos, a preservação de áreas verdes nas \ncidades, a preocupação com áreas de riscos nas periferias e o consumo consciente \nsão questões envolvidas na discussão sobre a sustentabilidade.\n4\n7"
    },
    {
      "number": 48,
      "text": "Pensando primeiro no consumo consciente, precisamos perceber que há duas \nperspectivas: uma que diz respeito ao que “se tira” do meio ambiente, outra que \nse refere ao que “despeja” nele.\nO consumo excessivo de água, energia, recursos naturais em geral, o esgotamento de áreas verdes pela degradação são problemas que se agravam com o \ncrescimento dos centros urbanos. Mais áreas são demandadas para produção de \nenergia, mais rios e riachos são comprometidos para o abastecimento, agravados por um consumo desordenado. O consumo consciente deve passar por uma \nmudança tanto dos indivíduos quanto do poder público, principalmente no modo \ncomo as cidades são geridas em suas demandas.\nA outra perspectiva está centrada, exatamente, naquilo que jogamos no meio ambiente, o produto descartado de um consumo desordenado. Quanto mais se consome, mais lixo e degradação se cria. Ao olharmos esse problema do ponto de vista \nsocial de classes, podemos perceber que as classes mais abastadas acabam por demandar mais recursos, em forma de energia, bem como por produzir mais descarte. \nT odavia, quem mais sofre com os resultados de um meio ambiente degradado são \nos moradores de áreas periféricas e de risco nos grandes centros urbanos.\nPor esse prisma, gerir um uso consciente dos recursos naturais, bem como o \ndescarte do lixo produzido, perpassa, também, a preocupação com a justiça social \ne a humanização nas relações. Se avaliarmos fatores como coleta de lixo, infraestrutura de saneamento, fornecimento de água, produção de lixo per capita, consumo de energia elétrica, veremos que os bairros concentrados em áreas nobres \nestão mais bem estruturados e demandam mais recursos. Como sustenta Coelho \n(2001), para se compreender, comparativamente, as estruturas sanitárias e de \nabastecimentos dos centros urbanos, é preciso uma abordagem social e histórica.\nEssa discussão é importante para entendermos como as temáticas da justiça \nsocial, da equidade, da sustentabilidade e da humanização nas instituições se coadunam em uma perspectiva mais complexa e intrincada. A organização espacial das \ncidades é influenciada pela forma como as classes sociais e os grupos se organizam \nem vista de seu poder aquisitivo. A partir daí, a desigualdade social pode se agravar, \numa vez que as classes mais abastadas contam com melhor estrutura e suporte. \nT al quadro leva à necessidade de ações públicas e privadas que visem eliminar ou \n4\n8"
    },
    {
      "number": 49,
      "text": "TEMA DE APRENDIZAGEM 2\npelo menos, arrefecer, as consequências de tais desigualdades por meio da busca \nde uma equidade. Uma vez estabelecida essa perspectiva, as instituições se tornam \nmais humanizadas, dando ênfase no cuidado às pessoas, às relações éticas e à vida.\nCertamente, os desdobramentos dessas afirmações poderiam ser ampliados \npara diversas outras abordagens. Dentro do escopo a que nos propomos neste \ntema de aprendizagem, compreendemos que se trata de uma discussão válida \ne extremamente importante para a integração social. Parece-nos necessário salientar que essa integração social é possível dentro dos parâmetros já discutidos \naqui, ou seja, a partir de consensos sociais, políticos, econômicos e jurídicos. Ao \nse estabelecer que é necessário combater a desigualdade, a injustiça, os problemas \nambientais e sanitários, a falta de oportunidade para as classes menos favorecidas, \ntendo, como esteio, os arranjos político-jurídicos do Estado de direito, promulga-se, também a necessidade de ações coletivas.\nA integração social trata exatamente desse arranjo possível, no qual as ações \ncoletivas, fomentadas pela sociedade civil e o poder público, se direcionam para \nos problemas sociais que afetam a sociedade. O primeiro movimento, para tal \nrealidade, é exatamente reconhecer os problemas e propor soluções viáveis, integradoras, inclusivas e exequíveis. Dentro da perspectiva de controle social que \nabordamos anteriormente, é no conjunto de ações da sociedade civil e do poder \npúblico que os avanços se concretizam, se não houver consonância entre essas \nduas esferas, não haverá integração social.\nNOVOS DESAFIOS\nEstudante, como indivíduo inserido em uma sociedade, com planos, projetos e \nexpectativas, certamente você já se deparou com diversas escolhas a serem feitas. \nNo mercado de trabalho, as suas escolhas são decisivas para determinarem a \nrealização de tais projetos, planos e expectativas. Assim, chegamos ao momento \nno qual buscamos vislumbrar como a teoria estudada pode nos ajudar na prática \ne na tomada de decisões assertivas.\nIndependentemente de sua profissão, as questões sociais permearão as ações e \nas decisões que deverá tomar, tendo como suporte o conhecimento que adquiriu \ncom sua vivência e com seus estudos. Neste tema de aprendizagem, pudemos \ndiscutir aspectos importantes da organização social. \n4\n9"
    },
    {
      "number": 50,
      "text": "Em sua opinião, tal discussão foi pertinente para sua realidade profissional, já \nvivenciada ou almejada? Buscando ser o profissional que você deseja, os assuntos \nque tratamos, aqui, serão importantes para sua formação? Embora sejam questões \nque parecem triviais, elas suscitam a necessidade de uma reflexão crítica.\nRetomemos a situação apontada no início de nossa jornada, uma realidade \ncotidiana em um grande centro urbano, a qual demonstra os aspectos de desigualdade e injustiça social que discutimos aqui. Será que é possível uma integração social entre realidades tão distintas quanto aquelas vivenciadas pelos dois \nbairros vizinhos em São Paulo, Paraisópolis e Morumbi? A busca de uma justiça \nsocial, com igualdade e equidade, pode se realizar em uma sociedade sem empatia \ne humanização? Como podemos, por meio de nossas profissões, contribuir para \na tão necessária integração social e a superação das desigualdades?\nNo seu cotidiano profissional, certamente, você irá se deparar com situações \nnas quais sua contribuição fará toda a diferença para o seu convívio social, o meio \nambiente, as relações sociais. Se, como engenheiro ambiental, preparando planos \nde manejo de recursos naturais; como assistente social, direcionando pessoas \npara um atendimento adequado de suas carências; como agente de segurança \npública, garantindo a segurança e a liberdade dos indivíduos sem discriminação; \ncomo um enfermeiro, tratando de forma humanizada seus pacientes e colegas \nde trabalho.\nDe maneira geral, sua atuação profissional estará inserida em uma cadeia de \nações que implicará em todo um arranjo social. Poderá ser uma atuação empática, humanizada, ética e imparcial, ou poderá ser apenas um conjunto de ações \ntécnicas e distantes da realidade social. Como apontado no início, são as escolhas \nque você fará, que determinarão os objetivos a serem alcançados em sua jornada \nprofissional e em sua realidade social.\nAborde essa discussão com seus colegas, troque ideias, busque outras contribuições teóricas e práticas a partir do que discorremos aqui. Certamente, você terá \nsucesso em alcançar seus objetivos!\n5\n1"
    },
    {
      "number": 51,
      "text": "VAMOS PRATICAR\n1. Em uma sociedade cada vez mais dinâmica, com interações sociais que estabelecem uma demanda cada vez maior de participação de todos os setores sociais, vê-se \ncrescer a preocupação com o bem-estar, compreendendo que tal preocupação não \né função exclusiva do poder público. Como instrui Cesar (2008, p. 158): “Na esteira \ndessa mobilização, várias entidades empresariais passaram a mobilizar, sensibilizar e \najudar as corporações a gerirem seus negócios, de modo sustentável e ‘politicamente \ncorreto’. Com isso, as empresas intensificam suas críticas à ineficiência do Estado na \nadministração da crise econômico-social, mas, ao mesmo tempo, reconhecem a sua \nincapacidade de responder sozinhas aos graves problemas sociais que assolam o país”.\nFonte: CESAR, M. de J. Empresa-cidadã: uma estratégia de hegemonia. São Paulo: \nCortez, 2008. p. 158.\nA participação do setor produtivo na discussão sobre o bem-estar social e a sustentabilidade não se apresenta apenas como imposição por lei, é uma forma de interação, \ncontribuição e retribuição para com a comunidade e o meio social. A partir dessas colocações, tendo em vista a citação feita, assinale, a seguir, qual seja a alternativa que melhor \nexpressa o que deve ser a interação do setor produtivo, em vista de sua inserção social:\na) O setor produtivo tem, como função social, prover geração de renda e emprego; dessa \nforma, sua inserção social está no campo econômico.\nb) Dentro do arranjo social moderno, todos os setores compartilham uma preocupação \ncom o bem-estar; o setor produtivo se especializa na questão da sustentabilidade.\nc) O setor produtivo, inserido de forma ativa na sociedade, contribui para o bem-estar \natravés da sustentabilidade, da humanização de suas atividades e da integração com \na comunidade.\nd) O setor produtivo se insere na sociedade e contribui para o bem-estar, ao produ zir bens acessíveis, mais baratos, para a população carente, pensando no consumo \nconsciente.\ne) A inserção social das empresas, através da sustentabilidade, é uma questão que tem \nchamado a atenção dos executivos e dos políticos, por representar grande potencial \nde lucro rápido na área de preservação ambiental.\n5\n1"
    },
    {
      "number": 52,
      "text": "VAMOS PRATICAR\n2. Dentro da construção social e política de uma determinada sociedade, é possível perceber dois níveis de criação de consenso e ordem: um nível mais subjetivo e outro \nmais objetivo. As leis são parte importante desse processo, principalmente em vista \nda garantia de liberdade e justiça. A partir dessa relação entre as leis e os consensos \nque as fundamentam, assinale a alternativa correta:\na) As leis refletem consensos históricos e sociais de determinada sociedade, objetivados \nnas instituições públicas e seus ordenamentos.\nb) As leis são dispositivos puramente simbólicos, sem qualquer caráter objetivo, pois \nrefletem um consenso teórico sobre o que é justo.\nc) O dispositivo das leis encontra sua objetividade na normatividade e nas punições, \nsendo essas funções subjetivas do Estado.\nd) As leis são válidas como dispositivos coercitivos apenas por sua base objetiva, punitiva, não tendo aspectos teóricos.\ne) Os consensos sociais que constituem as leis são objetivados apenas no Estado, não \nsendo existentes como fundamento popular.\n3. “O agente dessa nova vida econômica será a cidade que desperta, se desenvolve e se \ntransforma no elemento ativo da região. Lugar de proteção contra a insegurança, passa \nlogo a constituir um centro de comércio. Nessas cidades, os homens se agrupam e se \ndefendem, a um tempo, contra os perigos do banditismo e os excessos dos senhores. \nGraças ao trabalho, as cidades se enriquecem e podem adquirir suas franquias”.\nFonte: HUGON, P. História das doutrinas econômicas. 7. ed. São Paulo: Atlas, 1962. p. 85.\nAs grandes cidades atuais se tornam centros de desenvolvimento, mas também de extrema desigualdade, violência e injustiça. Todavia, sua centralidade no desenrolar da História \nhumana ainda é percebida. Analisando a citação feita, assinale a alternativa que melhor \ndefine a relação entre economia e desenvolvimento urbano:\na) É possível perceber que a economia é a responsável pela degradação das cidades, \ncausando insegurança e valorizando o comércio.\nb) As cidades foram e são importantes para o desenvolvimento econômico, possibilitando uma formação social maior e a produção de riquezas.\nc) Devido à violência existente apenas nas cidades, a economia se centrou no comércio, \ndeixando de lado a busca pela igualdade social.\nd) No desenrolar da História, as cidades sempre foram constituídas primeiro por conta \ndo comércio, depois foram sendo estabelecidas as relações sociais.\ne) Como indica a citação feita, o que levou à criação das cidades foi o banditismo, o qual \natrapalhava o comércio, assim como a violência hoje nos grandes centros.\n5\n1"
    },
    {
      "number": 53,
      "text": "REFERÊNCIAS\nCOELHO, M.C.N. Impactos ambientais em áreas urbanas: teorias, conceitos e métodos de \npesquisa. In: GUERRA, A. J. T.; CUNHA, S. B. (org.). Impactos ambientais urbanos no Brasil. Rio de Janeiro: Bertrand Brasil, 2001.\nCONSTANT, B. Da liberdade dos antigos comparada à dos modernos. Tradução de Loura Silveira. Belo Horizonte: UFMG – Universidade Federal de Minas Gerais, [201-?]. Disponível em: https:/ /www.fafich.ufmg.br/~luarnaut/Constant_liberdade.pdf. Acesso em: 31 ago. \n2023.\nCUNHA, R. A. V. Justiça e equidade. Revista de Informação Legislativa, Brasília, v. 50, \nn. 198, abr./jun. 2013. Disponível em: https:/ /www12.senado.leg.br/ril/edicoes/50/198/ril_\nv50_n198_p7.pdf. Acesso em: 31 ago. 2023.\nFERNANDES, F. A integração do negro na sociedade de classes. 5. ed. São Paulo: Globo, \n2008.\nMACINTYRE, A. Depois da virtude. São Paulo: Edusc, 2001.\nMARX, K. A miséria da filosofia. Tradução de José Paulo Neto. São Paulo: Global, 1985.\nMELLO, D. Violência policial é expressão do racismo em diversas partes do mundo. Agência \nBrasil, São Paulo, 21 mar. 2023. Disponível em: https:/ /agenciabrasil.ebc.com.br/geral/noticia/2023-03/violencia-policial-e-expressao-do-racismo-em-diversas-partes-do-mundo. \nAcesso em: 31 ago. 2023.\nRAWLS, J. Uma teoria da justiça. Tradução Almiro Pisetta e Lenita M. R. Esteves. São Paulo: \nMartins Fontes, 1997.\nRIOS, I. C. Humanização: a essência da ação técnica e ética nas práticas de saúde. Revista \nBrasileira de Educação Médica, Brasília, v. 33, n. 2, p. 253–261, 2009.\nVIANA, A. L. A.; SILVA, H. P. da. Meritocracia neoliberal e capitalismo financeiro: implicações \npara a proteção social e a saúde. Ciência & Saúde Coletiva, Rio de Janeiro, v. 23, n. 7, 2018.\nWAYNE, C.; CABRAL, V. N. de. Capitalismo, classe e meritocracia: um estudo transnacional \nentre o Reino Unido e o Brasil. Educação & Realidade, Porto Alegre, v. 46, n. 3, p. e117535, \n2021.\n5\n1"
    },
    {
      "number": 54,
      "text": "1. Opção C. O setor produtivo tem como função social prover geração de renda e emprego, \ndessa forma, sua inserção social está no campo econômico. A alternativa está incorreta, \npois a função social das empresas está ligada ao campo econômico, mas sua atuação \nnão se restringe a ele, em uma visão de integração social.\nDentro do arranjo social moderno, todos os setores compartilham uma preocupação com \no bem-estar, o setor produtivo se especializa na questão da sustentabilidade. A alternativa \nestá incorreta, pois o setor produtivo não se especializa na sustentabilidade, uma vez que \na sustentabilidade engloba uma série de ações e setores da sociedade. O setor produtivo \ncontribui ao gerir o uso de recursos e fomentar um consumo consciente e um descarte \ncorreto dos materiais.\nO setor produtivo, inserido de forma ativa na sociedade, contribui para o bem-estar \natravés da sustentabilidade, da humanização de suas atividades e da integração com \na comunidade. A alternativa está correta, pois a inserção do setor produtivo se dá em \nvárias frentes, na questão da sustentabilidade, na humanização e valorização da ética \nnas atividades produtivas, bem como na integração social ativa, participando ativamente \nda vida da comunidade.\nO setor produtivo se insere na sociedade e contribui para o bem-estar ao produzir bens \nacessíveis, mais baratos, para a população carente, pensando no consumo consciente. \nA alternativa está incorreta, pois o consumo consciente não está atrelado apenas ao \nconsumo de itens e produtos de baixo custo.\nA inserção social das empresas, através da sustentabilidade, é uma questão que tem \nchamado a atenção dos executivos e dos políticos, por representar grande potencial \nde lucro rápido na área de preservação ambiental. A alternativa está INCORRETA, pois a \ninserção social das empresas e do setor produtivo como um todo, tendo de uma visão de \nintegração social, não deve visar ao lucro ou ganho político.\n2. Opção A. As leis refletem consensos históricos e sociais de determinada sociedade, objetivados nas instituições públicas e seus ordenamentos. A alternativa está correta, pois \napresenta as leis como resultado de um consenso histórico, que envolve não apenas aspectos jurídicos, mas também valores, costumes e princípios compartilhados socialmente.\nAs leis são dispositivos puramente simbólicos, sem qualquer caráter objetivo, pois refletem \num consenso teórico sobre o que é justo. A alternativa está incorreta, pois indica que as \nleis são puramente simbólicas, entretanto, elas são objetivadas através das instituições \npúblicas, dos direitos e deveres.\nO dispositivo das leis encontra sua objetividade na normatividade e nas punições, sendo \nessas funções subjetivas do Estado. A alternativa está incorreta, pois as funções das leis \nnão são apenas punitivas, mas também instrutivas, além disso, a punição não é a mera \nfunção subjetiva do Estado.\nGABARITO\n5\n4"
    },
    {
      "number": 55,
      "text": "As leis são válidas como dispositivos coercitivos apenas por sua base objetiva, punitiva, não \ntendo aspectos teóricos. A alternativa está incorreta, pois as leis possuem fundamentos \nteóricos, além de fundamentos sociais, consuetudinários e valorativos.\n3. Opção B. É possível perceber que a economia é a responsável pela degradação das cidades, causando insegurança e valorizando o comércio. A alternativa está incorreta, pois \na economia não é a responsável pela degradação das cidades, ao contrário, segundo a \ncitação, ela alavancou o seu desenvolvimento.\nAs cidades foram e são importantes para o desenvolvimento econômico, possibilitando \numa formação social maior e a produção de riquezas. A alternativa está correta, pois o \nsurgimento das cidades permitiu o avanço do comércio e uma melhor sociabilidade dos \nindivíduos.\nDevido à violência existente apenas nas cidades, a economia se centrou no comércio, \ndeixando de lado a busca pela igualdade social. A alternativa está incorreta, pois a violência \nnão existe apenas nas cidades, além disso, a economia é a esfera produtiva da sociedade.\nNo desenrolar da História, as cidades sempre foram constituídas primeiro por conta do \ncomércio, depois foram sendo estabelecidas as relações sociais. A alternativa está incorreta, pois como se pode extrair da citação contida na questão, primeiro há a formação da \ncidade, o que favorece o comércio e o enriquecimento.\nComo indica a citação feita, o que levou à criação das cidades foi o banditismo, o qual \natrapalhava o comércio, assim como a violência hoje nos grandes centros. A alternativa \nestá INCORRETA, pois a formação das cidades vem primeiro, o que posteriormente garante \na defesa contra o banditismo, além disso, o comércio não é afetado diretamente por ele.\nGABARITO\n5\n5"
    },
    {
      "number": 56,
      "text": "MINHAS ANOTAÇÕES\n5\n6"
    }
  ]
};
