// Material de Estudo Auto-Gerado para a disciplina: Estudo Contemporâneo e Transversal_ Indústria, Transformação Digital e Inovação
window.FisioMaterials = window.FisioMaterials || {};
window.FisioMaterials["s4_estudo_contemp"] = {
  "title": "Estudo Contemporâneo e Transversal_ Indústria, Transformação Digital e Inovação",
  "toc": [
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 6
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 8
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 10
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 12
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 14
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 16
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 18
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 20
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 22
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 24
    },
    {
      "title": "TEMA DE APRENDIZAGEM 1",
      "page": 26
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 32
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 34
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 36
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 38
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 40
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 42
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 44
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 46
    },
    {
      "title": "TEMA DE APRENDIZAGEM 2",
      "page": 48
    }
  ],
  "pages": [
    {
      "number": 1,
      "text": "CECÍLIA LOPEZ SANTOS\nMARIA FERNANDA FRANCELIN CARVALHO\nESTUDO \nCONTEMPORÂNEO \nE TRANSVERSAL: \nINDÚSTRIA, \nTRANSFORMAÇÃO \nDIGITAL E \nINOVAÇÃO"
    },
    {
      "number": 2,
      "text": "Núcleo de Educação a Distância. SANTOS, Cecília Lopez; CARVALHO, \nMaria Fernanda Francelin.\nEstudo contemporâneo e transversal: indústria, transformação \ndigital e inovação / Cecília Lopez Santos, Maria Fernanda Francelin \nCarvalho. - Florianópolis, SC: Arqué, 2024.\n52 p.\n1. Indústria 2. Digital 3. Transformação 4. EaD. I. Título.\nCoordenador(a) de Conteúdo \nVania Konell\nProjeto Gráfico e Capa\nArthur Cantareli Silva\nEditoração\nCaroline Casarotto Andujar\nDesign Educacional\nFabiana Bruna Gozer Dias \nPatrícia Ramos Peteck\nRevisão Textual\nAriane Andrade Fabreti\nElaine Machado\nIlustração\nCarolina Guimarães Branco\nEduardo Aparecido Alves\nFotos\nShutterstock e Envato\nImpresso por: \nBibliotecária: Leila Regina do Nascimento - CRB- 9/1722.\nFicha catalográfica elaborada de acordo com os dados fornecidos pelo(a) autor(a).\nEXPEDIENTE\nFICHA CATALOGRÁFICA\nN964\nISBN: 978-65-279-1327-6"
    },
    {
      "number": 3,
      "text": ""
    },
    {
      "number": 4,
      "text": "RECURSOS DE IMERSÃO\nUtilizado para temas, assuntos ou conceitos avançados, levando ao aprofundamento do que está sendo trabalhado \nnaquele momento do texto. \nAPROFUNDANDO\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você \nterá indicações de filmes \nque se conectam com o \ntema do conteúdo.\nINDICAÇÃO DE FILME\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você terá \nindicações de livros que \nagregarão muito na sua \nvida profissional.\nINDICAÇÃO DE LIVRO\nUtilizado para desmistificar pontos \nque possam gerar confusão sobre o \ntema. Após o texto trazer a explicação, \nessa interlocução pode trazer pontos \nadicionais que contribuam para que \no estudante não fique com dúvidas \nsobre o tema. \nZOOM NO CONHECIMENTO\nEste item corresponde a uma proposta \nde reflexão que pode ser apresentada por \nmeio de uma frase, um trecho breve ou \numa pergunta. \nPENSANDO JUNTOS\nUtilizado para aprofundar o \nconhecimento em conteúdos \nrelevantes utilizando uma linguagem audiovisual.\nEM FOCO\nUtilizado para agregar um conteúdo \nexterno.\nEU INDICO\nProfessores especialistas e convidados, ampliando as discussões sobre os temas por meio de \nfantásticos podcasts.\nPLAY NO CONHECIMENTO\nPRODUTOS AUDIOVISUAIS\nOs elementos abaixo possuem recursos \naudiovisuais. Recursos de mídia disponíveis no conteúdo digital do ambiente \nvirtual de aprendizagem.\n4"
    },
    {
      "number": 5,
      "text": "6INOVAÇÃO E PENSAMENTO CRIATIVO 6\nO QUE É CRIATIVIDADE? . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8\nA MENTALIDADE DO CRIATIVO. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11\nPROCESSO CRIATIVO . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14\nMITOS SOBRE CRIATIVIDADE. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16\nDESENVOLVENDO IDEIAS INOVADORAS . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22\n32INDÚSTRIA E TRANSFORMAÇÃO DIGITAL 32\n5\nSUMÁRIO"
    },
    {
      "number": 6,
      "text": "MINHAS METAS\nINOVAÇÃO E PENSAMENTO \nCRIATIVO\nConhecer os principais conceitos de criatividade.\nDiferenciar imaginação, criatividade e inovação.\nConhecer as etapas do processo criativo.\nConhecer os principais mitos sobre criatividade.\nIdentificar momentos de bloqueio e como superá-los.\nConhecer práticas para uma rotina mais criativa.\nRelacionar criatividade e inovação.\nTEMA DE APRENDIZAGEM 1\n6"
    },
    {
      "number": 7,
      "text": "INICIE SUA JORNADA\nCom o rápido avanço da tecnologia no século XXI, o mundo está em constante \ntransformação, especialmente devido à automação de processos e à Inteligência Artificial. Como consequência, novos problemas surgiram, para os quais habilidades \npuramente técnicas já não são suficientes para solucionar. É necessário ser criativo, \nno entanto, é comum que pessoas adultas se achem pouco ou nada criativas, o que \npode significar um bloqueio em seu desenvolvimento pessoal e profissional. \nEste podcast é uma introdução à temática e mostra alguns dos principais bloqueios para uma vida criativa. Ele também leva à reflexão do que você pode fazer \npara superá-los e resgatar a sua criatividade. Recursos de mídia disponíveis no \nconteúdo digital do ambiente virtual de aprendizagem \nPLAY NO CONHECIMENTO\nA prática da criatividade de maneira intencional no dia a dia é essencial para \nnossa evolução, especialmente nos dias de hoje. Inserir a criatividade na rotina \nnos ajuda a tomar melhores decisões, ter ideias inovadoras e conquistar melhores \nresultados, tanto na vida pessoal como na profissional, independentemente da \nsua área de atuação.\nDiante do exposto, entender o conceito da criatividade e desmistificá-la, torna-se muito importante e enriquecedor, contudo já parou para pensar como \nsomos quase a vida inteira desestimulados criativamente? É possível desbloquear \nessa criatividade? Quais estratégias e ferramentas podemos utilizar para esse \ndesbloqueio? V amos, juntos, descobrir?\nVAMOS RECORDAR?\nAntes de nos aprofundarmos no assunto, primeiro, recordaremos, de maneira \ndidática e bem-humorada, o que é criatividade e entender o seu poder e importância \ntanto no mundo corporativo quanto fora dele, com base em Murilo Gun, especialista \ne professor de criatividade. https:/ /www.youtube.com/watch?v=KfSFRiB0MfE.\nUNIASSEL VI\n7"
    },
    {
      "number": 8,
      "text": "TEMA DE APRENDIZAGEM 1\nDESENVOLVA SEU POTENCIAL\nO QUE É CRIATIVIDADE? \nSegundo o dicionário Aurélio (FERREIRA, 2004, p. 557), criatividade significa: \n“1. Capacidade de criar, de inventar. 2. Qualidade de quem tem ideias originais, \nde quem é criativo” .\nPara o educador Ken Robinson (COMO..., 2006, on-line), criatividade é \no processo de ter ideias originais que possuem valor, já para Teresa Amabile \n(2012), diretora de pesquisa da Harvard Business School, é a capacidade de criar \numa resposta nova e apropriada para alcançar um objetivo. A escritora Elizabeth Gilbert (2015, p. 11) diz que “é o relacionamento entre um ser humano \ne os mistérios da inspiração” . De acordo com o professor Murilo Gun (AULA \n2.3, 2022, on-line), é combinar o que já existe para criar algo novo, semelhante à \ndefinição de Ferguson (EMBRACE..., 2012, on-line), que define a criatividade \ncomo a capacidade humana de copiar, transformar e combinar ideias, enquanto \npara Corita Kent (2008 apud KENT; STEW ARD, 2023), é a relação que construímos para formar um novo todo.\nDe maneira geral, a criatividade pode ser definida \ncomo a imaginação seguida de ação para a resolução \nde problemas. A capacidade de imaginar é o que distingue seres humanos de outros animais, logo, se você é \ncapaz de imaginar, é capaz de ser criativo. A criatividade é uma habilidade que, como qualquer outra, exige \nprática consistente ao seu desenvolvimento. \nSe você é capaz de \nimaginar, é capaz de \nser criativo\nEntão, se a criatividade é uma habilidade, qualquer pessoa é capaz de se de senvolver criativamente?\nPENSANDO JUNTOS\n8"
    },
    {
      "number": 9,
      "text": "A criatividade é uma das funções cognitivas definidas como um conjunto de \nhabilidades que todo indivíduo possui para adquirir, processar e transformar \ninformações, bem como ajudar na tomada de decisões (BALDISSERA, 2023, \non-line). Logo, todo indivíduo possui potencial criativo. Segundo Kelley e Kelley \n(2019, p. 12): “Como um músculo suas aptidões criativas crescerão e se fortalecerão com a prática; exercitá-las as manterá em forma” .\nDiante do avanço tecnológico que o mundo vive atualmente, o mercado de \ntrabalho tem valorizado cada vez mais profissionais criativos por, geralmente, \nserem aqueles que buscam soluções inovadoras e otimizações de processos, o \nque torna a criatividade uma habilidade essencial e competitivamente vantajosa \npara profissionais em qualquer área de atuação.\nUNIASSEL VI\n9"
    },
    {
      "number": 10,
      "text": "TEMA DE APRENDIZAGEM 1\nFigura 1 – Gráfico de habilidades citadas por vários CEO como essenciais\nFonte: adaptado de IBM (2010). \nDescrição da Imagem: a figura apresenta um gráfico cujos resultados mostram que, para os CEO, a criatividade \nestá à frente de habilidades como pensamento global, influência e imparcialidade. O gráfico contém barras nas \ncores rosa e roxo, posicionadas entre os dados de pesquisa e seus resultados. A criatividade aparece como habilidade mais citada (60%), à frente de integridade (52%), pensamento global (35%), influência (30%), abertura (28%), \ndedicação (26%), foco em sustentabilidade (26%), humildade (12%) e imparcialidade (12%). Fim da descrição.\nCriatividade\nIntegridade\nPensamento global\nInﬂuência\nAbertura\nDedicação\nFoco em sustentabilidade\nHumildade\nImparcialidade\n60%\n52%\n35%\n30%\n28%\n26%\n26%\n12%\n12%\nUma pesquisa desenvolvida pela IBM (2010) constatou o seguinte: os CEOs \nacreditam que a criatividade é a competência de liderança mais importante para \nempresas diante da complexidade do mercado atual. De acordo com o levantamento, eles acreditam que líderes criativos praticam e estimulam nas suas equipes \na experimentação e inovação.\nNo Brasil, entre os anos de 2017 e 2020, houve o aumento de 11,7% dos profissionais criativos no mercado formal, e a média de salário, em 2020, chegou \na R$ 6.920,00 — aproximadamente 2,5 vezes maior do que a média salarial no \npaís — de acordo com o Mapeamento da Indústria Criativa no Brasil, realizado \npela Firjan (2022). \n1\n1"
    },
    {
      "number": 11,
      "text": "Fica claro, portanto, que se desenvolver criativamente significa estar preparado \npara a competitividade do mercado de trabalho e para o futuro.\nA MENTALIDADE DO CRIATIVO\nAgora que você já sabe que a criatividade é uma habilidade capaz de ser desenvolvida, é preciso \nentender o que fazer para alcançá-la. T udo \ncomeça com a mentalidade certa, a qual é \ndiferente da que \nse costuma ter \ndiante de \ntantos mitos \ne bloqueios \nadquiridos \ncom o passar \ndo tempo e dos \nquais falare mos, com deta lhes, mais adiante. \nDiante disso, fica claro: é essencial \nassumir uma nova mentalidade para desenvolver o potencial criativo. Algumas ca racterísticas e práticas são comumente observadas \nem pessoas criativas, tais como: \nNo artigo completo da Firjan, você consegue ter acesso a esses e outros dados \ndetalhados sobre a indústria criativa no Brasil. https:/ /appsext.firjan.com.br/economiacriativa/downloads/MapeamentoIndustriaCriativa2022.pdf.\nEU INDICO\nUNIASSEL VI\n1\n1"
    },
    {
      "number": 12,
      "text": "TEMA DE APRENDIZAGEM 1\nCURIOSIDADE\nEla é fundamental para uma vida mais criativa, pois nos faz ter o desejo de conhecer o \nmundo e como as coisas funcionam, bem como ir em busca de novas experiências e \nconhecimentos, além de nos fazer levantar questionamentos que sempre nos levam a \numa nova descoberta.\nMENTE ABERTA\nÉ fundamental ter a mente aberta ao novo, ao diferente, estar aberto a todo tipo de \ninspiração. Uma mente fechada vive apenas de memória e dificilmente conseguirá ter \nalguma ideia criativa.\nAUTOESTIMA\nPara criar a solução de um problema, é preciso começar acreditando que consegue \ncriá-la. \nCORAGEM\nCriatividade requer quebra de padrões, ir além das convenções e do conforto do que \njá é conhecido, não ter medo de críticas e pensar o que se pode fazer de diferente do \nque os demais estão fazendo. Em uma sociedade onde se valoriza o padrão, deve-se \nter coragem para ir em busca do diferente.\nDETERMINAÇÃO\nNem sempre você se sentirá motivado a criar, mas é a determinação que lhe impedirá \nde desistir da sua empreitada criativa. \n1\n1"
    },
    {
      "number": 13,
      "text": "Algumas características, como a autoestima, são mais difíceis de desenvolver. É \num processo que pode ser demorado, mas é essencial para seu desenvolvimento \ncriativo e pessoal. \nUm exercício simples possível de lhe ajudar na busca pela autoestima é listar \nsuas conquistas. Esse exercício é complicado no início, pois não temos o hábito de \ncomemorar conquistas que não podem ser mensuradas, entretanto, qualquer coisa \nque você se propôs a fazer e fez pode ser considerada uma conquista. Por exemplo, \ncomeçar a praticar algum exercício, alimentar-se melhor, enviar um currículo etc. \nESPERANÇA\nÉ preciso acreditar que algo ainda não existente pode passar a existir. \nNÃO SE COMPARAR\nPessoas diferentes possuem contextos de vida diferentes. Comparar-se com os outros, além de injusto, trava a criatividade e a faz distanciar-se ainda mais.\nPERMISSÃO PARA FRACASSAR\nA melhora na criação de novas ideias está diretamente relacionada à liberdade que \nvocê dá a si mesmo e à sua equipe para cometer erros eventualmente.\nPensando nisso, você consegue listar todas as conquistas que teve no período dos \núltimos 30 dias? Reflita um pouco, não precisa ter pressa. Depois de anotar todas \nas conquistas que lembrar, leia e perceba quanta coisa realizou. Orgulhe-se!\nPENSANDO JUNTOS\nUNIASSEL VI\n1\n1"
    },
    {
      "number": 14,
      "text": "TEMA DE APRENDIZAGEM 1\nPROCESSO CRIATIVO\nO processo criativo é a estruturação de pensamentos e ideias cujo objetivo é solucionar um problema de forma criativa e eficiente. É o processo de transformação \nde uma ideia em uma ação ou produto novo. Sendo assim, recomenda-se aplicar \nesse processo em projetos das mais diversas áreas, desde artes e publicidade até a \nprogramação, a engenharia, dentre outras.\nAtualmente, existem várias abordagens e variações do que chamamos de processo \ncriativo, porém, a mais conhecida e utilizada até hoje é resultado de uma teoria desenvolvida por Graham W allas (2014), a qual divide o processo criativo em quatro etapas:\nPREPARAÇÃO\nRefere-se à etapa na qual se recebe o problema e, de maneira consciente e intencional, \no criativo acessa seu repertório e faz pesquisas relacionadas ao problema em questão.\nINCUBAÇÃO\nPor vezes ignorada, é uma etapa muito importante. É um período de processamento \ninconsciente de tudo que assimilamos na fase de preparação. É quando nos distanciamos do problema, deixando que nosso inconsciente comece a agir, favorecendo o \nsurgimento de ideias. Durante esse período, deve-se aproveitar o ócio ou dedicar-se a \noutros projetos e atividades. \nILUMINAÇÃO\nÉ quando a ideia surge. Após um período de intensa pesquisa, seguido de um trabalho inconsciente do cérebro, o criativo consegue ter ideias mais claras para solucionar o problema.\nIMPLEMENTAÇÃO (OU VERIFICAÇÃO)\nMomento de colocar em prática o que foi proposto na fase de iluminação, de mostrar \na sua ideia, testá-la e validá-la. \n1\n4"
    },
    {
      "number": 15,
      "text": "Importante ressaltar que o processo criativo não é linear, e obstáculos, geralmente, aparecem entre uma etapa e outra, entretanto, conhecer cada etapa do \nprocesso, além de nortear a prática criativa, é o que lhe direcionará quando \nesses obstáculos aparecerem.\nFerramentas para otimização de processos criativos\nExistem algumas ferramentas que ajudam no aperfeiçoamento de pensamentos \ne servem como um suporte ao processo criativo. As mais utilizadas nos mais \nvariados contextos de criação são:\nBRAINSTORMING \nTécnica muito utilizada, pode ser individual, mas possui resultados mais efetivos \nquando feita coletivamente. Tem como objetivo obter o maior número de insights sem \njuízo de valor, tomando nota de todos. O julgamento crítico restringe a imaginação, e \nas ideias fluem melhor quando o deixamos de lado. Em uma sessão de brainstorming, \na quantidade importa mais do que a qualidade. Depois de todas as ideias registradas, \né hora de selecionar, em conjunto, o que faz mais sentido, fazer novas combinações, \nbem como manipular e desenvolver as ideias.\nPNI (POSITIVO, NEGATIVO E INTERESSANTE)\nTécnica cujo objetivo é analisar ideias levando em conta seus aspectos positivos \n(pontos fortes), negativos (pontos fracos) e interessantes (ideias que precisam de uma \nsegunda avaliação). Muito usada para classificar ideias de forma clara e objetiva, a fim \nde facilitar o processo de criação.\nMAPA MENTAL \nTipo de diagrama que permite gerenciar ideias conectando-as de maneira visual, \nordenada e clara, a partir de um problema central. É uma excelente ferramenta para \norganizar ideias e gerar novos insights.\nUNIASSEL VI\n1\n5"
    },
    {
      "number": 16,
      "text": "TEMA DE APRENDIZAGEM 1\nDentre as ferramentas apresentadas, o mapa mental é o mais simples e, por ser \nvisual, serve como base para processos criativos de diversas áreas. Na Figura 2, \napresentamos um exemplo de mapa mental:\nReﬁnamento\nReﬁnamento\nReﬁnamento\nReﬁnamento\nReﬁnamento Reﬁnamento\nReﬁnamentoReﬁnamento\nReﬁnamento\nIdeia 6\nIdeia 5 Ideia 4 Ideia 3\nIdeia 1 Ideia 2\nPROBLEMA\nFigura 2 – Exemplo de mapa mental / Fonte: a autora.\nDescrição da Imagem: a figura apresenta um diagrama com retângulos na cor laranja, e um retângulo maior com \na palavra “problema” ao centro. A partir dele saem seis retângulos com a palavra “ideia”, e de cada retângulo de \nideia saem mais retângulos nomeados como “refinamento”. Fim da descrição.\nMITOS SOBRE CRIATIVIDADE \nCrianças são instintivamente criativas. \nImaginam, por exemplo, que fazem \nparte de uma banda (imaginação) e \num balde transforma-se em tambor \n(ação). Não sabem nem técnicas, nem \nconceitos sobre processos criativos. \nSão criativas porque nasceram assim. \n1\n6"
    },
    {
      "number": 17,
      "text": "Com o passar do tempo, essas mesmas crianças passam a valorizar mais a \nlógica do que a imaginação, a focar na resposta certa e estigmatizar o erro. Isso \nse deve ao fato de “o sistema educacional atual ser baseado na ideia de habilidade \nacadêmica” (COMO..., 2006, on-line), portanto, as crianças foram ensinadas a \nserem assim e, consequentemente, criam-se alguns mitos que geram bloqueios e \nprecisam ser desmistificados. São eles:\nMITO DO ARTISTA\nEsse mito apoia-se na ideia de que criatividade é habilidade específica para artistas, designers, arquitetos, publicitários etc. Já vimos que a criatividade é a imaginação aplicada \npara resolver problemas, e todo mundo tem problemas, logo, criatividade é para todos.\nMITO DO DOM \nCriatividade não é um dom de gênios ou de algumas pessoas especiais. É uma habilidade que pode ser treinada e desenvolvida.\nMITO DA CRIAÇÃO \nHá quem acredite que ser criativo é estar sempre criando coisas grandiosas que serão \nlembradas e reverenciadas no futuro. Acreditar nisso pode ser o suficiente para ocorrer \num bloqueio. \nMITO DO ACASO\nEm algumas situações, pode parecer que algumas ideias surgem repentinamente, \ncomo algo espontâneo. Na verdade, o que acontece nesses casos é uma combinação \ndas referências que o indivíduo já possui, mas que ainda não são suficientes para a \nsolução do problema, com uma informação recebida no momento. Toda a preparação \naté o momento da ideia conta para que esta venha à tona, não existe acaso.\nUNIASSEL VI\n1\n7"
    },
    {
      "number": 18,
      "text": "TEMA DE APRENDIZAGEM 1\nCriar não é obra do acaso, tampouco algo possível apenas a artistas ou um dom \nde poucas pessoas. A criatividade requer prática e aperfeiçoamento. “Escritores \nescrevem. Corredores correm. Estabeleça sua identidade fazendo seu trabalho” \n(GODIN, 2021, p. 43).\nAlém dos mitos sobre criatividade, outra razão para alguns se considerarem \nmenos ou nada criativos é a definição de inteligência. Fomos incentivados a focar \nno desenvolvimento do conhecimento lógico, matemático e linguístico. Quem \ntem dificuldade nessas áreas costuma ser considerado menos inteligente, o que, \nsegundo o psicólogo Howard Gardner (1994), é um equívoco. Esse autor desenvolveu a T eoria das Múltiplas Inteligências, que vai contra a visão tradicional de \nque nossa inteligência pode ser mensurada adequadamente por meio de testes \nde respostas rápidas, como o famoso teste de QI. Após intensa pesquisa, Gardner \n(1994) identificou oito tipos de inteligência distintos:\nINTELIGÊNCIA ESPACIAL \nHabilidade de conceituar e manipular matrizes espaciais em maior ou menor escala. \nPor exemplo: navegação, arquitetura, fotografia. \nINTELIGÊNCIA CORPORAL \nHabilidade de uso do próprio corpo ou partes dele, como dançarinos e artesãos.\nINTELIGÊNCIA MUSICAL \nSensibilidade a ritmos, tons, melodias e timbres. \n1\n8"
    },
    {
      "number": 19,
      "text": "INTELIGÊNCIA LINGUÍSTICA \nSensibilidade ao significado das palavras, à ordem entre elas e aos seus sons, ritmos \ne métricas, por exemplo, escrita de poesia. Também pode-se dizer da facilidade em \naprender idiomas e se comunicar por meio da fala e da escrita.\nINTELIGÊNCIA LÓGICO-MATEMÁTICA \nHabilidade com operações numéricas e raciocínio lógico.\nINTELIGÊNCIA INTERPESSOAL \nFacilidade de interagir de forma eficaz e empática com outras pessoas.\nINTELIGÊNCIA INTRAPESSOAL \nHabilidade em lidar com os próprios sentimentos, conhecer a própria personalidade e \nser capaz de se planejar de acordo com suas próprias características.\nINTELIGÊNCIA NATURALISTA \nHabilidade em fazer distinções ou encontrar padrões na natureza.\nUNIASSEL VI\n1\n9"
    },
    {
      "number": 20,
      "text": "TEMA DE APRENDIZAGEM 1\nApesar da T eoria das Múltiplas Inteligências já ser bastante difundida atualmente, ainda prevalece o conceito tradicional de inteligência, o qual valoriza as \ninteligências lógico-matemática e linguística e subvaloriza as demais, por isso, \nse um indivíduo não se encaixa nesse conceito, considera-se menos inteligente, \nalém de causar demora na descoberta de suas próprias aptidões e, consequente, \no afastamento da criatividade. \nÉ necessário desmistificar esses mitos e crenças e entender que existem vários \ntipos de habilidades e a sociedade precisa de todos eles.\nNo vídeo, o próprio Howard Gardner explica, com detalhes, a Teoria das Múltiplas Inteligências e suas implicações. https:/ /www.youtube.com/watch?v=8N2pnYne0ZA.\nEU INDICO\nOutros tipos de geradores de \nbloqueios\nExistem fatores comportamentais que \nbloqueiam nossa mente criativamente, \npor isso, são considerados os maiores \ngeradores de bloqueios: o medo de \nerrar, o perfeccionismo, a falta de momentos de descanso e lazer, o estresse \ne a produtividade tóxica.\nEsses fatores aumentam nossa ten são, e nossa imaginação deixa de fluir \nnaturalmente, o que gera um bloqueio \nmental, também chamado de bloqueio \ncriativo. Existem, porém, alguns meios \nde lidar com eles:\n1\n1"
    },
    {
      "number": 21,
      "text": "V ale salientar que, até para a pessoa mais criativa, os bloqueios surgirão em algum \nmomento. É uma espécie de aviso da mente para nos lembrar que talvez seja hora \nde parar um pouco, entretanto, entender que existem mitos e comportamentos \nque nos bloqueiam é essencial para evitar bloqueios crônicos.\nPERCA O MEDO DE ERRAR\nCriatividade requer experimentação, e uma vida criativa só existe na base de muita \ntentativa e erro. Como já falamos, o medo do fracasso nos priva de correr riscos e \nenfrentar novos desafios. Superá-lo é essencial para evitar bloqueios.\nCUIDADO COM O PERFECCIONISMO\nA perfeição só existe no campo das ideias e aceitar esse fato pode evitar frustra ções, gasto desnecessário de energia e tempo, além de fazer você aproveitar o pro cesso e sentir-se muito mais realizado. O perfeccionismo nos faz criar expectativas \ntão altas a ponto de formar uma barreira que nos impede de criar e mostrar nosso \ntrabalho para o mundo.\nTRANSFORME COMPARAÇÃO EM INSPIRAÇÃO\nTemos a tendência a nos comparar com outros profissionais de nosso segmento (ou \nnão), mas cada um possui uma vivência, um estilo de vida e privilégios totalmente \ndistintos, o que torna qualquer comparação ser injusta. Que tal se inspirar em vez de \nse comparar?\nCUIDADO COM A PRODUTIVIDADE TÓXICA\nAs redes sociais, geralmente, nos fazem ter a sensação de que todos são produtivos \nmenos nós. O que, costumeiramente, não levamos em conta é o fato de o conteúdo ali \ncompartilhado ser apenas um recorte da realidade e que ninguém é 100% produtivo o \ntempo todo. Ter essa consciência evita a autocobrança desnecessária e, consequentemente, nos aproxima da vida criativa que desejamos.\nUNIASSEL VI\n1\n1"
    },
    {
      "number": 22,
      "text": "TEMA DE APRENDIZAGEM 1\nExercícios para desbloqueio\nOs bloqueios são passíveis de serem revertidos e, para isso, existem ações práticas \nque podemos tomar quando surge um bloqueio. As veremos, a seguir.\n ■ Consulte seu registro de ideias: tenha um lugar para anotar as suas \nideias e consultá-las em momentos de bloqueio, a fim de gerar novas \nideias a partir das que já existem.\n ■ Desconecte-se: muitos de nossos bloqueios surgem a partir do excesso \nde informação. Desligar aparelhos de celular, computador e até a televisão \npor alguns minutos, contemplar as nuvens e os sons ao redor ajuda a sair \nde um bloqueio momentâneo.\n ■ Crie histórias: esse exercício, que consiste em separar três objetos ou \npalavras aleatórias e contar uma história com eles, estimula a imaginação \nmesmo em momentos de bloqueio, podendo ajudar a vencê-los.\n ■ Duble uma cena: coloque uma cena de novela ou filme no mudo e tente \ndublar os personagens. Além de muito divertido, esse exercício também \nestimula a imaginação e ajuda a vencer momentos de bloqueio. \n ■ Dê-se um tempo: para descansar, fazer algo que lhe deixe feliz, ler um \nlivro, ouvir música, caminhar no parque. Desconectar-se é importante \npara que nossa mente desligue e faça novas ligações, gerando novas ideias.\nQualquer atividade que, de alguma maneira, estimule a sua imaginação, lhe ajudará a ter menos bloqueios ou até a vencê-los quando surgirem em sua jornada \ncriativa. Além desses exercícios, é muito importante entender o que está causando \nesses bloqueios. Identificar as causas, refletir sobre elas e entendê-las é a maneira \nmais eficaz de evitar bloqueios criativos.\nDESENVOLVENDO IDEIAS INOVADORAS\nSe a criatividade é a imaginação seguida de ação para \nsolucionar problemas, podemos dizer que a inovação é \na criatividade usada para geração de valor e progresso. \nInovação é a \ncriatividade usada \npara geração de \nvalor e progresso\n1\n1"
    },
    {
      "number": 23,
      "text": "Soluções inovadoras, geralmente, são desenvolvidas por pessoas que decidi ram pela criatividade e não abrem mão da mentalidade criativa (a qual, aliás, \njá abordamos). Essas pessoas estão mais propensas a pensar fora da caixa, a \nver o problema de diferentes perspectivas, e estão sempre em busca de formas \nalternativas de resolvê-lo. “Suas ideias originais são, normalmente, resultado da \nhabilidade que têm de fazer associações incomuns entre ideias aparentemente \nnão relacionadas” (SILV A FILHO, 2010, p. 25). \nIdeias inovadoras, geralmente, nascem quando se leva em conta três fatores \nque precisam ser equilibrados: praticabilidade técnica, viabilidade econômica e \ndesejos do usuário.\nDe acordo com a Lei de Incentivo à Inovação — Lei nº 10.973/2004 — inovação é a \n“introdução de novidade ou aperfeiçoamento no ambiente produtivo ou social que \nresulte em novos produtos, processos ou serviços” (BRASIL, 2004).\nAPROFUNDANDO\nInovação\nPraticabilidade\ntécnica\nViabilidade\neconômica\nDesejo\nhumano\nFigura 3 – Diagrama do ponto \nideal entre os três fatores \nFonte: a autora.\nDescrição da Imagem: a fi gura apresenta um diagrama \nna cor laranja com os dados \n“Viabilidade econômica”, \n“Praticabilidade técnica” e \n“Desejo humano”, cada um \nem um círculo. Na interse ção entre esses círculos, em \numa área em laranja-escuro, \nestá a palavra “Inovação”. \nFim da descrição.\nUNIASSEL VI\n1\n1"
    },
    {
      "number": 24,
      "text": "TEMA DE APRENDIZAGEM 1\nO ponto de equilíbrio entre tecnologia disponível (fator técnico), viabilidade \neconômica (fator de negócios) e os desejos do usuário (fator humano) é onde \nmora a inovação, mas vale salientar que, embora nenhum seja mais importante \nque o outro, a essência da inovação, nos dias atuais, está na empatia.\nCriadores do termo design thinking, nomenclatura dada à abordagem centrada no ser humano para criação de soluções inovadoras, David Kelley e T om \nKelley (2021, p. 12) nos confirmam a ideia anterior, quando dizem: “a profunda \nempatia pelas pessoas faz das nossas observações fontes poderosas de inspiração” . \nDiante disso, podemos dizer que a inovação se fundamenta no equilíbrio entre a \nprofunda compreensão das reais necessidades e desejos de usuários, a tecnologia \ne a viabilidade financeira.\nEm suma, durante nossa jornada, vimos que crianças, geralmente, se afastam \nda criatividade com o passar do tempo, por vários fatores e mitos que tomam \ncomo verdade, então, tornam-se adultos bloqueados, os quais se acham pouco \nou nada criativos, entretanto, vimos que, com a mentalidade e o comportamento \ncorretos, além de ferramentas facilitadoras e processos, todos podem resgatar \nsua criatividade e aplicá-la na vida pessoal ou profissional, independentemente \nda área de atuação. \nTítulo: Confiança criativa: libere sua criatividade e \nimplemente suas ideias.\nAutores: Tom Kelley e David Kelley. \nEditora: Alta Books.\nAno: 2019.\nSobre o livro: os autores mostram que todos \nnós temos um enorme potencial criativo a ser \nexplorado e desenvolvido. Neste livro, eles dividem \nexperiências de alunos que se descobriram criativos \ne profissionais que, aplicando os princípios do design \nthinking, tiveram ideias inovadoras.\nINDICAÇÃO DE LIVRO\n1\n4"
    },
    {
      "number": 25,
      "text": "Estudante, para expandir seus conhecimentos acerca do assunto abordado, gostaríamos de lhe indicar a aula que preparamos especialmente para você. Essa aula \ncontribuirá para aprofundar ainda mais o seu conhecimento sobre o tema. Não perca!\nRecursos de mídia disponíveis no conteúdo digital do ambiente virtual de \naprendizagem \nEM FOCO\nNOVOS DESAFIOS\nA economia criativa segue gerando cada vez mais empregos, bem como renda acima da média do mercado. Desenvolver seu potencial criativo é essencial para estar \npreparado ao futuro e para a competitividade do mercado de trabalho que, cada vez \nmais, valoriza e incentiva profissionais criativos. \nAtualmente, as empresas consideram a criatividade uma habilidade essencial para os líderes e suas \nequipes, portanto, o profissional que aplica a criatividade no seu dia a dia, independentemente de sua área \nde atuação, terá um diferencial importante, melhores \noportunidades de emprego e melhores salários.\nO mercado de trabalho busca profissionais que \nconsigam sair do padrão, que vão além das soluções \nestabelecidas. As corporações enxergam os pro fissionais criativos como aqueles capazes de trazer \nsoluções inovadoras aos problemas novos que um \nmundo tão volátil gera. Ao adotar uma mentalidade \ncriativa e, de fato, praticar a criatividade, seguindo \nseus processos, você chegará lá! \nNão perca tempo e desenvolva seu lado criativo, pois ele é uma das habilidades mais procuradas pelo mercado de trabalho no mundo contemporâneo. \nUNIASSEL VI\n1\n5"
    },
    {
      "number": 26,
      "text": "TEMA DE APRENDIZAGEM 1\n1. Processo criativo é o processo de transformação de uma ideia em uma ação ou produto \nnovos. Recomenda-se aplicá-lo em projetos, a fim de estruturar as ideias e ter resultados \nmais satisfatórios. A abordagem mais utilizada até hoje foi desenvolvida pelo psicólogo \nGraham Wallas e possui quatro etapas. \nCom base no que estudamos, qual das alternativas não configura uma das etapas do \nprocesso criativo desenvolvido por Graham Wallas?\na) Implementação.\nb) Incubação.\nc) Preparação.\nd) Brainstorming.\ne) Iluminação.\n1\n6"
    },
    {
      "number": 27,
      "text": "2. A Teoria das Múltiplas Inteligências (TMI) de Howard Gardner é uma crítica à visão psicológica padrão do intelecto. Com base em evidências provenientes de fontes díspares, a teoria \nafirma que os seres humanos têm uma série de capacidades intelectuais relativamente \ndistintas. \nCom base no exposto e, também, no que estudamos, analise as afirmativas: \nI - De acordo com a TMI, existem oito tipos distintos de inteligência, dentre eles, a inteligência corporal, musical e naturalista.\nII - O teste de QI é capaz de avaliar adequadamente todos os tipos de inteligência que um \nindivíduo possui.\nIII - Tradicionalmente, as inteligências interpessoal e intrapessoal são as mais incentivadas \nnas escolas.\nÉ correto o que se afirma em:\na) I, apenas.\nb) III, apenas.\nc) I e II, apenas.\nd) II e III, apenas.\ne) I, II e III.\nAUTOATIVIDADE\n1\n7"
    },
    {
      "number": 28,
      "text": "3. “Uma pesquisa de opinião conduzida pela Adobe Systems mostrou que apenas 31% dos \nparticipantes acham que têm condições de aplicar todo o seu potencial criativo na própria \nvida pessoal e profissional” (KELLEY; KELLEY, 2019, p. 14). \nCom base no que estudamos, assinale a alternativa que não configura um possível motivo \npara tantas pessoas não acreditarem no seu potencial criativo, como mostrado no estudo: \na) O sistema educacional preza pelo gabarito e pela lógica.\nb) Conforme crescemos, somos desestimulados a imaginar cenários e a questionar.\nc) O medo de errar.\nd) O perfeccionismo.\ne) A não comparação com outras pessoas.\nAUTOATIVIDADE\n1\n8"
    },
    {
      "number": 29,
      "text": "REFERÊNCIAS\nAMABILE, T. M. Componential Theory of Creativity. Boston: Harvard Business School, 2012. \n(Working Paper 12-096). \nAULA 2.3 Habilidades do Futuro - A Prioridade. [S. l.: s. n.], 2022. 1 vídeo (19 min). Publicado pelo \ncanal Keep Learning School. Disponível em: https:/ /youtu.be/bcc7R0hBBE4?si=9NO7FbCG2M9QjaiR. Acesso em: 14 mar. 2024.\nBALDISSERA, O. O que todo educador precisa saber sobre desenvolvimento cognitivo. Blog do \nEaD - PUCPR, Curitiba, 3 nov. 2023. Disponível em: https:/ /www.blogdoead.com.br/tag/mercado-de-trabalho/desenvolvimento-cognitivo. Acesso em: 14 mar. 2024.\nBRASIL. Lei nº 10 973, de 2 de dezembro de 2004. Dispõe sobre incentivos à inovação e à \npesquisa científica e tecnológica no ambiente produtivo e dá outras providências. Brasília, DF: \nDiário Oficial da União, 2004. Disponível em: https:/ /www2.camara.leg.br/legin/fed/lei/2004/\nlei-10973-2-dezembro-2004-534975-publicacaooriginal-21531-pl.html. Acesso em: 14 mar. 2024.\nCOMO as escolas matam a criatividade. [S. l.: s. n.], 2006. 1 vídeo (19 min). Publicado pelo canal TED. Disponível em: https:/ /www.ted.com/talks/sir_ken_robinson_do_schools_kill_creativity?language=pt. Acesso em: 14 mar. 2024.\nEMBRACE the remix. [S. l.: s. n.], 2012. 1 vídeo (9 min). Publicado pelo canal TEDGlobal. Disponível \nem: https:/ /www.ted.com/talks/kirby_ferguson_embrace_the_remix. Acesso em: 14 mar. 2024.\nFERREIRA, A. B. de H. Novo Aurélio século XXI: o dicionário da língua portuguesa. 3. ed. Curitiba: \nPositivo, 2004. \nFIRJAN – FEDERAÇÃO DAS INDÚSTRIAS DO ESTADO DO RIO DE JANEIRO. Mapeamento da \nindústria criativa no Brasil. Rio de Janeiro: Firjan, 2022. \nGARDNER, H. Estruturas da mente: a teoria das múltiplas inteligências. 2. ed. Porto Alegre: Penso, 1994. \nGILBERT, E. Grande magia: vida criativa sem medo. Rio de Janeiro: Objetiva, 2015.\nGODIN, S. A prática: entregando um trabalho criativo. Rio de Janeiro: Alta Books, 2021.\nIBM – INTERNATIONAL BUSINESS MACHINE CORPORATION. Capitalizing on complexity: insights from the global chief executive officer study. New York: IBM, 2010. Disponível em: https:/ /\nwww.ibm.com/downloads/cas/1VZV5X8J. Acesso em: 14 mar. 2024. \nKELLEY, T.; KELLEY, D. Confiança criativa: como desenvolver a sua curiosidade e criatividade. \nRio de Janeiro: Sextante, 2021. \n1\n9"
    },
    {
      "number": 30,
      "text": "REFERÊNCIAS\nKELLEY, T.; KELLEY, D. Confiança criativa: libere sua criatividade e implemente suas ideias. Rio \nde Janeiro: Alta Books, 2019.\nKENT, C; STEWARD, J. Aprender de coração: práticas para libertar o espírito criativo. São Paulo: \nClube do Livro do Design, 2023.\nSILVA FILHO, A. M. Inovação requer criatividade e informação. Revista Espaço Acadêmico, Maringá, ano 10, n. 111, p. 21-25, ago. 2010. Disponível em: https:/ /periodicos.uem.br/ojs/index.php/\nEspacoAcademico/article/view/10793/5843. Acesso em: 14 mar. 2024.\nWALLAS, G. The art of thought. 2nd ed. Kent: Solis Press, 2014. \n1\n1"
    },
    {
      "number": 31,
      "text": "1 Opção D. \nBrainstorming é uma ferramenta facilitadora, utilizada para otimizar o processo criativo. Todas \nas outras são etapas do que chamamos de processo criativo tradicional, desenvolvido por \nGraham Wallas.\n2 Opção A. \nA afirmativa I está correta porque a Teoria das Múltiplas Inteligências descreve oito tipos de \ninteligência: espacial, corporal, musical, linguística, lógico-matemática, interpessoal, intrapessoal e naturalista. A afirmativa II está incorreta porque testes de QI avaliam a inteligência \nlinguística e lógico-matemática e, por vezes, a inteligência espacial, os demais tipos não \nsão considerados nesse tipo de teste. A afirmativa III está incorreta porque, geralmente, o \nsistema educacional incentiva o foco no desenvolvimento das inteligências lógico-mate mática e linguística. \n3 Opção E. \nNão se comparar é uma das características que o indivíduo precisa adotar justamente para \nmudar a concepção de que não é criativo. As demais alternativas configuram ações que \ngeram bloqueios mentais, como visto no material, portanto, podem sim ser consideradas \npossíveis motivos para causá-los.\nGABARITO\n1\n1"
    },
    {
      "number": 32,
      "text": "MINHAS METAS\nINDÚSTRIA E TRANSFORMAÇÃO \nDIGITAL\nDesenvolver pensamento analítico.\nRealizar planejamento estratégico.\nImplementar tomadas de decisões.\nAplicar ferramentas de análises. \nConhecer fontes que possibilitem desenvolvimento contínuo.\nObter pensamento inovador.\nTEMA DE APRENDIZAGEM 2\n1\n1"
    },
    {
      "number": 33,
      "text": "INICIE SUA JORNADA\nImagine um mundo em que as máquinas ganham vida e se tornam parceiras dos \nseres humanos. Uma jornada que começou há muito tempo, na era das grandes \nengrenagens movidas a vapor, quando a Revolução Industrial trouxe a promessa \nde máquinas poderosas que transformariam o trabalho manual em produtividade desenfreada. Um cenário intrigante, não é?\nBem-vindo à nossa máquina do tempo! Aqui, vamos explorar as diferentes \neras industriais que moldaram o tempo presente, e talvez, neste momento, você \npergunte, afinal, para que estamos falando disso? Convidamos você a mergulhar \nnessa trajetória para, juntos, tomarmos decisões e projetarmos uma pluralidade \nde futuros possíveis e plausíveis para nossa jornada.\nAgora a indagação será: “muito interessante esse tema, mas como avaliar e tomar as decisões mais acertadas?” Ainda mais: “como, além de tomar essa decisão, \nplanejar e executar as ações necessárias?”\nPois bem, iniciaremos falando um pouco sobre como imaginamos o futuro \ne quais decisões podemos tomar para que sejamos assertivos.\nV amos mergulhar em um tema realmente empolgante e inovador: as metodologias de Future Thinking , ou Pensamento do Futuro. Imagine poder prever \ntendências, antecipar mudanças e tomar decisões mais informadas neste mundo, \nem constante evolução, em que vivemos. É exatamente isso que o Future Thinking \nnos oferece. V amos explorar como essas metodologias funcionam e por que são \ntão essenciais nos dias de hoje.\nUNIASSEL VI\n1\n1"
    },
    {
      "number": 34,
      "text": "TEMA DE APRENDIZAGEM 2\nEntão, o que exatamente é o Future \nThinking ? Bem, é uma abordagem \nestratégica que nos ajuda a visualizar cenários futuros possíveis e a \ndesenvolver estratégias para nos \nadaptarmos a eles. Em outras pa lavras, é como olhar para um horizonte distante e começar a traçar \ncaminhos que nos levem aonde \nqueremos ir.\nExistem algumas metodo logias que são frequentemente \nusadas no Future Thinking , uma \ndelas é a Análise de Tendências, \nem que examinamos os padrões e \nmudanças no presente para entender como podem afetar o futuro. \nOutra é a Criação de Cenários, \nem que imaginamos diferentes \npossibilidades futuras e como nossa organização ou projeto pode se \nencaixar em cada uma.\nAqui está a parte realmente \nemocionante, pois esse não é apenas um exercício intelectual, mas \numa ferramenta prática que nos \najuda a tomar decisões melhores \nhoje, considerando o que está por \nvir. Ele nos ajuda a evitar surpresas \ndesagradáveis e a estar preparados \npara enfrentar os desafios futuros \nde maneira mais eficaz.\n1\n4"
    },
    {
      "number": 35,
      "text": "Supomos que você esteja gerenciando uma empresa de qualquer setor, ou mesmo um projeto \nde mudanças em qualquer ambiente profissional. Com o Future Thinking, você pode antecipar \nas tendências emergentes, como novas tecnologias ou mudanças no comportamento dos \natores envolvidos no processo. Isso permitiria que você ajustasse sua estratégia de negócios \npara se alinhar a essas mudanças, mantendo sua empresa competitiva.\nUma das principais vantagens do Future Thinking é que ele pode dar a você uma \nvantagem competitiva. Enquanto outros estão reagindo às mudanças, você estará \nse preparando proativamente. Isso não apenas ajuda a evitar riscos, mas também \npode abrir portas para oportunidades que outros podem não ter percebido.\nAgora você tem um vislumbre das incríveis metodologias de Future Thinking. Essa \nabordagem nos permite dar uma espiada no futuro e nos capacita a moldá-lo de \nmaneira mais favorável. É como ter uma bússola que nos guia através das incertezas do amanhã. Então, que tal começar a incorporar essas técnicas em sua abor dagem estratégica? O futuro é seu para criar!\nPara darmos o primeiro passo, lhe convidamos a fazer o download do Canva para \nque seja seu parceiro nesta jornada. Escolha uma situação de seu cotidiano e inicie \no preenchimento para que possamos seguir. Recursos de mídia disponíveis no \nconteúdo digital do ambiente virtual de aprendizagem \nAPROFUNDANDO\nEnquanto outros \nestão reagindo \nàs mudanças, \nvocê estará se \npreparando \nproativamente\nPara exemplificar, escolheremos: “a utilização da inteligência artificial como gerente de processos, usar \nou não?”\nEntão, a partir de agora, vamos olhar para o passado para tomar as decisões?\nUNIASSEL VI\n1\n5"
    },
    {
      "number": 36,
      "text": "TEMA DE APRENDIZAGEM 2\nDESENVOLVA SEU POTENCIAL\nBem, como bons planejadores, olharemos para o passado e tentaremos com preender o que já aconteceu na indústria com o passar dos anos e, com essa \nbagagem, desenhar as tendências.\nEspero que tenha baixado seu planejador, vamos usá-lo durante nossa jor nada. Lembre-se, não há certo ou errado, apenas caminhos diferentes que nos \nlevam a finais futuros diferentes, e você, como gestor, tem a ferramenta necessária para fazer as escolhas que melhor lhe couberem, o conhecimento e os dados \nnecessários para ponderar. \nDiante disso, vamos falar um pouco da história de mudanças. Aqui gostaria \nde ressaltar que cada mudança, durante a história, foi considerada uma inovação. \nT alvez, hoje, isso tudo pareça ultrapassado, mas, na época, eram modelos disruptivos e até mesmo ações duvidosas.\nA falta geral de pensamento futuro e previsão necessária para lidar com isso, \nnos remete ao sucesso do passado, que é a nossa lente padrão.\nIniciamos com a Revolução Industrial, também conhecida como Indústria 1.0, foi o ponto de partida. Imagine a emoção da primeira máquina a \nvapor criada por Thomas Newcomen, bombando água de minas com uma \neficiência surpreendente. Naquele tempo, as cidades ganharam vida com as \nfábricas rugindo e o mundo nunca mais foi o mesmo. Começou entre 1760 e \n1840 na Inglaterra, com a substituição progressiva dos métodos artesanais por \nmáquinas e ferramentas, pela exploração do carvão como energia alternativa \nà madeira e outros biocombustíveis, e pelo uso crescente da energia do vapor \n(COELHO, 2016).\nPronto para se tornar um empresário? Espero que sim! Neste tema, teremos a \noportunidade de tomar decisões importantes e que podem fazer toda a diferença no desenrolar da trajetória! Falaremos um pouco disso em nosso podcast! \nAperte o play e venha conosco nessa caminhada! Ou não aperte! Você decide \no final! Recursos de mídia disponíveis no conteúdo digital do ambiente virtual \nde aprendizagem \nPLAY NO CONHECIMENTO\n1\n6"
    },
    {
      "number": 37,
      "text": "Ao olharmos o passado da sociedade traçado desde o princípio dos processos industriais, podemos perceber que houve inúmeras mudanças por causa das invenções \ne coisas novas. Na história, encontramos basicamente três revoluções industriais, \ncada uma delas acontecendo na sua própria época. Esses acontecimentos alteraram \nprofundamente a maneira como as pessoas pensam, agem e se comportam.\nEssas revoluções industriais não são coisas soltas, estão todas ligadas e aconteceram subsequentemente. \n INDÚSTRIA 1.0 \n• Era da Mecanização.\n• Século XVIII e XIX.\n• Máquinas à vapor.\n INDÚSTRIA 2.0 \n• Era da Eletricidade.\n• 1850 à 1ª Guerra Mundial.\n• Linhas de montagem.\n• Produção em massa.\nUNIASSEL VI\n1\n7"
    },
    {
      "number": 38,
      "text": "TEMA DE APRENDIZAGEM 2\n INDÚSTRIA 3.0 \n• Era da Automação.\n• 1950 a 1970.\n• Computação e eletrônica.\n INDÚSTRIA 4.0 \n• Era de Sistemas Ciberfísicos.\n• Atualmente.\n• IOT (Internet das Coisas).\n• Automação de softwares.\n• Robôs autônomos.\n INDÚSTRIA 5.0 \n• Fusão das tecnologias físicas, digitais e \nbiológicas.\n1\n8"
    },
    {
      "number": 39,
      "text": "Essas mudanças que vieram com as revoluções, impulsionadas pela ciência e \ntecnologia, tiveram um grande impacto na sociedade, alteraram a organização de \nsetores, deram origem a novas formas de planejamento e até mudaram a cultura, \nfatores que nos afetam ainda hoje.\nCom todo esse processo de evolução, a necessidade de gerenciamento também \ncresceu. De modo que, quanto mais ferramentas e tecnologias surgem, mais temos \noportunidades de identificar as necessidades e possibilidades de gerenciamento. \nAntigamente, o trabalho era coordenado por meio de violência, mas, ao longo \ndo tempo, essa violência foi dando espaço para uma administração mais organizada (SILV A, 2020). Por essa razão, é importante coletar dados para que as decisões sejam tomadas de forma consciente, pautadas em informações e estratégias. \nNas décadas que se seguiram, até ao fim da Segunda Guerra Mundial, as evoluções foram significativas na área da indústria química, elétrica e do aço, assim \ncomo um aprimoramento significativo das técnicas existentes (COELHO, 2016).\nUNIASSEL VI\n1\n9"
    },
    {
      "number": 40,
      "text": "TEMA DE APRENDIZAGEM 2\nAgora, avance conosco para a Era da Produção em Massa, a Indústria 2.0. \nImagine-se nas fábricas da famosa linha de montagem de Henry Ford. Carros \neram montados como um quebra-cabeça gigante e saíam pelas portas a uma \nvelocidade impressionante. Curioso, não é? Contudo, essa revolução foi além \ndos carros, ela trouxe consigo a eletrificação e uma nova forma de enxergar a \nprodução em larga escala.\nA próxima parada é na Era da Automação, a Indústria 3.0. Aqui, a tecnologia \nse torna uma aliada ainda mais poderosa. Imagens de robôs industriais, meticulosamente executando tarefas complexas, ganham vida. As máquinas se tornam inteligentes e assumem funções antes realizadas por seres humanos. Isso tudo aconteceu \nenquanto a eletrônica e os computadores davam um salto surpreendente.\nA Indústria 4.0 chega com um passo à frente na evolução, com a internet se \nexpandindo, sensores menores e mais poderosos a preços acessíveis, e softwares \ne hardwares cada vez mais avançados. As máquinas começaram a aprender e \ncolaborar, criando redes gigantes de “coisas” . Isso desencadeou uma mudança \nna indústria, com um impacto enorme na competitividade, na sociedade e na \neconomia, a ponto de transformar o mundo como conhecemos.\nOs professores Erilk Braynjolfsson e Andrew McAfee, do Instituto de T ecnologia de Massachusetts, chamaram isso de “segunda era da máquina” , e em 2011, na \nFeira Industrial de Hannover, na Alemanha, se começou a falar em “Indústria 4.0” .\n4\n1"
    },
    {
      "number": 41,
      "text": "Imagine robôs conversando uns com os outros, trocando informações como colegas de trabalho. A Internet das Coisas faz com que nossos objetos cotidianos, \ncomo geladeiras e carros, compartilhem dados pela internet.\nUma curiosidade fascinante: as impressoras 3D, que começaram como um \nexperimento, agora moldam o futuro ao criar objetos complexos com uma \nprecisão surpreendente.\nPENSANDO JUNTOS\nEm cada era a indústria mudou radicalmente. Da fumaça das primeiras fábricas \nà conectividade avançada da Indústria 4.0, a jornada industrial é uma emocionante história de inovação e superação. Agora, estamos vivendo uma era em que \na tecnologia não é apenas nossa ferramenta, mas também nossa parceira na busca \npor um futuro mais eficiente, inteligente e sustentável.\nHoje em dia, os clientes buscam mais do que apenas produtos; eles querem \nexperiências, tudo é levado em consideração no momento da compra: a embalagem, \na marca, o atendimento, os serviços pós-venda e até mesmo o que outras pessoas \ndizem acerca do produto.\nA redes sociais desempenham um papel importante na disseminação de ex periências de outros consumidores, pois há informação acessível para que as \nescolhas sejam baseadas em fatos, não apenas intuições. Assim, passamos de \numa era de produção em massa para uma era de customização em massa, em \nque produtos e serviços são adaptados às necessidades individuais a custos \ncomparáveis aos da produção em massa, pois as novas condições com que a \ntransformação digital impulsiona produtos e serviços com a introdução de \nrecursos digitais, materiais mais inteligentes e sensores que monitoram o de sempenho em tempo real, previnem problemas antes que ocorram. Isso ma ximiza a utilidade, reduz os custos e aumenta o valor percebido pelos clientes.\nO Fórum Econômico Mundial define inovação como a comercializa ção bem-sucedida de ideias inovadoras , que inclui novos produtos, serviços, \nprocessos ou modelos de negócios que melhoram a experiência do cliente ou \nUNIASSEL VI\n4\n1"
    },
    {
      "number": 42,
      "text": "TEMA DE APRENDIZAGEM 2\naumentam a produtividade das empresas. Entendemos que a inovação colaborativa, destacada pelo Fórum, gera sinergias e vantagens competitivas, impulsionando o crescimento social e econômico. Empresas jovens e estabelecidas \nbuscam essa inovação para permanecerem ágeis e competitivas, introduzindo \nprodutos ou serviços que criam valor para todos.\nPara o professor Mark Esposito, da Harvard University, a inovação colaborativa \né fundamental para criar novos modelos de negócios colaborativos, ancorados no \nempreendedorismo. Essa mudança de paradigma está forçando as organizações a \nrepensarem suas operações para se tornarem mais rápidas, ágeis e adaptadas a um \nmundo em constante mudança e complexa concorrência (COELHO, 2016).\nDiante desse cenário em desenvolvimento, não podemos deixar de lado a importância da inovação. Com a economia globalizada, a inovação se torna um elemento crucial para a competitividade e a sobrevivência das empresas no mercado, \ncontribuindo, por conseguinte, para o desenvolvimento econômico das nações. \nPercebemos que esse tema tem sido amplamente debatido tanto no meio \nacadêmico quanto no mundo corporativo. Estudos acadêmicos que demonstram a importância da inovação tecnológica no crescimento das empresas e no \ndesenvolvimento econômico das nações têm uma longa história, e até mesmo \npensadores, como Adam Smith e Karl Marx, abordaram o tema, embora não \ntenham se concentrado em análises econômicas, no entanto, foi com Joseph \nSchumpeter que o progresso tecnológico começou a ser estudado como um \ncomponente vital para o desenvolvi mento econômico.\nSchumpeter introduziu a palavra \n“inovação” para descrever as mudanças \nrevolucionárias que podem ser introduzidas no sistema econômico, alterando \nfundamentalmente as relações entre produtores e consumidores, para ele, a inovação era o motor do desenvolvimento \neconômico e, a partir do momento em \nque a adoção de novas tecnologias passou a ser vista como uma oportunidade \npara o crescimento econômico, uma \nnova dinâmica surgiu.\n4\n1"
    },
    {
      "number": 43,
      "text": "A evolução da incorporação de inovações nas organizações, dentro do modelo \ncapitalista de geração de riqueza, envolveu a absorção de novas tecnologias, \nconceitos, processos, modelos de gestão, pessoas e suas ideias inovadoras. Independentemente da estratégia adotada para criar novos produtos, processos, \nserviços e métodos organizacionais, é inegável que a inovação é uma tarefa \ncomplexa, que exige a integração de diversas atividades, altos investimentos e \na disposição para assumir riscos significativos. \nPor muitos anos, as organizações seguiram abordagens de “inovação fechada” , \ninvestindo pesadamente em Pesquisa e Desenvolvimento (P&D) e contratando \nos melhores talentos para trazer novas ideias para o mercado (MAGALHÃES \nJÚNIOR, 2023). Hoje, contamos com inúmeros modelos de inovação, além de \ntécnicas e ferramentas que direcionam o trabalho.\nO conceito de Inovação Aberta, também conhecido como open innovation, \nem inglês, surgiu em 2003, e, desde então, tem acontecido debates em torno de \numa suposta rivalidade entre inovação aberta e inovação fechada, no entanto, \nserá que esses conceitos são realmente opostos? \nV amos entender melhor o que são inovação aberta e inovação fechada. A inovação aberta envolve a colaboração com outras empresas ou parceiros externos \npara impulsionar a inovação, enquanto a inovação fechada é realizada inteiramente com recursos internos da empresa, portanto, é essencial compreender as \ndiferenças entre essas abordagens para promover a inovação em uma empresa.\nO processo de inovação envolve a geração de ideias para desenvolver projetos que podem ser testados e implementados na empresa, nesse sentido, uma \nempresa pode escolher entre inovação aberta, trazendo ideias de fontes externas, \nou inovação fechada, desenvolvendo tudo internamente.\nUNIASSEL VI\n4\n1"
    },
    {
      "number": 44,
      "text": "TEMA DE APRENDIZAGEM 2\nA inovação aberta, no entanto, também apresenta desafios, como a gestão do relacionamento entre agentes internos e externos, a necessidade de atualização constante, a adaptação da cultura organizacional e a identificação de parceiros adequados.\nPortanto, a inovação aberta e a fechada não precisam ser mutuamente exclusivas. Muitas empresas começam com inovação aberta e, posteriormente, trazem \nos projetos para dentro de casa para a fase final. Em um mundo cada vez mais \ncolaborativo, essas abordagens podem ser combinadas para impulsionar a inovação e o sucesso dos negócios.\nPara além disso, Freeman (1987) definiu quatro categorias de inovação:\n ■ inovação incremental;\n ■ inovação radical;\n ■ mudanças do sistema tecnológico; \n ■ mudança no paradigma tecno-econômico.\nA principal diferença entre inovação aberta e inovação fechada está no modelo de \nfuncionamento. A inovação fechada é o modelo tradicional, em que a empresa \nconduz todo o processo internamente, desde pesquisa e desenvolvimento até a \ncomercialização do produto. Isso garante sigilo das informações e conhecimento \nexclusivo para uso interno, conferindo à empresa uma vantagem competitiva.\nA inovação aberta, por outro lado, envolve a colaboração com profissionais de \noutras empresas, pesquisadores, acadêmicos e até membros do governo, o que \nenriquece o processo de inovação, reunindo diversas perspectivas e conhecimentos, pode reduzir custos, uma vez que não é necessário manter uma grande \nequipe interna e também reduz riscos, pois envolve um conjunto diversificado de \nprofissionais trabalhando no projeto.\nZOOM NO CONHECIMENTO\n4\n4"
    },
    {
      "number": 45,
      "text": "Não se esqueça, ser inovador é ser criativo!\nCom base em todos os conceitos que vimos até aqui, convidamos você, estudante, \na, mais uma vez, experimentar ferramentas que podem lhe auxiliar nessa jornada \nde inovação e enriquecer esse processo.\nTrouxemos mais ferramentas, para que você possa utilizar na sua tomada de decisão, lembre-se, a sua jornada é única e a sua escolha o levará por caminhos únicos. \nAqui, temos o teste de valores sobre a sua proposta e o cartão de aprendizado. \nInicialmente, elenque as dores e os ganhos da proposta e depois acesse o cartão \nde aprendizado, anotando os elementos que estruturam a sua ideia de inovação, que foi colocada primeiramente em seu Canva. Você pode, inclusive, se reunir \ncom alguns colegas de trabalho, e, assim, todos preenchem o cartão e discutem \nsobre as ideias propostas.\nObserve a dinâmica desse material. Poderíamos fazer isso? Ele vai indicando onde \nas ferramentas se encaixam dentro do Canva maior.\nRecursos de mídia disponíveis no conteúdo digital do ambiente virtual de \naprendizagem \nAPROFUNDANDO\nPensando nesse processo inovativo, trouxemos mais duas ferramentas que podem lhe auxiliar a continuar no processo de criação e avaliação de sua proposta \nde valor. Segue, agora, um cartão de aprendizado, utilize-o após a conversa e \nanálise. Recursos de mídia disponíveis no conteúdo digital do ambiente virtual \nde aprendizagem \nEU INDICO\nUNIASSEL VI\n4\n5"
    },
    {
      "number": 46,
      "text": "TEMA DE APRENDIZAGEM 2\nNão podemos nos preocupar muito com o passado, afinal estamos olhando \npara o futuro, mas gostaríamos de lhe passar alguns conceitos construídos, \npois podem ser utilizados.\nAo longo da nossa jornada humana e econômica, a tecnologia tem exerci do um impacto significativo, redefinindo a maneira como nos relacionamos \ne realizamos tarefas. Lembra daquele tempo em que a produção industrial \ndeu seu primeiro pulo revolucionário? Foi quando engrenagens inteligentes, \ncomo a tecnologia a vapor, também conhecida como a Primeira Revolução \nIndustrial, começaram a aparecer.\nAssim, adentramos na Segunda Revolução Industrial, apresentando um novo \ntrunfo: máquinas mais potentes e duradouras, que suplantaram as antigas máquinas a vapor. Iniciamos com a Revolução Industrial, também conhecida como \nIndústria 1.0, foi o ponto de partida. Imagine a emoção da primeira máquina a \nvapor criada por Thomas Newcomen, bombando água de minas com uma eficiência surpreendente. Naquele tempo, as cidades ganharam vida com as fábricas \nrugindo e o mundo nunca mais foi o mesmo. Começou entre 1760 e 1840 na \nInglaterra, com a substituição progressiva dos métodos artesanais por máquinas e \nferramentas, pela exploração do carvão como energia alternativa à madeira e outros biocombustíveis, e pelo uso crescente da energia do vapor (COELHO, 2016).\nEssas revoluções industriais não são coisas soltas, estão todas ligadas e \naconteceram subsequentemente, e essas mudanças que vieram com as revo luções, que foram impulsionadas pela ciência e tecnologia, tiveram um grande \nimpacto na sociedade, mexeram em como as coisas eram organizadas, deram \norigem a novas formas de planejamento e até mudaram a cultura de um jeito \nque a gente ainda sente hoje.\nCom o domínio da energia elétrica, por volta da metade do século XX, as \ncoisas ficaram ainda mais interessantes. Os processos de produção começaram \na funcionar com uma precisão e sincronização incríveis, graças às máquinas e à \nrobótica, marcando, assim, a Terceira Revolução Industrial.\nApós, deu-se início à Revolução Digital, com toda sua bagagem de truques, \ndesde vantagens competitivas, que deixaram todo mundo de queixo caído, até \nmodelos de negócios totalmente novos. Não podemos esquecer das mudanças \nnos gostos dos consumidores e da entrada em cena das startups. \n4\n6"
    },
    {
      "number": 47,
      "text": "T udo isso levou as pessoas a perceberem que a robótica disponível precisava \nser aprimorada para atender às demandas do século XXI. \nOs novos cenários sugerem um futuro radicalmente transformador e que se \nmove em uma velocidade a qual a maioria não está preparada. O foco na disrupção aumenta nosso nível de urgência, ou nos embala em uma falsa sensação \nde segurança baseada no passado? Nossa visão predeterminada do termo nos \najuda a entender o quão dramáticas são as mudanças que estão por vir? Isso leva \nà percepção de que as características e atributos de nossa organização devem \nmudar radicalmente se quisermos permanecer viáveis? Não temos certeza disso.\nO termo “Indústria 4.0” , também conhecido como a Quarta Revolução \nIndustrial, descreve um avanço significativo na manufatura, em que o mundo \nreal se conecta ao virtual para aumentar a competitividade na produção, seus \nobjetivos estão intrinsecamente ligados ao uso de tecnologias como a Internet \ndas Coisas, a biologia sintética, a inteligência artificial, o Big Data, sistemas \nciberfísicos, manufatura aditiva e outras. \nAlém disso, há avanços notáveis na segurança da informação, interação \nhumano-computador e uma série de equipamentos tecnológicos, incluindo \nimpressoras 3D, redes 5G, robôs, sensores inteligentes e dispositivos móveis, \nessas tecnologias, combinadas com novas técnicas de gestão, têm o potencial \nde impulsionar o progresso rápido das empresas, especialmente nas indústrias \nautomobilística, tecnológica e biológica.\nOs conceitos da Indústria 4.0 podem ser aplicados em empresas de diversos \nsetores, como aquelas envolvidas em transporte automatizado, que inclui veículos controlados remotamente, no entanto, é essencial capacitar os trabalhadores \npara a utilização eficaz dessas tecnologias. Além disso, as empresas enfrentam \no desafio do alto custo de implementação de certos recursos tecnológicos e, em \nalguns casos, a resistência por parte dos gestores em aceitar mudanças. \nPor isso, é fundamental compreender que, apesar da presença da tecnologia e \ndos recursos disponíveis, é necessário investir em capacitação, políticas públicas \ne educação para garantir que esses recursos beneficiem uma parcela maior da \npopulação. Sabendo que a falta de conhecimento e habilidades na utilização das \ntecnologias pode resultar em perda de receita e competitividade para algumas \nempresas, levando até mesmo ao seu fechamento.\nUNIASSEL VI\n4\n7"
    },
    {
      "number": 48,
      "text": "TEMA DE APRENDIZAGEM 2\nUm exemplo disso é a startup Easy Taxi, que, apesar de utilizar tecnologia, não \nconseguiu inovar o suficiente para competir com aplicativos como o Uber. A Kodak \ntambém é um caso emblemático, uma vez que não conseguiu se adaptar às \nmudanças trazidas pelos smartphones e aplicativos de compartilhamento de fotos, \no que levou à sua falência.\nEm resumo, a Indústria 4.0 representa uma mudança significativa na forma como \nas empresas operam, impulsionada por avanços tecnológicos e que, para colher os \nbenefícios dessas inovações, é necessário investir em capacitação e estar disposto \na abraçar as mudanças necessárias (BARROS et al., 2022).\nDiante desse cenário em desenvolvimento, não podemos deixar de lado a importância da inovação. Com a economia globalizada, a inovação se torna um elemento crucial para a competitividade e a sobrevivência das empresas no mercado, \ncontribuindo, por conseguinte, para o desenvolvimento econômico das nações. \n4\n8"
    },
    {
      "number": 49,
      "text": "REFERÊNCIAS\nBARROS, B. R. G. et al. Impacto da indústria 4.0 no século XXI: um estudo teórico. Revista Contemporânea, [s. l.], v. 2, n. 5, p. 878-892, 2022. \nCOELHO, P. M. N. Rumo à indústria 4 0. 2016, 65 f. Dissertação (Mestrado em Engenharia Mecânica) – Universidade de Coimbra, Coimbra, 2016.\nFREEMAN, C. Technology policy and economic performance. Londres: Pinter, 1987.\nMAGALHÃES JÚNIOR, D. B. de. Direitos de propriedade intelectual e modelos de inovação aberta (Open Innovation): um estudo teórico sobre o papel dos Direitos de Propriedade Intelectual na \npromoção dos modelos de inovação aberta. P2P e Inovação, Rio de Janeiro, v. 9, n. 2, p. 153-168, \n2023. \nNEGREIROS, G. C. Planejamento estratégico em micro e pequenas empresas: um estudo multicasos. 2022, 44 f. Projeto (Graduação em Engenharia de Produção) – Universidade de Brasília, \nBrasília, DF, 2022.\nNEIS, D. F.; PEREIRA, M. F.; MACCARI, E. A. Processo de planejamento estratégico e estrutura organizacional: impactos, confluências e similaridades. BBR – Brazilian Business Review, Vitória, \nv. 14, n. 5, p. 479-492, set./out. 2017.\nRIGBY, D.; BILODEAU, B. Management tools & trends 2015. Massachusetts: Bain & Company, \n2015.\nSILVA, A. de O. da. A importância da administração de conflitos nas relações de trabalho.  Administração de Empresas em Revista, Curitiba, v. 3, n. 21, p. 271-280, ago. 2020. Disponível em: \nhttps:/ /revista.unicuritiba.edu.br/index.php/admrevista/article/view/3851. Acesso em: 15 fev. \n2024.\n4\n9"
    },
    {
      "number": 50,
      "text": "MINHAS ANOTAÇÕES\nMINHAS ANOTAÇÕES\n5\n1"
    },
    {
      "number": 51,
      "text": "MINHAS ANOTAÇÕES\nMINHAS ANOTAÇÕES\n5\n1"
    },
    {
      "number": 52,
      "text": "MINHAS ANOTAÇÕES\nMINHAS ANOTAÇÕES\n5\n1"
    }
  ]
};
