// Material de Estudo Auto-Gerado para a disciplina: Estudo Contemporâneo e Transversal_ Relações Étnico-Raciais, Cultura e Direitos Humanos
window.FisioMaterials = window.FisioMaterials || {};
window.FisioMaterials["s6_estudo_contemp"] = {
  "title": "Estudo Contemporâneo e Transversal_ Relações Étnico-Raciais, Cultura e Direitos Humanos",
  "toc": [
    {
      "title": "_GoBack",
      "page": 47
    }
  ],
  "pages": [
    {
      "number": 1,
      "text": "HUGO RIOS BRETAS\nMARCONE COSTA CERQUEIRA\nESTUDO \nCONTEMPORÂNEO \nE TRANSVERSAL:\nRELAÇÕES \nÉTNICO-RACIAIS, \nCULTURA \nE DIREITOS \nHUMANOS"
    },
    {
      "number": 2,
      "text": "Coordenador(a) de Conteúdo \nVera Lucia Hoffmann Pieritz\nProjeto Gráfico e Capa\nArthur Cantareli Silva\nEditoração\nAlan Diego Hordina; Ellen Jeane Versari; \nLaura Janke\nDesign Educacional\nAmanda Peçanha dos Santos\nRevisão Textual\nSalen Nascimento\nIlustração\nAndre Luis Azevedo da Silva\nEduardo Aparecido Alves\nFotos\nShutterstock e Envato\nImpresso por: \nBibliotecária: Leila Regina do Nascimento - CRB- 9/1722.\nFicha catalográfica elaborada de acordo com os dados fornecidos pelo(a) autor(a).\n48 p.\n1. Relação 2. Étnico-r\nacial 3. Cultura 4. Direito 5. EaD. I. Título.\nCDD - 320.56\nEXPEDIENTE\nFICHA CATALOGRÁFICA\nNúcleo de Educação a Distância. BRETAS, Hugo Rios; CERQUEIRA, \nMarcone Costa.\nE\nstudo Contemporâneo e Transv ersal: relações étnico-raciais, \ncultura e direitos humanos / Hugo Rios Bretas, Marcone Costa \nCerqueira. - Florianópolis, SC: Arqué, 2024. Reimpresso em 2025.\nN964\nISBN digital 978-65-279-0937-8"
    },
    {
      "number": 3,
      "text": ""
    },
    {
      "number": 4,
      "text": "RECURSOS DE IMERSÃO\nUtilizado para temas, assuntos ou conceitos avançados, levando ao aprofundamento do que está sendo trabalhado \nnaquele momento do texto. \nAPROFUNDANDO\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você \nterá indicações de filmes \nque se conectam com o \ntema do conteúdo.\nINDICAÇÃO DE FILME\nUma dose extra de \nconhecimento é sempre \nbem-vinda. Aqui você terá \nindicações de livros que \nagregarão muito na sua \nvida profissional.\nINDICAÇÃO DE LIVRO\nUtilizado para desmistificar pontos \nque possam gerar confusão sobre o \ntema. Após o texto trazer a explicação, \nessa interlocução pode trazer pontos \nadicionais que contribuam para que \no estudante não fique com dúvidas \nsobre o tema. \nZOOM NO CONHECIMENTO\nEste item corresponde a uma proposta \nde reflexão que pode ser apresentada por \nmeio de uma frase, um trecho breve ou \numa pergunta. \nPENSANDO JUNTOS\nUtilizado para aprofundar o \nconhecimento em conteúdos \nrelevantes utilizando uma linguagem audiovisual.\nEM FOCO\nUtilizado para agregar um conteúdo \nexterno.\nEU INDICO\nProfessores especialistas e convidados, ampliando as discussões sobre os temas por meio de \nfantásticos podcasts.\nPLAY NO CONHECIMENTO\nPRODUTOS AUDIOVISUAIS\nOs elementos abaixo possuem recursos \naudiovisuais. Recursos de mídia disponíveis no conteúdo digital do ambiente \nvirtual de aprendizagem.\n6\n4"
    },
    {
      "number": 5,
      "text": "6TEMA 1\nCONDUTAS: DEVO, MAS NÃO POSSO; POSSO, MAS NÃO DEVO; DIZEM QUE É CERTO, \nMAS PARECE ERRADO, E AÍ? 6\nSER OU NÃO SER? EIS A QUESTÃO . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8\nEXPLORANDO AS DIFERENÇAS CULTURAIS. . . . . . . . . . . . . . . . . . . . . . . . . . . . 15\n26TEMA 2\nINDAGAÇÕES 26\nA JORNADA DO CIDADÃO . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28\n5\nSUMÁRIO"
    },
    {
      "number": 6,
      "text": "MINHAS METAS\nCONDUTAS: DEVO, MAS NÃO POSSO; \nPOSSO, MAS NÃO DEVO; DIZEM QUE É \nCERTO, MAS PARECE ERRADO, E AÍ?\nEntender a importância do comportamento humano em sociedade.\nExplorar a questão das diversidades culturais e suas relações étnico-raciais, a História e \nculturas afro-brasileira e indígena e as normativas da vida em sociedade.\nAvaliar as consequências do comportamento ético e profissional.\nValorizar as diferenças culturais entre etnias e povos diversos.\nQuestionar normas sociais, políticas e códigos de conduta, e refletir sobre crenças culturais \ninternalizadas.\nIncentivar o protagonismo ativo.\nCriar uma estrutura de avaliação que permita identificar e questionar dogmas sociais, \nbuscando promover mudanças positivas.\nTEMA DE APRENDIZAGEM 1\n6"
    },
    {
      "number": 7,
      "text": "INICIE SUA JORNADA\nA vida em sociedade é repleta de dilemas e contradições que moldam a vida dos \nindivíduos. Na maioria do tempo, estamos tão focados nas tarefas, nos prazos, \nnas metas, que, muitas vezes, ignoramos a importância de nossas escolhas. Não \nobstante, por vezes, não buscamos refletir acerca do fator motivador de cada uma \nde nossas ações ou do valor que atribuímos àquilo que fazemos.\nQual o valor que atribuo àquilo que eu faço? Como devo me relacionar com os \noutros? O que será que as outras pessoas esperam de mim? Como devo me portar diante \nde determinadas situações? Essas perguntas podem servir como um norte e nos ajudar \na refletir sobre quem somos e o que esperamos de nós e do mundo ao nosso redor.\nAo explorar as encruzilhadas das diversidades culturais e suas relações étnico-raciais e a História e cultura afro-brasileira e indígena, somos desafiados a compreender as \nnormas da vida em sociedade, suas origens e influências em nossas decisões. Questionar \no que é certo ou errado implica em analisar como as normas são estabelecidas e como \npodem limitar ou possibilitar nossas interações com os outros. Aprendemos que as \nnormas não são estáticas e podem variar de acordo com as culturas, permitindo uma \nreflexão sobre como nos relacionamos com diferentes grupos sociais.\nNão existe uma receita pronta ou caminho único. De todo modo, é preciso \ndesenvolver uma perspectiva empática e inclusiva, que valorize as diferentes formas de relacionamento e respeitem e promovam a igualdade entre os indivíduos. \nÉ uma oportunidade para crescermos como seres humanos e construirmos um \nambiente mais tolerante e harmonioso.\nVAMOS RECORDAR?\nVamos recordar alguns aspectos importantes. As decisões que tomamos e as escolhas que fazemos têm um impacto significativo nas relações sociais e na busca \npor uma convivência mais harmoniosa. Nesse sentido, devemos atuar e conhecer \nmecanismos e meios propositivos de mudança, buscando \ndesconstruir preconceitos, promover o respeito mútuo e agir \nde forma ética e responsável em nosso convívio com os outros. \nAssista ao curta metragem Alike, que possui uma mensagem \nmuito importante sobre nossas escolhas e os efeitos de nossas \nações na nossa vida e na vida de outras pessoas.\nUNICESUMAR\n7"
    },
    {
      "number": 8,
      "text": "TEMA DE APRENDIZAGEM 1\nSER OU NÃO SER? EIS A QUESTÃO\nEstudante, você há de convir que o comportamento humano é algo fascinante. A \ncapacidade de comunicar, criar e organizar faz com que sejamos uma espécie com \npossibilidades infinitas. Cada indivíduo é, em alguma \nmedida, aquilo que faz e pensa. Portanto, nesse contexto, nossas decisões e escolhas dizem muito sobre \nnossa consciência e maneira de nos relacionarmos \ncom o mundo.\nA literatura é um bom meio para compreendermos um pouco mais do que acontece no íntimo da mente humana. Quando menciono literatura, não me refiro apenas \nà literatura acadêmica, mas também à literatura de modo geral, a qual, frequentemente, proporciona elementos muito ricos para a compreensão da realidade e do \ncomportamento social.\nPodemos tomar, como exemplo, a obra de William Shakespeare, A Tragédia de \nHamlet, Príncipe da Dinamarca, um livro clássico que apresenta, de forma nítida, a natureza humana e sua relação com escolhas, paixões e, sobretudo, dilemas \nque permeiam nosso pensamento (KARNAL, 2018). Essa obra é tão aclamada \nque foi adaptada para o teatro, rádio, televisão e cinema.\nEm síntese, a peça narra a história de Hamlet, um príncipe determinado a \nvingar a morte de seu pai, o rei também chamado Hamlet, que foi envenenado \npor seu próprio irmão, Claudius. Hamlet finge estar louco para ganhar tempo e \nplanejar sua vingança. Ele finalmente mata Claudius, mas acaba morrendo no \nprocesso. A peça explora temas como vingança, loucura, amor, morte e destino. É \numa obra complexa e multifacetada que tem sido interpretada de várias maneiras \nao longo dos séculos.\nO título desta seção é inspirado em parte do monólogo presente no Ato III \nda peça, o qual nos conduz a uma discussão sobre nossas escolhas e liberdades, \nlançando luz sobre uma corrente teórica dentro da filosofia, o existencialismo.\nCada indivíduo é, \nem alguma medida, \naquilo que faz e \npensa\n8"
    },
    {
      "number": 9,
      "text": "Na obra O Existencialismo É Um Humanismo, o filósofo francês Jean-Paul Sartre \n(1973, p. 23) afirma que: “A escolha é possível, em certo sentido, porém o que não é \npossível é não escolher. Eu posso sempre escolher, mas devo estar ciente de que, \nse não escolher, ainda assim estarei escolhendo”. Como podemos perceber, assim \ncomo Hamlet, estamos condenados a ser livres e, consequentemente, compelidos a fazer escolhas sempre.\nO existencialismo é uma corrente filosófica de destaque, conferindo relevância \nà experiência singular do indivíduo e a sua liberdade intrínseca. Nessa perspectiva, os existencialistas sustentam que os seres humanos ingressam no mundo \nsem um propósito ou significado predefinidos, sendo incumbidos da tarefa de \nforjar seus próprios valores e objetivos. Surgindo no século XIX como filósofo \ndinamarquês Søren Kierkegaard, o existencialismo conquistou notoriedade \nno século XX, graças aos eminentes pensadores franceses Jean-Paul Sartre \ne Simone de Beauvoir. O impacto desse movimento filosófico reverberou, de \nmaneira significativa, nas esferas da filosofia, da literatura e das artes, e suas \nexplorações enveredaram por territórios temáticos que englobam a liberdade, a \nresponsabilidade, a angústia, o niilismo e a morte (BUNGE, 2012).\nAPROFUNDANDO\nUNICESUMAR\n9"
    },
    {
      "number": 10,
      "text": "TEMA DE APRENDIZAGEM 1\n Søren Kierkegaard foi um filósofo dinamarquês do \nséculo XIX, pioneiro no existencialismo. Suas obras \nprofundas exploraram a natureza da fé, da angústia e \nda individualidade. Ele desafiou as convenções religiosas e sociais de sua época, enfatizando a importância \nda escolha individual e da autenticidade na vida humana.\n Jean-Paul Sartre Ícone do existencialismo no século XX, um renomado filósofo, escritor e dramaturgo \nfrancês. Sua filosofia enfatizava a liberdade radical do \nindivíduo e a responsabilidade pela própria existência. \nEle explorou temas como a angústia, o absurdo e a \nbusca por significado na vida.\n Simone de Beauvoir foi uma escritora e filósofa \nfrancesa, cuja voz foi poderosa no existencialismo e no \nfeminismo. Sua obra O Segundo Sexo foi pioneira na \nanálise das opressões enfrentadas pelas mulheres. Ela \ntambém abordou temas como liberdade, autenticidade \ne identidade. Uma influência inspiradora para repensar \no papel das mulheres na sociedade.\n1\n1"
    },
    {
      "number": 11,
      "text": "A melhor escolha é sempre escolher\nNossas vidas, frequentemente, nos confrontam com escolhas difíceis, e, muitas \nvezes, somos surpreendidos por situações inesperadas, para as quais não estamos \npreparados. Embora possamos prever algumas de nossas ações e nos adaptar ao \ncontexto, o futuro permanece imprevisível, e não podemos antecipar o próximo \ndilema que a vida colocará em nosso caminho.\nVOCÊ SABE RESPONDER?\nComo, então, orientar nossas decisões? Como discernir se a escolha que \nfazemos é realmente a correta?\nO ineditismo das situações, que vivenciamos em nosso cotidiano, nos obri ga, constantemente, a decidir (LOPES, 2020). No entanto, nem sempre nossas \ndecisões são as mais acertadas ou corretas. De qualquer forma, toda tomada de \ndecisão revela uma escolha e traz consigo uma consequência.\nPara responder a essa questão sobre a corretude de nossas decisões, devemos \nsempre nos lembrar dos valores e crenças que são fundamentais para nós. Nosso \ncomportamento deve ser fundamentado em práticas sociais sólidas, as quais \nrefletem nossos valores e crenças.\nA ética é um campo de investigação da filosofia que busca compreender \no comportamento humano. Ela nos guia em direção a um agir correto e nos \ndireciona a assimilar temas e questões específicas da vida em sociedade. Nesse \nsentido, a política e as tomadas de decisões na vida social, certamente, podem \nser consideradas elementos centrais no estudo da ética, uma vez que as opções e \nas escolhas, no âmbito da vida pública, visam a alcançar o bem comum.\nUNICESUMAR\n1\n1"
    },
    {
      "number": 12,
      "text": "TEMA DE APRENDIZAGEM 1\n “\nV ocê define através do modular, do exemplar, define através de \nprincípios da sociedade, sejam religiosos ou não. Define através de \nnormatizações. Por exemplo, há 20 anos, nos auditórios, algumas \npessoas fumariam, outras não. Há dez anos, haveria uma placa “é \nproibido fumar” . Hoje, não precisa mais. Hoje, as pessoas o fazem. \nElas introjetaram aquele comportamento social (CORTELLA, \n2009, p. 107).\nEm linhas gerais, podemos identificar a ética como um arcabouço teórico, enquanto a moral é compreendida como a prática da ética. Um dos principais desafios da ética é que, muitas vezes, ela não se aplica com a mesma eficácia a nós \nmesmos como aplicamos aos outros.\nKarnal (2018, p. 41, grifo nosso) propõe uma reflexão perspicaz sobre a ética em \nHamlet e como ela se manifesta na realidade da nossa sociedade: “Poderiam se \nsentir lisonjeados ao pensar que nós somos, todos, profundamente honestos, probos, pessoas experimentadas na ética. Somos Hamlet suspeitando da corrupção \nalheia, mas sentindo-se imune e não conspurcado por ela”.\nEm teoria, devemos usar o mesmo rigor e adotar as mesmas medidas para nós \nmesmos que adotaríamos para os outros. Isso parece ser um princípio básico, \nporém, na maioria das vezes, não é, devidamente, seguido por alguns indivíduos \nem nossa sociedade.\nAinda assim, nos escritos de Mario Sergio Cortella (2009), encontramos um \nconjunto de princípios que pode nos auxiliar nessa tarefa. Perguntas fundamentais, que servem como coordenadas na tomada de decisão, são descritas como \ncentrais em nossas vidas, como: quero? Devo? Posso? Se você conseguir responder a essas três perguntas, de maneira sincera, certamente, será capaz de discernir \nentre o que é certo ou errado, de acordo com o seu entendimento.\n “\nPortanto, o que é ética? São os princípios que você e eu usamos para \nresponder ao “Quero? Devo? Posso?” É preciso remarcar: isso não \nsignifica que você e eu não vivamos dilemas. Eles existem, e serão \nmais tranquilamente ultrapassados quanto mais sólidos forem os \nprincípios que tivermos e a preservação da integridade que desejarmos (CORTELLA, 2009, p. 108).\n1\n1"
    },
    {
      "number": 13,
      "text": "Cortella, ainda, salienta: “[...] tem coisa que quero, mas não devo, tem coisa que \ndevo, mas não posso, tem coisa que eu posso, mas não quero”. A felicidade, nesse \ncaso, resulta, de quando aquilo que você quer é aquilo que você deve e pode. Do \ncontrário, não é, necessariamente, a decisão mais precisa ou acertada. Somos \nlivres para efetuar nossas escolhas, e é, justamente, nessas escolhas que colocamos \na ética em ação.\nE, estudante, as decisões e as escolhas que fazemos em nossas vidas, assim \ncomo em nossa rotina profissional, não são tão simples. No entanto, podemos \nsempre buscar a melhor maneira de lidar com os dilemas e dificuldades que \nencontramos em nossa jornada, refletindo sobre nossas escolhas e ações.\nEssa ideia é tão predominante que, frequentemente, nos referimos às pes soas pelas suas ocupações; por exemplo, dizemos que fulano é professor, sicrana \né dentista, beltrano é advogado. Agora, você pode se perguntar: o que ética e \ncultura têm a ver com minha atividade profissional? A resposta mais óbvia é \nsimplesmente tudo!\nNossas escolhas, renúncias, ações, omissões, hábitos e práticas fazem toda \na diferença, não apenas no âmbito pessoal, mas também na esfera profissional. \nNo livro Por Que Fazemos O Que Fazemos?, Mario Sergio Cortella tenta nos \napresentar uma possível resposta para esses dilemas e preocupações de nosso \ncotidiano.\nO questionamento sobre nossas ações e escolhas, como \"por que faço o que \nfaço?\", leva-nos a pensar sobre o motivo de evitarmos certas ações. Princípios \néticos e a preservação da nossa integridade pessoal são fundamentais. A citação \n\"De nada adianta um homem ganhar o mundo se perder a sua alma\" reforça a \nimportância desses valores essenciais. Embora a conotação possa ser religiosa, a \n\"alma\" simboliza nossa integridade pessoal. Optar por ações éticas, mesmo \nem cenários comuns de ações contrárias, exige abdicações, mas mantém nossa \nidentidade intacta. Isso também se aplica ao ambiente profissional, incluindo a \nempresa, em que a integridade é essencial e o \"escrúpulo\" serve como orientação. \nA ideia de compliance, embora discutida, deve ser incorporada às práticas diárias \npara evitar inconsistências entre discurso e ação, pois a reputação da empresa \né vulnerável em um mundo de informações instantâneas (CORTELLA, 2016).\nUNICESUMAR\n1\n1"
    },
    {
      "number": 14,
      "text": "TEMA DE APRENDIZAGEM 1\nVocê sabia que a deontologia é um ramo dentro do estudo da ética que se \nconcentra nos deveres e normas morais dentro de diferentes profissões? Ela \ndefine princípios que orientam a conduta dos profissionais, visando a garantir \nintegridade e confiança em suas atividades.\nZOOM NO CONHECIMENTO\nA provocação principal e o questionamento central são: devo fazer o errado \nmesmo sabendo que é errado?\nUma palestra incrível do professor Leandro Karnal foi proferida, em2016, na cidade de Blumenau. O tema da palestra é \"Os \nanimais não têm ética\". Nela, o professor explora as nuances \nda ética em diversos aspectos da vida em sociedade.\nOutra palestra magnífica de Leandro Karnal foi proferida no \nCafé Filosófico, em 2015, com o tema “Hamlet de Shakespeare e \no mundo como palco”. Nessa palestra, Karnal analisa a relação \npsicossociológica dos personagens do universo de Hamlet \ne traz à luz questões intrigantes para refletirmos sobre as \nrelações sociais na contemporaneidade.\nEU INDICO\nSegundo ele, a ocasião não cria o ladrão; o ladrão já existe antes mesmo da \nocasião. A ocasião, nesse caso, tem a função de revelar o ladrão . No vídeo, ele \nexplora essa ideia, buscando uma discussão em torno da ética profissional e da \nmoralidade individual. Não é porque os outros fazem que eu devo fazer.\nCertamente, essa não é uma tarefa fácil; se fosse, não seríamos diariamente \nbombardeados com inúmeras matérias nos noticiários sobre comportamentos \ninadequados na esfera política e no âmbito profissional. Ainda assim, é importante lembrar que sempre temos a escolha!\nMesmo quando a situação está difícil e a competição parece desleal, deve mos nos portar de maneira ética, buscando manter nossa integridade inabalável. \nMuitas vezes, o que parece uma vantagem pode se voltar contra nós; o caminho \ndo justo quase nunca é fácil, mas é certamente mais digno.\n1\n4"
    },
    {
      "number": 15,
      "text": "EXPLORANDO AS DIFERENÇAS CULTURAIS\nA antropologia é a ciência que se propõe a estudar o comportamento humano. \nOs antropólogos entendem que os seres humanos, \ncomo seres sociais, se constituem em contextos sociais específicos. Conforme conceitua Lidório (2009), \na antropologia emerge da convergência de diversas \norigens e estudos, moldada por uma história evolutiva de ideias.\nEm outras palavras, ideias tanto do Oriente quanto do Ocidente, como as de \nConfúcio e Franz Boas, contribuíram para seus fundamentos. Boas introduziu a \ndualidade, enfatizando que a cultura é moldada tanto pelo ambiente quanto pelas \nideias. Essa perspectiva dinâmica enriquece nossa compreensão da formação \ncultural. A antropologia evoluiu de uma área dentro da história e filosofia para \numa disciplina abrangente, refletindo a crescente conscientização das complexidades culturais e a necessidade de explorar a identidade humana em seu contexto \nsocial (LIDÓRIO, 2009).\nA complexidade do ser humano é resultado de inúmeros fatores biológicos, psicológicos, históricos, sociais e culturais que moldaram nossa espécie ao longo da \nHistória. Essa diversidade de capacidades nos torna únicos e distintos de outras \nespécies. Somos seres vivos dotados de cognição, linguagem elaborada e capacidade de interação social, o que nos torna seres biopsicossocioculturais.\nA antropologia é \na ciência que se \npropõe a estudar \no comportamento \nhumano\nBIOLÓGICO PSICOLÓGICO\nSOCIAL CULTURAL\nFigura 1 – O ser humano como ser biopsicossociocultural\nFonte: Lopes (2020, p. 52).\nDescrição da Imagem: na figura, temos um esquema com \ncírculos e um boneco em formato humanoide no centro deles. Na parte superior à esquerda, o círculo está preenchido \nna cor verde e escrito de maneira centralizada (Biológico). \nNa parte superior à direita, o círculo é da cor azul e escrito \nde maneira centralizada (Psicológico). Na parte inferior à \nesquerda, o círculo está preenchido na cor rosa e escrito \nde maneira centralizada (Social). Na parte inferior à direita, \no círculo está na cor amarela e escrito de maneira centralizada (Cultural). Fim da descrição.\nUNICESUMAR\n1\n5"
    },
    {
      "number": 16,
      "text": "TEMA DE APRENDIZAGEM 1\nA biologia explica nossa natureza como seres vivos, a psicologia revela nossa \ncapacidade cognitiva, enquanto nossa natureza social nos conecta e nos faz adaptar a padrões comportamentais. Além disso, somos seres culturais, criadores e \ntransmissores de cultura, tanto material quanto imaterial. Essa interseção complexa de fatores molda nossa identidade e influencia nossa relação com o mundo \n(LOPES, 2020).\nExistimos dentro de padrões e regras sociais preestabelecidas. Isso significa \nque, desde o momento em que nascemos, começamos a fazer parte de grupos \nsociais. O primeiro grupo ao qual nos incorporamos é a nossa família, seguida \npor escola, igreja e outros espaços de convívio. Os grupos sociais desempenham \num papel crucial ao permitir a interação social, constituindo componentes de \nentidades maiores denominadas comunidades e sociedades.\nDe acordo com Reinaldo Dias (2010), a comunidade é uma estrutura social com \nvínculos sólidos entre seus membros, refletindo-se na cooperação, confiança e \nbusca pelo bem-estar coletivo. Por outro lado, a sociedade se caracteriza pela \ncompetição, individualismo e prioriza a eficiência e impessoalidade nas inter ações. Seu foco é atender às necessidades de grupos específicos, muitas vezes \nem detrimento de outros.\nEssa intrincada relação pode ser visualizada de maneira mais clara na Figura 2. \nNela, os sociólogos Charon e Vigilant (2012) exploram as dimensões das relações sociais que os indivíduos estabelecem em vários níveis.\n1\n6"
    },
    {
      "number": 17,
      "text": "Sociedade\nComunidade\nGrupos e\norganizações formais\nDíades e grupos\nAlgumas díades, grupos e organizações formais\npodem introduzir-nos em outras comunidades\nFigura 2 – O indivíduo na organização social\nFonte: Charon e Vigilant (2012, p. 60).\nDescrição da Imagem: na figura, temos um esquema com dois círculos, quatro elipses e um boneco em formato humanoide no centro. De fora para dentro da imagem, temos um grande círculo escrito (Sociedade), dentro desse círculo existe \num círculo menor escrito (Comunidade). Aqui, encontram-se quatro elipses sobrepostas e ao centro, um ícone de forma \nhumana (semelhante a um desenho de átomo). Nessa parte, termos as seguintes informações textuais vinculadas às \nelipses (Grupos e organizações formais e Díades e grupos). Fim da descrição.\nSe, dentro de um mesmo grupo social, podemos identificar essas variações, imagine como isso se complexifica ao compararmos diferentes sociedades. A cultura, \nabrangendo aspectos regionais, históricos, religiosos e étnicos, resulta em variações significativas nas práticas sociais e comportamentos.\nNossa necessidade de interação social é tão profunda que é no convívio com os \noutros que construímos nossa identidade como indivíduos. Tente imaginar: tudo o \nque o distingue dos demais e o torna único pode ser basicamente interpretado por \ndois fatores. São eles: os fatores intrínsecos (que dizem respeito somente a você) \ne os fatores extrínsecos (que dizem respeito aos outros).\nUNICESUMAR\n1\n7"
    },
    {
      "number": 18,
      "text": "TEMA DE APRENDIZAGEM 1\nEssa necessidade de interação social possibilita, nessa relação com o outro, a construção e a diferenciação entre o eu e o outro. Essa diferenciação se manifesta de maneira física, linguística, simbólica, cultural e singulariza cada grupo ou indivíduo.\nComo ressalta o antropólogo brasileiro Roque de Barros Laraia (1989, p. 46): \n“O homem é o resultado social do meio em que foi \nsocializado . Nesse sentido, é importante enfatizar o \npapel que o processo educacional, seja ele proporcionado por instituições formais ou informais, desempenha na formação das pessoas.\nImmanuel Kant é outro filósofo que apresenta uma ideia muito clara sobre a \nconstituição daquilo que entendemos como sujeitos. Segundo Kant (1999, p. 14, \ngrifo nosso), \"o homem é aquilo que a educação faz dele\". Em outras palavras, \na educação é o mecanismo pelo qual é possível conduzir o ser humano a um \nprocesso de emancipação.\n“O homem é o \nresultado social \ndo meio em que foi \nsocializado” \nCultura: um conceito antropológico \nAutor: Roque de Barros Laraia \nSinopse: este livro de Roque de Barros Laraia, aborda as raízes \ne dimensões fascinantes da cultura humana. O antropólogo \nexplora de maneira profunda e acessível o conceito-chave da \nantropologia: a cultura. Se você é aficionado por desvendar os \nintricados aspectos das sociedades e seus valores, esse livro \né uma ferramenta indispensável em sua jornada intelectual. \nDesvende os segredos da cultura e enriqueça seu conhecimento com insights que irão expandir sua compreensão do \nmundo ao seu redor.\nINDICAÇÃO DE LIVRO\nA cultura é variável e permeia a capacidade que possuímos de valorar as coisas, isto \né, com o desenvolvimento da antropologia como ciência foi possível identificar \npadrões e comportamentos que se mantém, mas também que se modificam de \num grupo cultural para outro.\n1\n8"
    },
    {
      "number": 19,
      "text": "No fim do século XVIII e início do século XIX, os termos Kultur e Civilization eram utilizados para representar aspectos espirituais e materiais de uma \ncomunidade, respectivamente. Edward Tylor consolidou esses conceitos no termo Culture, abrangendo conhecimentos, crenças, arte, moral, leis e costumes \nadquiridos pelo ser humano como membro de uma sociedade . Tylor enfatizou \na aprendizagem cultural em contraposição à aquisição inata, refletindo a diversidade de realizações humanas. Essa definição ressoa como uma rejeição à visão \netnocêntrica, na qual um grupo considera-se superior aos demais, e destaca a \nriqueza das complexas expressões humanas (LARAIA, 1989).\nOs estudos na área da antropologia se dedicam à exploração do \"outro\", buscando \ncompreender as particularidades e as subjetividades das diversidades culturais e \nsuas relações étnico-raciais, a História e culturas afro-brasileira e indígena. Eles \nreconhecem que diferentes modos de pensamento e vivência do mundo existem. \nA antropologia, desse modo, é a disciplina que se concentra na apreciação e no \nentendimento da diversidade e singularidade cultural. Essa ciência se contrapõe \nao etnocentrismo, que é uma perspectiva em que o observador considera seu \npróprio grupo social como superior aos demais.\nO olhar antropológico sobre a cultura proporciona uma experiência distinta na \nrelação com o outro. Essa experiência leva a um processo de estranhamento em \nrelação à cultura. Nesse exercício, o antropólogo não busca julgar uma cultura \ndiferente, mas, ao contrário, procura compreender o que era incompreensível ou \nestranho à primeira vista.\nO antropólogo polonês Bronislaw Malinowski revolucionou a antropologia ao \npropor um método de investigação participante. Nesse método, chamado de \netnografia, o pesquisador mergulha na cultura que deseja observar e registra, \ncom grande riqueza de detalhes, as práticas e as atividades do cotidiano. \nEssa prática se mostrou altamente eficaz e permitiu que, principalmente, as \nsociedades ocidentais compreendessem as especificidades das sociedades \naborígenes, indígenas e comunidades.\nZOOM NO CONHECIMENTO\nUNICESUMAR\n1\n9"
    },
    {
      "number": 20,
      "text": "TEMA DE APRENDIZAGEM 1\nCompreender a visão dos nativos, explorar suas conexões com a vida e sua compreensão da realidade são tarefas cruciais. Devemos investigar profundamente o \nser humano, incluindo o domínio que a vida exerce sobre ele. Cada cultura possui \nseus próprios valores, ambições individuais e buscas por bem-estar. A exploração \ndesses caminhos pode oferecer novos olhares sobre a mentalidade humana e \niluminar nossa própria essência por meio da compreensão de perspectivas diferentes \ne distantes (MALINOWSKI, 1984).\nO estudo acerca do universo cultural não está restrito apenas à abordagem antropológica, e seu objeto de estudo não se limita somente a comunidades tradicionais. Pessoas que buscam estudar outros grupos sociais certamente conseguem \ncompreender de maneira mais nítida elementos específicos daquela cultura.\nT omemos, como exemplo, um estudioso no campo da arte; ele certamente \nnotará sutilezas nas obras de arte que, muitas vezes, passam despercebidas pelo \npúblico em geral.\nVOCÊ SABE RESPONDER?\nVocê pode se perguntar: por que isso ocorre?\nOra, isso é simples: o estudioso da arte, seja ele um artista, pesquisador ou mesmo \ncrítico, possui uma capacidade treinada para perceber detalhes. Essa habilidade \nnão é inata; ao contrário, é resultado de muito treino e exposição a uma atividade \nespecífica, para que alguém possa dominar um determinado conhecimento.\n1\n1"
    },
    {
      "number": 21,
      "text": "NOVOS DESAFIOS\nO universo do trabalho é uma das nossas âncoras sociais, pois o trabalho em nossa \nsociedade é considerado um elemento tão crucial que \nnossas ocupações funcionais nos constituem. Além de \nsermos consumidores, somos identificados pelo nosso \ntrabalho realizado. Em outras palavras, o que fazemos \ncontribui para definir quem somos. \nPerceba como o conhecimento, que adquirimos sobre cultura, ética e escolhas, está diretamente conectado ao ambiente profissional que você, em breve, \nirá enfrentar. A compreensão de como a cultura influencia nossas percepções e \ndecisões nos prepara para navegar, com confiança, por um mercado de trabalho \nem constante transformação.\nAo identificar a importância da ética em nossas decisões individuais e nas \ninterações sociais, você constrói uma base sólida e cultiva relacionamentos profissionais duradouros e bem-sucedidos. Ainda, ao relacionar teoria e prática, torna-se possível aplicar o conhecimento adquirido em situações do seu cotidiano. \nJá a abordagem antropológica sobre a diversidade cultural, por exemplo, é muito \nvaliosa no ambiente de trabalho globalizado em que vivemos, onde interações \nsensíveis com colegas de diferentes origens são fundamentais.\nAlém disso, ao refletirmos sobre como a cultura e a ética se entrelaçam em \nnossas escolhas diárias, ganhamos a capacidade de tomar decisões informadas, \nque mantenham nossa integridade pessoal e profissional intacta. Desse modo, \nno mercado de trabalho atual, marcado por concorrência e diversidade de demandas, a habilidade de compreender as diversas perspectivas culturais, as suas \nrelações étnico-raciais, a sua história, as culturas afro-brasileira e indígena, as \nnormativas da vida em sociedade e o que posso ou não posso fazer, o sentido \ndas diferenças e, conexões com a própria cultura e suas conectividades e relações \nsociais, o agir com ética e respeito se tornam elementos fundamentais.\nO que fazemos \ncontribui para \ndefinir quem somos \nUNICESUMAR\n1\n1"
    },
    {
      "number": 22,
      "text": "VAMOS PRATICAR\n1. O estudo da diversidade cultural em metrópoles levou ao desenvolvimento de conceitos \ncomo heterogeneidade cultural e subculturas. Eles são usados como ferramentas para \nentender tanto as áreas urbanas quanto os comportamentos empresariais. A partir dos \nanos 1970, o conceito de cultura e subcultura se espalhou, especialmente nos EUA, à \nmedida que as empresas buscavam enfrentar a concorrência japonesa. Surgiu a ideia \nde \"cultura da em presa\", porém, essa noção pode simplificar demais a complexidade cultural, insinuando que uma empresa pode criar uma cultura única. Isso levanta \nquestões sobre manipulação cultural e interpretação ideológica (CARVALHO, 1997).\nFonte: CARVALHO, M. G. de. Antropologia e as culturas organizacionais. Revista Educação & Tecnologia, Curitiba, n. 2, p. 107-114, 1997.\nComo a noção de cultura da empresa é utilizada no ambiente corporativo? Assinale a \nalternativa correta:\na) A cultura da empresa é um conceito antropológico que se refere à diversidade cultural \nnas metrópoles.\nb) A cultura da empresa é uma ideia amplamente aceita de que as empresas podem \ncriar uma cultura exclusiva.\nc) A cultura da empresa é um instrumento conceitual que os antropólogos usam para \nestudar a área urbana.\nd) A cultura da empresa é uma abordagem ideológica que sugere que as empresas \npodem manipular a cultura de seus funcionários.\ne) A cultura da empresa é uma ferramenta utilizada por psicólogos para entender os \naspectos comportamentais das organizações.\n2. “O conceito de democracia é complexo, com diversas facetas e, frequentemente, \ndependente de um contexto histórico. Dessa forma, a democracia, segundo Joseph \nSchumpeter, seria um método político para atingir uma decisão política, como a decisão \nde escolher um representante”.\nFonte: ANDRADE, C. D. R. Melhor candidato é o debate: o debate como influenciador direto para o sucesso de democracias. In: LOPES, G. A. H. (org.). O debate é preciso: reflexões \nacerca do debate. Brusque: Editora Unifebe, 2022. p. 94.\n1\n1"
    },
    {
      "number": 23,
      "text": "VAMOS PRATICAR\nQual é o conceito proposto por Joseph Schumpeter sobre a democracia? Assinale a \nalternativa correta.\na) A democracia é uma forma de governo baseada na concentração de poder nas mãos \nde um único líder.\nb) A democracia é um sistema político em que as decisões são tomadas por um pequeno \ngrupo de elite.\nc) A democracia é um método político para atingir uma decisão política, como a escolha \nde um representante.\nd) A democracia é um sistema em que todas as decisões políticas são tomadas diretamente pela população, sem a necessidade de representantes.\ne) A democracia é uma abordagem filosófica que defende a supremacia do Estado sobre \nos direitos individuais.\n3. O povo Mbyá-Guarani, liderado pelo cacique Agostinho e o professor Cleber, carrega \nnomes guarani, dados pelo pajé, líder espiritual da aldeia. O significado profundo desses nomes é relevante para a comunidade. O nome é concedido quando completam \num ano, marcando o início da identidade individual e coletiva. Lutam para oficializar \nesses nomes perante a sociedade não indígena, eliminando a dualidade. Agostinho \ncompartilha a empatia, respeito e alteridade que permeiam seu grupo. A coletividade \né essencial, cada dor é compartilhada. A religiosidade é forte, desejando que o \"grande \nespírito \" os guie. A língua guarani e a conexão com a natureza refletem a rica cultura. \nSão politeístas, valorizando a terra além do mercado (LOPES, 2018).\nFonte: LOPES, G. P. et al. Conhecer, reconhecer e respeitar: relato de experiência da visita à \naldeia Mbyá-Guarani de Major Gercino (SC). In: ENPEX – ENCONTRO DE ENSINO, PESQUISA E EXTENSÃO, 17., 2018, Brusque. Anais [...]. Brusque: Unifebe – Centro Universitário \nde Brusque, 2018. p. 797-810.\nCom base no texto, qual das seguintes características NÃO é parte das crenças e valores \ndo povo Mbyá-Guarani? Assinale a alternativa correta:\na) Registrar seus nomes guarani oficialmente na sociedade não indígena.\nb) Valorizar a coletividade, empatia e compartilhamento das dores.\nc) Acreditar em uma entidade única como o \"grande espírito\".\nd) Valorizar o individualismo e competição.\ne) Manter a língua guarani e a conexão com a natureza.\n1\n1"
    },
    {
      "number": 24,
      "text": "REFERÊNCIAS\nBUNGE, M. Dicionário de filosofia. Tradução de Gita K. Guinsburb. São Paulo: Perspectiva, \n2012. (Coleção Big Bang).\nCHARON, J. M.; VIGILANT, L. G. Sociologia. 2. ed. São Paulo: Saraiva, 2012.\nCORTELLA, M. S. Por que fazemos o que fazemos? Aflições vitais sobre trabalho, carreira e \nrealização. São Paulo: Planeta, 2016.\nCORTELLA, M. S. Qual é a sua obra?: Inquietações propositivas sobre gestão, liderança e \nética. 8. ed. Petrópolis: Vozes, 2009.\nDIAS, R. Introdução à sociologia. 2. ed. São Paulo: Pearson Prentice Hall, 2010.\nKANT, I. Sobre a pedagogia. Tradução de Francisco Cock Fontanella. 2. ed. Piracicaba: Editora Unimep, 1999.\nKARNAL, L. O que aprendi com Hamlet: porque o mundo é um teatro. Rio de Janeiro: LeYa, 2018.\nLARAIA, R. de B. Cultura: um conceito antropológico. 4. ed. Rio de Janeiro: Jorge Zahar, 1989.\nLIDÓRIO, R. Conceituando a antropologia. Antropos, Brasília, v. 2, n. 3, p. 7-15, dez. 2009.\nLOPES, G. A. H. Instrumentalidade e processo de trabalho do educador social. Indaial: \nUniasselvi, 2020.\nMALINOWSKI, B. Argonautas do Pacífico Ocidental: um relato do empreendimento e da \naventura dos nativos nos arquipélagos da Nova Guiné melanésia. 3. ed. São Paulo: Abril Cultural, 1984.\nSARTRE, J. P. O existencialismo é um humanismo. Tradução de Vergílio Ferreira. São Paulo: Abril, 1973.\n1\n4"
    },
    {
      "number": 25,
      "text": "1. Opção D. A cultura da empresa é um conceito que, muitas vezes, pode ser mal interpretado e até ideologicamente manipulado. A ideia de que a empresa pode criar uma cultura \nprópria e impor isso aos funcionários levanta questionamentos sobre sua autenticidade \ne sobre a manipulação dessa cultura, de acordo com as necessidades da organização.\n2. Opção C. A democracia, conforme proposto por Joseph Schumpeter, é, de fato, um \nmétodo político para atingir uma decisão política, como a escolha de um representante. \nSchumpeter descreveu a democracia como um sistema no qual as decisões políticas são \ntomadas, por meio de competições eleitorais, em que os cidadãos participam e elegem \nrepresentantes, que tomarão as decisões em nome do povo.\n3. Opção D. Valorizar o individualismo e a competição. O texto enfatiza a coletividade, a \nempatia, a conexão com a natureza, a religiosidade e a valorização da língua guarani, o \nque vai contra o individualismo e a competição mencionados na alternativa D e portanto, \nessa é a característica que não faz parte das crenças e dos valores do povo Mbyá-Guarani, \nconforme apresentado no texto.\nCONFIRA SUAS RESPOSTAS\n1\n5"
    },
    {
      "number": 26,
      "text": "MINHAS METAS\nINDAGAÇÕES\nExplorar a jornada pessoal de compreensão dos direitos humanos e seu impacto no eu, \nno você e no nós.\nConhecer as maneiras pelas quais os indivíduos podem contribuir para a promoção e \nproteção dos direitos humanos.\nRefletir sobre minha própria identidade social e seu papel na formação de minha perspectiva sobre a nossa cidadania.\nAnalisar os desafios atuais dos direitos humanos.\nRefletir sobre a responsabilidade pessoal como membro da sociedade e um ser cidadão, \nbem como os meios de propagar os direitos humanos e promover um mundo mais justo.\nRefletir sobre as mudanças atuais no mundo e, assim, incitar o seu protagonismo social.\nEntender as indagações.\nTEMA DE APRENDIZAGEM 2\n1\n6"
    },
    {
      "number": 27,
      "text": "INICIE SUA JORNADA\nComeçamos uma grande jornada! A história do Eu, de Você e de Nós, em uma \nsociedade e seu protagonismo. V amos viajar juntos nestas construção histórica \ndo Eu enquanto protagonista da formação do Nós e da nossa própria história.\nConectados aos preceitos que não vivemos ou convivemos sós, fazemos parte \nda criação do Eu, de V ocê e de Nós. V ocê já embarcou nessa história há muito e \nmuito tempo. Só vamos relembr á-la!\nIsso é muito mais profundo, pois, se você percebeu, foi conduzido pelos autores em um processo de crescimento pessoal em todo o seu âmago, ou seja, \nbuscou-se trabalhar, aqui, a formação de um ser humano completo, por isso, \na analogia com uma “viagem” .\nNós estamos em uma viagem, pessoal de crescimento, e tenho certeza de que \nvocê, hoje, é uma pessoa melhor do que quando iniciou a estudar este caderno.\nT emos que fechar este caderno, porém, infelizmente ou felizmente, ele não \nterminará nestas páginas que você está lendo. Agora, você está abrindo um mundo todo de indagações, ou seja, os “pontos de interrogações” que você está \ncolocando para fazer o mundo melhor.\nV ocê é um cidadão do mundo, consciente de seus direitos e seus deveres para \ntornar este um mundo melhor.\nVocê, cidadão do mundo\nEstá preparado para indagar a vida, as suas contribuições e o convívio em \nsociedade e, por isso mesmo, reforçar todos os aspectos relacionados ao direito \nhumano e à cidadania, formando um ser humano completo, fechando todo o seu \nciclo evolutivo e construindo uma ponte para o futuro.\nUNICESUMAR\n1\n7"
    },
    {
      "number": 28,
      "text": "TEMA DE APRENDIZAGEM 2\nVAMOS RECORDAR?\nPara recordar melhor as questões relacionadas aos direitos \nhumanos, convido-lhe a ler a Declaração Universal dos Direitos Humanos (DUDH), publicada pela Organização das \nNações Unidas (ONU), a qual foi proclamada pela Assembleia \nGeral das Nações Unidas, em Paris, em 10 de dezembro de \n1948.\nVocê poderá acessar a DUDH em sua íntegra em português \natravés do QR Code ao lado.\nÉ uma leitura bem interessante, inclusive para gerar um debate com os seus colegas.\nDESENVOLVA SEU POTENCIAL\nA JORNADA DO CIDADÃO\nO ser humano é um ser em evolução. O ato de pensar faz cada ser humano único, \ndiferente de tudo e de todos.\nAtualmente, temos a revolução da inteligência artificial (IA) dominando os \nassuntos da internet, “bombando” , como se diz na gíria, mas, por outro lado, temos o telescópio James W ebb, o qual, recentemente, trouxe imagens com detalhes \nimpressionantes do que se acredita ser o início do universo, há milhões de anos.\nSão muitas as indagações do Eu para me compreender, para me significar e \nme ressignificar. Muitas as indagações do V ocê num contexto social, de protagonista desses momentos, das suas contribuições sociais individuais. Mais ainda, \ndo grande conjunto que somos o todo, o Nós, da evolução da humanidade, da \nevolução social como um todo.\nSe você começar a fazer uma autorreflexão ou, ainda, debater em grupo sobre \nesses temas evolutivos, provavelmente verá como somos tão diferentes e como \nos nossos pensamentos são tão díspares.\n1\n8"
    },
    {
      "number": 29,
      "text": "VOCÊ SABE RESPONDER?\nDa filosofia de Sócrates, Platão e Aristóteles, dos áureos tempos da Grécia Antiga aos pensamentos atuais relacionados à IA, o ser humano seria o grande “X” \nda equação, pois ninguém sabe os rumos de seus pensamentos?\nIndagações, perguntas e são questionamentos foram os elementos que nos \ntrouxeram até aqui, e o que nos levará ao futuro.\nVOCÊ SABE RESPONDER?\nMas como podemos crescer? Como a nossa sociedade pode evoluir?\nIsso, a História responde: tudo o que você \ne eu vivenciamos está relacionado a nossa \nevolução como sociedade, e a junção das \npessoas em comunidade, em cidades nos \ntrouxe até onde estamos hoje.\nCada dificuldade vivida pela socie dade foi um grande empurrão para se \npensar e trabalhar a sua evolução. V eja a \nRevolução Francesa, a pandemia da “Peste Negra” , a Primeira e a Segunda Guerra \nMundial. T odas as dificuldades da época \ngeraram perdas, mas também evoluções.\nUNICESUMAR\n1\n9"
    },
    {
      "number": 30,
      "text": "TEMA DE APRENDIZAGEM 2\nPara você entender essa evolução de pensamentos, quero \nlhe indicar a leitura de um texto muito antigo que retrata bem \nessas indagações que fazemos. Gostaria que você lesse e refletisse sobre o texto de Platão, A Caverna de Platão, um mito \nque tem corrido os estudiosos pelos séculos e está cada vez \nmais atual.\nAo procurar por “Caverna de Platão” no YouTube, também irá \nencontrar diversos vídeos interessantes sobre o tema, como \neste que estou lhe indicando.\nPense e reflita sobre o tema assunto e em como ele se correlaciona com o que Platão já ensinava há muitos séculos.\nEU INDICO\nDireitos humanos e cidadania\nA história do Eu, de V ocê e de Nós começa em entendermos, então, quais são \nos nossos direitos e deveres, e, assim, termos uma convivência harmônica na \nsociedade atual.\nAssim, as legislações locais e os costumes culturais são um grande balizador \npara o nosso protagonismo humano e social.\nMuitas vezes, as pessoas se horrorizam com certos costumes e culturas, mas \nque, para o povo local, são situações comuns. Por isso, devemos entender e compreender que nem tudo que Eu posso não aceitar é errado, pois a humanidade é \nfeita de diversidade de pensamentos, gostos, religiões, culturas e etnias.\nNesse sentido, podemos dizer que o Direito Humano é um conceito básico, \nque todos precisamos entender e praticar.\nConforme Pieritz, Bonetti e Franzmann (2016, p. 24) expressam:\n “\nOs direitos humanos são o direito próprio que está intrínseco na \nvida do cidadão. Nessa linha é possível compreendermos que cada \nser humano pode usufruir de seus direitos, independentemente de \nraça, cor, religião, sexo, etnia, opinião política, se é rico ou pobre, \nentre outros. Sendo assim, os direitos humanos são garantias previstas em lei, contidas na Declaração Universal dos Direitos Huma1\n1"
    },
    {
      "number": 31,
      "text": "nos, a qual protege o cidadão de toda e qualquer possibilidade de \ntransgressão de sua liberdade e sua dignidade humana (PIERITZ; \nBONETTI; FRANZMANN, 2016, p. 24).\nDenotando que a liberdade que cada um possui é construída primeiro no Eu, \ninicialmente, podendo fazer tudo que possa imaginar. Depois dessa liberdade \nindividual, apresentou a primeira barreira que é o V ocê, ou seja, o Outro.\nSim, a minha liberdade vai até o momento de não ferir a liberdade do Outro, \ndo Vo cê.\nAqui, já entramos em um dogma bastante grande, que são os limites que \nV ocê apresenta para o Eu.\nVOCÊ SABE RESPONDER?\nVocê já parou para refletir sobre os limites impostos pelos outros a você? E se \nnão tivesse esses limites, como você construiria a sua vida? Não se esqueça \nde que temos as amarras culturais e legais como orientadoras dessa decisão.\nUNICESUMAR\n1\n1"
    },
    {
      "number": 32,
      "text": "TEMA DE APRENDIZAGEM 2\nDeclaração Universal dos Direitos Humanos e Constituição \nFederal\nEsses limites, barreiras impostas, são alicerçados pela sociedade moderna e são \ndefinidos, principalmente, pelas leis instituídas em cada país.\nSó para exemplificar, temos, na Declaração Universal dos Direitos Humanos, \npublicada pela Organização das Nações Unidas (ONU):\nARTIGO 1°\nTodos os seres humanos nascem livres e iguais em dignidade e em direitos. \nDotados de razão e de consciência, devem agir uns para com os outros em \nespírito de fraternidade.\nARTIGO 2°\nTodos os seres humanos podem invocar os direitos e as liberdades proclamados \nna presente Declaração, sem distinção alguma, nomeadamente de raça, de cor, \nde sexo, de língua, de religião, de opinião política ou outra, de origem nacional \nou social, de fortuna, de nascimento ou de qualquer outra situação. Além disso, \nnão será feita nenhuma distinção fundada no estatuto político, jurídico ou \ninternacional do país ou do território da naturalidade da pessoa, seja esse país \nou território independente, sob tutela, autônomo ou sujeito a alguma limitação \nde soberania.\nARTIGO 3°\nTodo indivíduo tem direito à vida, à liberdade e à segurança pessoal.\nARTIGO 5°\nNinguém será submetido à tortura nem a penas ou tratamentos cruéis, desumanos ou degradantes.\n1\n1"
    },
    {
      "number": 33,
      "text": "ARTIGO 7°\nTodos são iguais perante a lei e, sem distinção, têm direito a igual proteção da lei.\nARTIGO 9°\nNinguém pode ser arbitrariamente preso, detido ou exilado.\nARTIGO 17°\nToda a pessoa, individual ou coletiva, tem direito à propriedade.\nARTIGO 18°\nToda a pessoa tem direito à liberdade de pensamento, de consciência e de \nreligião; este direito implica a liberdade de mudar de religião ou de convicção, \nassim como a liberdade de manifestar a religião ou convicção, sozinho ou em \ncomum, tanto em público como em privado, pelo ensino, pela prática, pelo culto \ne pelos ritos.\nARTIGO 19°\nTodo o indivíduo tem direito à liberdade de opinião e de expressão, o que implica \no direito de não ser inquietado pelas suas opiniões e o de procurar, receber e \ndifundir, sem consideração de fronteiras, informações e ideias por qualquer meio \nde expressão.\nJá quando vamos para as leis e normativas locais, temos, então, que considerar \na Constituição Federal de 1988, da qual quero destacar os rts. 1º e 5º para a \nnossa discussão:\nUNICESUMAR\n1\n1"
    },
    {
      "number": 34,
      "text": "TEMA DE APRENDIZAGEM 2\nTÍTULO I\nDOS PRINCÍPIOS FUNDAMENTAIS\nArt. 1º A República Federativa do Brasil, formada pela união indissolúvel dos Estados \ne Municípios e do Distrito Federal, constitui-se em Estado Democrático de Direito e \ntem como fundamentos:\nI - a soberania;\nII - a cidadania;\nIII - a dignidade da pessoa humana;\nIV - os valores sociais do trabalho e da livre iniciativa;\nV - o pluralismo político.\nParágrafo único. Todo o poder emana do povo, que o exerce por meio de representantes eleitos ou diretamente, nos termos desta Constituição.\nTÍTULO II\nDOS DIREITOS E GARANTIAS FUNDAMENTAIS\nCAPÍTULO I\nDOS DIREITOS E DEVERES INDIVIDUAIS E COLETIVOS\nArt. 5º Todos são iguais perante a lei, sem distinção de qualquer natureza, garantindo-se aos brasileiros e aos estrangeiros residentes no País a inviolabilidade do \ndireito à vida, à liberdade, à igualdade, à segurança e à propriedade, nos termos \nseguintes:\nI - homens e mulheres são iguais em direitos e obrigações, nos termos desta Constituição;\nII - ninguém será obrigado a fazer ou deixar de fazer alguma coisa senão em virtude \nde lei;\nIII - ninguém será submetido à tortura nem a tratamento desumano ou degradante;\nIV - é livre a manifestação do pensamento, sendo vedado o anonimato;\nV - é assegurado o direito de resposta, proporcional ao agravo, além da indenização \npor dano material, moral ou à imagem;\nVI - é inviolável a liberdade de consciência e de crença, sendo assegurado o livre \nexercício dos cultos religiosos e garantida, na forma da lei, a proteção aos locais de \nculto e a suas liturgias.\nQuadro 1 – Título I e Título II da Constituição Brasileira\nFonte: Brasil (1988, on-line).\n1\n4"
    },
    {
      "number": 35,
      "text": "Uma leitura que todos estudantes de curso superior devem \nfazer é a da Constituição da República Federativa do Brasil \n(1988), principalmente os Títulos I e II, que trazem os Princípios \nFundamentais e Os Direitos e Garantias Fundamentais.\nEU INDICO\nTrouxe essas referências para você entender o crescimento pessoal do individual, \ndo Eu, para o do V ocê, na construção do Nós, mostrando que os limites são postos \npara o bem individual e coletivo, e, assim, formar o conceito de sociedade organizada, em que podemos desenvolver o nosso protagonismo social.\nEssa vivência social é que nos faz também construtores da nossa sociedade.\nO Eu cidadão no Nós\nSe você estudar um pouco da História, analisando as conquistas dos direitos \nsociais, verá que foram escritos por um longo período, perpassando fatos como \na Revolução Francesa, a Revolução Industrial, as guerras mundiais, entre outros \nAinda estamos escrevendo, você verá a revolução que irá ocorrer com as IAs \nque virão!\nUNICESUMAR\n1\n5"
    },
    {
      "number": 36,
      "text": "TEMA DE APRENDIZAGEM 2\nMesmo essas novas realidades podem ser entendidas quando lemos, em Pieritz, Bonetti e Franzmann (2016, p. 161), que a conquista de direitos sociais “é um \nprocesso lento e gradual, resultado dos movimentos sociais e da luta de classes” \ne do aprendizado, da evolução do pensar.\nT emos que cuidar na construção do Eu e do V ocê, para não gerarmos uma \ndeturpação conceitual no NÓS.\nAssim, trazemos o conceito de uma construção do Nós, do nosso protagonismo social e do cidadão.\nT oda essa evolução nos remete à cidadania, ao Nós em vez do individual, \ne, assim, podemos entender a cidadania como apresentado por Costa e Ianni \n(2018, p. 47-48), como:\n “\n[...] o status daqueles que são membros de uma comunidade e são \npor ela reconhecidos. É, também, o conjunto de direitos e deveres \nque um indivíduo tem diante da sociedade da qual faz parte. Historicamente e genericamente, a cidadania tem uma referência espacial, constituída da relação dos indivíduos com um dado território \n(organização sociopolítica do espaço).\nAssim, cidadania é uma noção construída socialmente e ganha \nsentido nas experiências sociais e individuais. Por isso, será, aqui, \ncompreendida como uma identidade social política. Ora, se identidade pessoal/individual é o conjunto das características e dos traços \npróprios de um indivíduo, a identidade social são as características \nque o identificam perante as demais comunidades. E, em certa medida, a consciência de pertencer a algo maior, a um coletivo, a uma \nsociedade (COSTA; IANNI, 2018, p. 47-48).\nAgora, Eu e V ocê ultrapassamos as dimensões individuais e chegamos no coletivo, na construção de uma sociedade pautada em direitos e deveres, na qual \ntodos nós precisamos seguir para que haja harmonia e paz entre as pessoas que \ncompõem a sociedade como um todo.\n1\n6"
    },
    {
      "number": 37,
      "text": "Para você aprofundar mais seus conhecimentos relaciona dos à cidadania, recomendo a leitura do texto O conceito \nde cidadania, de Maria Izabel Sanches Costa e Aurea Maria \nZollner Ianni.\nEU INDICO\nVOCÊ SABE RESPONDER?\nFaça uma análise sobre a importância das leis e das culturas locais para a concepção do ser Cidadão Social.\nA expansão do conceito de cidadania e a sociedade moderna, em si, levam, conforme Geaquinto (2010), a vinculação desses conceitos à questão da participação \npolítica dos indivíduos, sendo um direito seu, mas, também, por outro lado, \ntemos o dever do Estado em oferecer condições mínimas adequadas, para que \npossa se fazer o exercício desse poder.\nA cidadania, o respeito pelos outros e as questões políticas relacionadas à sociedade moderna fazem de todos nós um ser vivo, no qual, conforme Geaquinto \n(2010), todas as partes contribuem para uma vivência plena e feliz.\nUNICESUMAR\n1\n7"
    },
    {
      "number": 38,
      "text": "TEMA DE APRENDIZAGEM 2\nFigura 1 – Evolução do Eu para um protagonista social\nFonte: Pieritz (2023, p. 3).\nDescrição da Imagem: a figura apresenta um triângulo invertido: em sua base está o Eu, que retrata o início da \njornada da pessoa com todos os seus aprendizados e contribuições; logo acima, traz a família, pois ela é a base da \nsociedade e na qual se inicia a socialização das pessoas. Acima da Família, a figura traz toda a Sociedade, na qual o \nEu e a Família estão inseridos e compondo todo o conjunto de contribuição social. E, por último, temos a Cidadania, \nque é formada por todos os membros da sociedade, influenciados pelas suas culturas e contribuições pessoais \ne coletivas. Esse conjunto todo apresenta o crescimento do Protagonismo Social de todos nós. Fim da descrição.\nQuando associamos a Declaração Universal dos Direitos Humanos, publicada \npela ONU, a nossa Constituição Federal, vimos que a o ser cidadão é algo que \ntodos buscamos, mas essa busca é de difícil manutenção, principalmente, pela \nrelação individual e pelas interpretações que cada um dá a esses objetos.\nConforme apresenta Hunt (2009), a construção dos direitos humanos foi \nfeita ao longo dos anos de História e conquistas obtidas pelos homens, definindo \ndireitos e deveres entre as pessoas, tornando-as cidadãs de um mundo melhor e \ncom mais dignidade individual e familiar.\nE você está ajudando a construir uma cidadania com direitos e respeitos pelo \npróximo, pelo Nós.\n1\n8"
    },
    {
      "number": 39,
      "text": "Curso de Direitos Humanos\nEditora: Saraiva\nAutor: André de Carvalho Ramos\nSobre o Livro: André de Carvalho Ramos, Curso de Direitos \nHumanos, que nos traz a evolução histórica e os principais \ndocumentos relacionados aos Direitos Humanos.\nInclusive, saiu uma edição nova em 2023. Aproveite e \naprenda mais sobre este assunto, principalmente, se você \nnão é da área de humanas, para se familiarizar com o \ntema, pois ele é bem detalhista, mas, principalmente, para \nvocê que é da área e precisa conhecer a fundo sobre este \nTema. Eu recomendo.\nINDICAÇÃO DE LIVRO\nAssim, o Nós está relacionado, também, aos outros, então, temos pautado como \nrégua de linha os direitos, que a sociedade em geral precisa seguir.\nAssim, a ONU, ao divulgar a Declaração Universal dos Direitos Humanos, \ndescreveu um conjunto de direitos, considerados indispensáveis para uma vida \nhumana mais justa, baseada em liberdade, igualdade e, principalmente, na dignidade das pessoas em geral.\nConsiderando esses três pontos, liberdade, igualdade e dignidade, te mos, assim, um conjunto mínimo de direitos tidos essenciais para uma vida \nplena e digna.\nNo entanto, como coloca Ramos (2023), as necessidades humanas variam, levando-se em conta o contexto histórico da época em consideração, assim, não tem \ncomo condenarmos o passado sem entender e reconhecer o contexto.\nClaro que não queremos eximir a responsabilidade dos fatos históricos horrendos que ocorreram em diversas partes do mundo, inclusive no Brasil.\nUNICESUMAR\n1\n9"
    },
    {
      "number": 40,
      "text": "TEMA DE APRENDIZAGEM 2\nA evolução cidadã continua\nNas questões atuais, relacionamos, ainda, o Nós com essa nova efervescência que \nestamos vivenciando, como as IAs, viagens espaciais e carros voadores. T udo isso \nestá explodindo agora. Ramos (2023) expõe que as novas demandas sociais, que \nsão produzidas pela modernidade, são traduzidas juridicamente e atualizadas \nna lista dos direitos humanos.\nLogo, o que vale hoje, pode ser arcaico amanhã. Por isso, a importância do \ncrescimento do Eu e V ocê, porque o Nós continua evoluindo, queiramos ou não.\nNão sei se você percebeu, mas mesmo aqui, neste tópico, você já evoluiu como \npessoa, saiu do individualismo inconsciente da caverna de Platão para o vasto \nmundo em que possuímos direitos respaldados pela nossa dignidade humana. \nT odavia, também temos deveres, pois o Nós também ressalta que não podemos \ntolher os nossos irmãos humanos de seus direitos, igualdade para todos.\nA relação da dignidade, das relações humanas e da cidadania revela o tecido intrincado e essencial subjacente à nossa humanidade compartilhada e que trouxe \nvocê nestas construção do seu Eu.\n4\n1"
    },
    {
      "number": 41,
      "text": "Por meio de lentes acadêmicas, você examinou e aprendeu a natureza, a intrincada dinâmica das relações humanas e a importância da cidadania na promoção de uma sociedade justa e inclusiva, pois o Nós traz todos para a coletividade \ne para a vivência em paz.\nA dignidade da pessoa humana, como aspecto fundamental da existência \nhumana, abrange tanto o valor intrínseco quanto o reconhecimento desse valor \npelos outros.\nÉ por meio da dignidade que os indivíduos obtêm um senso de autorrespeito, \narbítrio e valor, ao mesmo tempo em que reconhecem a dignidade inerente a \ntodo ser humano.\nAo reconhecer a natureza universal da dignidade, cultivamos um ambiente \nque promove o respeito, a justiça e a igualdade, promovendo, assim, relações \nhumanas significativas e construtivas para todos nós.\nAs relações humanas, em sua essência, são os blocos de construção da coesão \nsocial e da interconexão entre os indivíduos, assim, perpassando por todo um processo de amadurecimento pessoal do Eu para a vivência no coletivo, na sociedade \nno Nós completo.\nPor meio de nossa exploração, identificamos a intrincada interação de poder, \nempatia, comunicação e diversidade cultural nas relações humanas.\nReconhecer as nuances e as complexidades inerentes a essas dinâmicas modernas e entre as pessoas nos permite navegar e resolver conflitos, promover o \nentendimento e proporcionar empreendimentos colaborativos.\nAo promover relações humanas positivas e empáticas, nutrimos comunidades \ninclusivas que celebram a diversidade e abraçam a riqueza de perspectivas variadas.\nAssim, a cidadania nos leva para além dos marcos legais, representa uma \nresponsabilidade ética e participativa perante a sociedade.\nComo cidadãos engajados, temos o dever de contribuir ativamente para a \nmelhoria de nossas comunidades e do mundo como um todo.\nA nossa ligação com a cidadania implica defender os princípios democráticos, defender a justiça social e reconhecer os direitos e responsabilidades inerentes que acompanham a participação em um coletivo.\nUNICESUMAR\n4\n1"
    },
    {
      "number": 42,
      "text": "TEMA DE APRENDIZAGEM 2\nAo abraçar o conceito de cidadania, nos capacitamos para efetuar mu danças positivas, cultivar a coesão social e construir uma sociedade mais \nequitativa e compassiva.\nLogo, temos uma responsabilidade maior do Eu evoluído (estudado) em relação à sociedade (Nós) como um todo. Essa é a sua responsabilidade!\nA Lista de Schindler\nDirigido por Steven Spielberg, o filme retrata a verdadeira \nhistória de Oskar Schindler, um empresário alemão, que \nsalvou a vida de mais de mil refugiados judeus durante o \nHolocausto. O filme chama a atenção para as atrocidades \ncometidas contra judeus e outros grupos perseguidos durante a Segunda Guerra Mundial, enfatizando a importância de reconhecer e defender os direitos humanos diante \nda discriminação e da violência. Vale muito a pena assistir, \npois o filme traz muitos pontos importantes para você refletir \nsobre a evolução das pessoas, a dignidade e o protagonismo \nde pessoas, que influenciaram todo um contexto social.\nINDICAÇÃO DE FILME\nEm essência, a exploração da dignidade, das relações humanas e da cidadania nos \nobriga a refletir sobre nossos próprios papéis como indivíduos e como membros \nda sociedade. Exorta-nos a lutar, continuamente, pelo crescimento pessoal, empatia e compreensão, ao mesmo tempo em que promove um espírito coletivo de \nrespeito, justiça e igualdade.\nApós todo esse aprofundamento teórico sobre o Nós cidadão e os direitos humanos, faça uma reflexão individual dos pontos que você precisa melhorar para \najudar a melhorar a sua comunidade em relação ao pertencimento de todos e \nao seu crescimento como cidadão de um mundo mais igual.\nPENSANDO JUNTOS\n4\n1"
    },
    {
      "number": 43,
      "text": "Ao adotar esses conceitos e incorporá-los em nossos esforços, podemos pro mover um ambiente que celebra a dignidade humana, nutre relações humanas \nharmoniosas e defende os valores da cidadania responsável, abrindo caminho \npara um futuro mais brilhante e inclusivo.\nFaça parte dessa evolução do Eu, do V ocê e do Nós, o primeiro passo foi dado!\nNOVOS DESAFIOS\nNa verdade, é agora que começa…Novos desafios para você!\nA construção do Eu, de V ocê e do Nós é algo complexo e simples ao mesmo \ntempo, pois, apesar de depender do coletivo, da sociedade, começa com as contribuições individuais de cada um dos Eus que estão lendo e fazendo este curso. \nT udo o que aprendemos nos leva ao nosso protagonismo.\nÉ simples porque é o passo adiante que cada um dá, mas, também, é complexo \nporque amarra todos os Nós, definindo uma sociedade mais igualitária e humana, fazendo um futuro melhor para todos.\nEstes é o momento de você refletir, pegar as ferramentas que lhe serão dadas \ne ajudar a fazer um mundo melhor, e não é difícil.\nCada um fazendo a sua parte na família, na comunidade e no trabalho conseguirá deixar um futuro melhor para a humanidade, e temos muito ainda a fazer.\nO que você vai fazer?\nSão tantas indagações!\nUNICESUMAR\n4\n1"
    },
    {
      "number": 44,
      "text": "VAMOS PRATICAR\n1. O ser humano tem evoluído nos últimos milênios, criando diversas tecnologias e for mas de viver em uma sociedade digna e cidadã para todos. Essa evolução, apesar de \nser sentida por toda a sociedade, é fomentada pelo Eu crítico, pensador, que busca \nsempre por novos desafios, crescimento pessoal e formação de um cidadão completo. \nAnalisando o Eu pessoa e a sua evolução, na construção de um Você (família) e de um \nNós, como sociedade, formam cidadãos mais completos. Assim, podemos afirmar que:\na) A evolução do Eu por meio de aquisição de conhecimentos, amadurecimento pessoal, \nfazendo o Eu tornar-se uma pessoa melhor em todos os aspectos ajuda a formar um \nVocê é um Nós mais justo e cidadão, fazendo, assim, um mundo melhor.\nb) A evolução de algumas poucas pessoas é o suficiente para a geração de um mundo melhor.\nc) O Eu não tem necessidade de evoluir com a aquisição de conhecimentos, amadurecimento pessoal, pois o Eu torna-se uma pessoa melhor mesmo não fazendo nada, \nmas, assim mesmo, forma um Você e um Nós mais justo e cidadão, fazendo, assim, \num mundo melhor.\nd) A evolução do Eu não contribui na formação de Você, do Nós e da sociedade.\ne) O Eu não contribui na formação do Você e do Nós, no âmbito da sociedade.\n2. Um dos pontos primordiais da sociedade moderna está na questão da prática, por todos \nque a compõem, dos princípios instituídos pela Organização das Nações Unidas (ONU) \nna Declaração Universal dos Direitos Humanos, a qual foi proclamada pela Assembleia \nGeral das Nações Unidas, em Paris, em 10 de dezembro de 1948. Assim, considerando o \nconceito de direitos humanos, analise as alternativas apresentadas e assinale a correta:\na) Os direitos humanos são os direitos próprios que estão intrínsecs o na vida do cidadão. \nNessa linha, é possível compreendermos que cada ser humano pode usufruir de seus \ndireitos, independentemente de raça, cor, religião, sexo, etnia, opinião política, classe \nsocial, entre outros.\nb) Os direitos humanos são os direitos próprios que estão intrínsecos aos cidadãos de \npaíses desenvolvidos e por isso, foram promulgados na França. Nessa linha, é possível \ncompreendermos que cada ser humano, que mora nesses países, pode usufruir de \nseus direitos, independentemente de raça, cor, religião, sexo, etnia, opinião política, \nclasse social, entre outros.\nc) Os direitos humanos são os direitos próprios que estão intrínsecos aos cidadãos ricos \nde países desenvolvidos.\nd) Os direitos humanos são os direitos que estão intrínsecos somente aos cidadãos ricos \nde países desenvolvidos.\ne) Os direitos humanos são os direitos que estão relacionados a casos de Justiça, quando \num réu vai a júri popular por seu crime.\n4\n4"
    },
    {
      "number": 45,
      "text": "VAMOS PRATICAR\n3. Depois da Segunda Guerra Mundial e as diversas declarações de barbárie cometidas, \na Organização das Nações Unidas (ONU) publicou a Declaração Universal dos Direitos \nHumanos, a qual foi proclamada por todos como uma carta-guia a todos os povos livres \ndo planeta Terra. Foram muitos os países que a aceitaram e, inclusive, colocaram seus \nprincípios em prática. Identifique a opção correta que apresenta a referência a um artigo apresentado na Declaração Universal dos Direitos Humanos apresentado pela ONU:\na) Todos os seres humanos nascem livres e iguais em dignidade e em direitos. Dotados \nde razão e de consciência, devem agir uns para com os outros em espírito de fraternidade.\nb) Todos os seres humanos nascem presos ao sistema e iguais em dignidade e em direitos. Dotados de limites, devem agir uns para com os outros em espírito de fraternidade.\nc) Todos os seres humanos nascem livres e iguais em dignidade e em direitos. Dotados \nde limites, devem agir uns para com os outros em espírito de concorrência.\nd) Todos os seres humanos nascem livres e desiguais em direitos. Dotados de limites de \nconsciência, devem agir uns para com os outros em espírito de fraternidade.\ne) Todos os seres humanos nascem livres e são diferentes nas questões legais conforme \na sua classe social. Dotados de razão e de consciência, devem agir uns para com os \noutros em espírito de fraternidade.\n4\n5"
    },
    {
      "number": 46,
      "text": "REFERÊNCIAS\nBRASIL. [Constituição (1988)]. Constituição da República Federativa do Brasil de 1988. \nBrasília, DF: Presidência da República, [2022]. Disponível em: http:/ /www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm. Acesso em: 31 ago. 2023.\nCOSTA, M. I. S.; IANNI, A. M. Z. O conceito de cidadania. In: COSTA, M. I. S.; IANNI, A. M. Z. Individualização, cidadania e inclusão na sociedade contemporânea: uma análise teórica. \nSão Bernardo do Campo: Editora UFABC, 2018. p. 43-73.\nGEAQUINTO, W. S. Cidadania, o direito de ser feliz: iguais e desiguais, até quando? São \nPaulo: Ed. Biblioteca 24 Horas, 2010.\nHUNT, L. A. A invenção dos direitos humanos: uma história. São Paulo: Companhia das \nLetras, 2009.\nONU – ORGANIZAÇÃO DAS NAÇÕES UNIDAS. Declaração Universal dos Direitos Humanos. Brasília, DF: ONU, 2020. Disponível em: https:/ /brasil.un.org/pt-br/91601-declara%C3%A7%C3%A3o-universal-dos-direitos-humanos. Acesso em: 31 ago. 2023.\nPIERITZ, V. L. H. Cidadania e Protagonismo Social. Indaial: Vitru Educação, 2023. [? slides], \ncolor., 25 ×20 cm.\nPIERITZ, V. L. H.; BONETTI, J. C. S.; FRANZMANN, N. M. Direitos humanos e cidadania. Indaial: Uniasselvi, 2016.\nRAMOS, A. de C. Curso de direitos humanos. 10. ed. São Paulo: Saraiva, 2023.\n4\n6"
    },
    {
      "number": 47,
      "text": "1. Opção A. A evolução de uma pessoa, principalmente, em sua educação/conhecimento \ntraz responsabilidades maiores ao Eu, e, por consequência, ajuda na formação de uma \nfamília mais consistente (o Você), assim como traz melhorias para toda a sociedade.\nPara exemplificar, podemos utilizar o estudante que, em sua fase atual, é um mero aprendiz, evoluindo em seu conhecimento e trato profissional. No entanto, após formado, \nespera-se dele toda uma contribuição profissional, fazendo um Você e um Nós diferente, \ndepois de formado, a sua contribuição será de atitudes profissionais e a sociedade o verá \ncomo médico, enfermeiro, professor, administrador etc.\n2. Opção A. O conceito apresentado como alternativa correta está está embasado na Declaração dos Direitos Humanos da ONU.\n3. Opção A. Todos os seres humanos nascem livres e iguais em dignidade e em direitos. \nDotados de razão e de consciência, devem agir uns para com os outros em espírito de \nfraternidade. Este texto é a íntegra do artigo primeiro da Declaração Universal dos Direitos \nHumanos promulgado pela ONU.\nCONFIRA SUAS RESPOSTAS\n4\n7"
    },
    {
      "number": 48,
      "text": "TEMA DE APRENDIZAGEM 2\n4\n8"
    }
  ]
};
